### ISSUE TITLE
[Usage] Entry Not Found for url: https://huggingface.co/liuhaotian/LLaVA-7b-delta-v0/resolve/main/pytorch_model.bin.

### ISSUE THREAD

**Issue by npurson** [haotian-liu/LLaVA#100]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

I encountered an error while converting the weight of LLaMA-7B to LLaVA using the following command:

```bash
python3 -m llava.model.apply_delta \
    --base checkpoints/llama-7b-hf \
    --target checkpoints/llava-7b-v0 \
    --delta liuhaotian/LLaVA-7b-delta-v0
```

The error message I received is as follows:

```
HTTPError                                 Traceback (most recent call last)
~/envs/miniconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py in hf_raise_for_status
    258     try:
--> 259         response.raise_for_status()
    260     except HTTPError as e:


/usr/local/lib/python3.10/dist-packages/requests/models.py in raise_for_status
    959         if http_error_msg:
--> 960             raise HTTPError(http_error_msg, response=self)
    961 

HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/liuhaotian/LLaVA-7b-delta-v0/resolve/main/pytorch_model.bin

The above exception was the direct cause of the following exception:

EntryNotFoundError                        Traceback (most recent call last)
~/envs/miniconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub/file_download.py in cached_download
    688             )
    689             headers.pop("Accept-Encoding", None)
--> 690             hf_raise_for_status(r)
    691             etag = r.headers.get(HUGGINGFACE_HEADER_X_LINKED_ETAG) or r.headers.get("ETag")
    692             # We favor a custom header indicating the etag of the linked resource, and

~/envs/miniconda3/envs/llava/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py in hf_raise_for_status
    267         elif error_code == "EntryNotFound":
    268             message = f"{response.status_code} Client Error." + "\n\n" + f"Entry Not Found for url: {response.url}."
--> 269             raise EntryNotFoundError(message, response) from e
    270
    271         elif error_code == "GatedRepo":

EntryNotFoundError: 404 Client Error. (Request ID: Root=1-6454f263-14b6f0b24a4090276df28333)

Entry Not Found for url: https://huggingface.co/liuhaotian/LLaVA-7b-delta-v0/resolve/main/pytorch_model.bin.
```

The URL https://huggingface.co/liuhaotian/LLaVA-7b-delta-v0/resolve/main/pytorch_model.bin could not be accessed, resulting in an HTTP 404 error. It is worth noting that I was able to successfully download from https://huggingface.co/liuhaotian/LLaVA-7b-delta-v0/resolve/main/config.json just prior to this error. Additionally, I attempted to open the aforementioned URL in my browser, but it was also inaccessible. This leads me to believe that the issue is not related to my local environment.

Please let me know if you have any insights regarding this issue.

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our work.

I am wondering if this is only happening to this specific model or to all the models that we have released?  Not sure if it due to the network issue, but if the [model list](https://huggingface.co/liuhaotian/LLaVA-7b-delta-v0/blob/main/pytorch_model.bin.index.json) is loaded successfuly, it should know that there are two shards of the model checkpoint, and should not look for `pytorch_model.bin`.
