### ISSUE TITLE
[Usage] Gradio Web interface can not open, Google browser http://0.0.0.0:40000 display ' the page does not work 0.0.0.0 is currently unable to handle this request. HTTP ERROR 502'

### ISSUE THREAD

**Issue by yang606** [haotian-liu/LLaVA#1005]
### Describe the issue

Issue:
I 'm operating on Windows 11, GPU : RTX4060, with LLaVA checkpoint : liuhaotian / llava-v1.5-7b prepared locally.
Command:
python -m llava.serve.controller --host 0.0.0.0 --port 10000
![image](https://github.com/haotian-liu/LLaVA/assets/150589589/d4e2625d-f48b-481c-b383-11c1a68b69a3)

python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload
![image](https://github.com/haotian-liu/LLaVA/assets/150589589/b2379ea1-38e1-4e68-b3bf-516d84f52d83)

python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-v1.5-7b
![image](https://github.com/haotian-liu/LLaVA/assets/150589589/f45cd72d-3427-47dd-aa21-b21738d55f47)

Click the web page http://0.0.0.0:40000. But it shows :
![image](https://github.com/haotian-liu/LLaVA/assets/150589589/b24d8e18-b420-42d6-a69c-b145288d9add)

My network connection is normal. Why can 't open the web page, how to solve it ? Do I have any other questions ?

**Comment by liwenyang-911** [comment]
This is because this is not a public IP address

**Comment by yang606** [comment]
> This is because this is not a public IP address
Okay, thank you very much！

**Comment by cryptonome** [comment]
Gradio is running on http://0.0.0.0:7860/ as indicated in the logs.

**Comment by haotian-liu** [comment]
Gradio interface should be at http://127.0.0.1:7860/

Thanks.
