### ISSUE TITLE
[Feature request] - Integrate MPT from MosaicML

### ISSUE THREAD

**Issue by altryne** [haotian-liu/LLaVA#101]
### feature

Hi dear LLaVa maintainers. 

Mosaic has just released their new OpenSource model called MPT-7B and they claim it's fully open source and is matching LLaMa while having up to 65K token window! 

![image](https://user-images.githubusercontent.com/463317/236505791-2739fa48-094b-4d94-8b55-f189621c1c11.png)

Would be incredible to see it used inside LLaVa

https://www.mosaicml.com/blog/mpt-7b

**Comment by haotian-liu** [comment]
Hi @altryne

It's released!  Thanks to the LLaVA-lightning, we are able to release it today.

Checkout the Tweet [here](https://twitter.com/imhaotian/status/1654905800165392384).
Checkout the instructions [here](https://github.com/haotian-liu/LLaVA#LLaVA-MPT-7b).

**Comment by altryne** [comment]
Incredible effort @haotian-liu 👏 Did NOT expect this to be resolved this quick! Super exciting! Thank you for the effort. (boosted on twitter)
