### ISSUE TITLE
Any plans to release the pretrain weights for Llava-7b?

### ISSUE THREAD

**Issue by jihan-yin** [haotian-liu/LLaVA#103]

**Comment by haotian-liu** [comment]
Hi, thanks for your interest in our work.

Our 7b weights are released here: https://github.com/haotian-liu/LLaVA#llava-weights

Include one based on Vicuna v0, and our lightning model based on Vicuna v1.1.

**Comment by jihan-yin** [comment]
Ah I meant the pretrained projector weights, not the final weights after fine-tuning

**Comment by haotian-liu** [comment]
Hi @jihan-yin, it's uploaded here just now, thanks.

https://huggingface.co/liuhaotian/LLaVA-13b-pretrain-projector-v0/blob/main/LLaVA-7b-pretrain-projector-v0-CC3M-595K-original_caption.bin

**Comment by jihan-yin** [comment]
Also just wanna confirm, these are based off Vicuna v0 right?

**Comment by haotian-liu** [comment]
Yes you are right.

**Comment by jihan-yin** [comment]
Thanks for the help so far! Though I'm trying to load the new pretrained weights locally, and am getting an error.

```
import torch

mm_projector_weights = torch.load(pretrain_mm_mlp_adapter, map_location="cpu")
```

gets 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by jihan-yin** [comment]
Actually, this is because I downloaded the weight file incorrectly. Redownloading with git-lfs fixed the issue. Thanks!
