### ISSUE TITLE
when i run finetune_lora.sh，it get the error message,how can i solve it?

### ISSUE THREAD

**Issue by hongdangshao** [haotian-liu/LLaVA#1034]
### Question

Traceback (most recent call last):
  File "/home/LLaVA/llava/train/train_mem.py", line 6, in <module>
    from llava.train.llama_flash_attn_monkey_patch import replace_llama_attn_with_flash_attn
  File "/home/LLaVA/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (/home/LLaVA/llava/model/__init__.py)

**Comment by betterftr** [comment]
same

**Comment by hongdangshao** [comment]
您的邮件已收到！请放心！

**Comment by betterftr** [comment]
reinstalled pip install --upgrade charset_normalizer and it seems resolved... Windows11

**Comment by zhangboshen** [comment]
same

**Comment by haotian-liu** [comment]
We find that this is due to `flash-attn` compiled previously with a different version of pytorch. Please reinstall that with:

```
pip install flash-attn --no-build-isolation --no-cache-dir
```

**Comment by rkuo2000** [comment]
I had the same issue, resolved after `pip install flash-attn --no-build-isolation --no-cache-dir`

**Comment by hongdangshao** [comment]
I have got it!Thanks's.
