### ISSUE TITLE
Still weak on OCR capbility

### ISSUE THREAD

**Issue by lucasjinreal** [haotian-liu/LLaVA#1055]
![image](https://github.com/haotian-liu/LLaVA/assets/21303438/38a7b724-3a7f-4930-9546-d9e2a7f155fd)

Event Qwen1.8B can reads all text on this image...

**Comment by AbrahimZaman360** [comment]
Right it need to be finetuned with Korean Dataset!

**Comment by haotian-liu** [comment]
We have not finetuned it for Chinese OCR yet. Stay tuned for an updated version with improved Chinese OCR.

**Comment by lucasjinreal** [comment]
Is this improved Chinese OCR will be release as well?
