### ISSUE TITLE
[Question] mismatch setting in training stage one.

### ISSUE THREAD

**Issue by jyC23333** [haotian-liu/LLaVA#1059]
### Question

I find that the setting in ```pretrain.sh```  is mismatched with the pap

As mentioned in paper, LLM should be freezed, but in the pretrain script, the LLM weights are not freezed.

**Comment by haotian-liu** [comment]
`--tune_mm_mlp_adapter True` shall make LLM weights frozen.

https://github.com/haotian-liu/LLaVA/blob/main/scripts/pretrain.sh#L22

**Comment by jyC23333** [comment]
Thanks.
