### ISSUE TITLE
[Question] llava 1.6 use mistral 7b instruct

### ISSUE THREAD

**Issue by RyanHuangNLP** [haotian-liu/LLaVA#1061]
### Question

I wondered that which version of mistral using in llava 1.6, instruct or base?

**Comment by haotian-liu** [comment]
Base LLM: [mistralai/Mistral-7B-Instruct-v0.2](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2)

You can check out our model card for different variants of our llava-v1.6 models. Thanks.

https://huggingface.co/liuhaotian/llava-v1.6-mistral-7b
