### ISSUE TITLE
How to finetune llava v1.5 model with chinese instruction dataset?

### ISSUE THREAD

**Issue by hongdangshao** [haotian-liu/LLaVA#1062]
### Question

hello, I want to know if  llava v1.5 model can finetune with chinese instruction dataset?Does the model support Chinese like english?

**Comment by haotian-liu** [comment]
It is not finetuned with Chinese instructions and simply generalizes to answer questions in Chinese zero-shot, while you can finetune it on Chinese instruction dataset to allow it better.

**Comment by hongdangshao** [comment]
I have got it!Thanks's.
