### ISSUE TITLE
[Question] how to solve library version conflict?

### ISSUE THREAD

**Issue by Hesh0629** [haotian-liu/LLaVA#1064]
### Question

<img width="1128" alt="Screenshot 2024-02-04 at 3 14 39 AM" src="https://github.com/haotian-liu/LLaVA/assets/57738176/d475f8ce-7a29-4083-8ce7-f0251f949464">
Hello liu, thank you for releasing code and i'm trying to install LLaVA with your guide.   

however, there's a problem when i try to install library with "pip install -e ".[train]" and it seems like i can't use gradio 4.16.0 and deepspeed 0.9.5 together.  
how can i use it together? can i use lower version of gradio or deepspeed?

**Comment by wd9702** [comment]
I had the same issue and  manually changed the dependencies of Gradio to 3.35.2 and gradio-client to 0.2.9 to earlier version.

**Comment by haotian-liu** [comment]
Sorry for the inconvenience. Fixed in https://github.com/haotian-liu/LLaVA/releases/tag/v1.2.2.post1
