### ISSUE TITLE
[Usage]  Question of initialize Cuda

### ISSUE THREAD

**Issue by wd9702** [haotian-liu/LLaVA#1065]
### Describe the issue

Issue:

I set the cuda version to 11.8 to match torch version. But after install the project with "pip install -e .", and when i tried to test locally, the error message saying "Torch not compiled with CUDA enabled".

I manually uninstall torch and reinstall with "pip3 install torch==2.0.1 torchvision==0.15.2 torchaudio --index-url https://download.pytorch.org/whl/cu118", the cuda is availabe for torch now, but i got a new error message: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model'

What would be procedure of unitilizing GPU in the installation process?

**Comment by anindita127** [comment]
Hi, what was the solution to this issue?

**Comment by wd9702** [comment]
> Hi, what was the solution to this issue?

It is gone with the newest version in Linux OS
