### ISSUE TITLE
[Usage] LoRA fine-tune script error

### ISSUE THREAD

**Issue by mao-code** [haotian-liu/LLaVA#1071]
### Describe the issue

When I was fine-tuning LLaVA using the script in script/finetune_lora.sh, I encounter this error:

```
Traceback (most recent call last):
  File "/content/LLaVA/llava/train/train_mem.py", line 1, in <module>
    from llava.train.train import train
ModuleNotFoundError: No module named 'llava'
```

Although I changed my current directory to LLaVA/, I still keep getting this error.
Is there anything I haven't considered, yet?

**Comment by NuiMrme** [comment]
Hello there, I've seen you marked it as Completed. Would you please explain how did you solve it ? thanks

**Comment by mao-code** [comment]
I found that I just mistakenly typoed the file path in the script.

NuiMrme ***@***.***> 於 2024年3月4日 週一 下午10:57寫道：

**Comment by NuiMrme** [comment]
Would you please elaborate ? here in your example I'm assuming you were using GC and your file path is correct. It actually found it but then couldn't recognize llava. I'm having the same issue so what typo in what path did you make ?

**Comment by mao-code** [comment]
Honestly, I forget the detail, though. However, I remember that it is actually not a problem for the repository itself. If everything looks OK, you can try to restart the session in GC and then install the required modules again.

**Comment by Song-WenPo** [comment]
> Would you please elaborate ? here in your example I'm assuming you were using GC and your file path is correct. It actually found it but then couldn't recognize llava. I'm having the same issue so what typo in what path did you make ?

pip install -e .    would help

**Comment by MassEast** [comment]
Either that, or add export PYTHONPATH=/src:$PYTHONPATH

**Comment by shahzain110** [comment]
Run these lines 

`%cd /content/LLaVA`
`import sys, os`
`sys.path.append(os.getcwd())`

then run this directly

`!python -m llava.train.train_mem \
    --lora_enable True \
    --lora_r 128 \
    --lora_alpha 256 \
    --model_name_or_path {MODEL_NAME} \
    --data_path {DATA_PATH} \
    --image_folder {IMAGE_FOLDER} \
    --vision_tower {VISION_TOWER} \
    --mm_projector_type mlp2x_gelu \
    --output_dir {OUTPUT_DIR} \
    --version v1 \
    --bf16 True \
    --num_train_epochs 5 \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --learning_rate 2e-4 \
    --lazy_preprocess True \
    --report_to wandb
`
