### ISSUE TITLE
[Usage] LlavaConfig object has no attribute 'attention_dropout'

### ISSUE THREAD

**Issue by yejipark-m** [haotian-liu/LLaVA#1075]
### Describe the issue

Issue:

First, thank you for your amazing work.

I have an issue with evaluating with my custom data.

I am trying to compare the answers of two cases.
1. Fine-tune llava-v1.5-7b with lora then evaluate the model with my custom data.

2. Do not fine-tune llava-v1.5-7b then evaluate the model zoo checkpoint with my custom data.

For the case 1, I passed args and evaluate successfully. But for the case 2, It fails with the log below.

Command:
```
python3 llava/eval/model_vqa.py \
--model-path
liuhaotian/llava-v1.5-7b-lora
--model-base
lmsys/vicuna-7b-v1.5
--question-file
/path/to/question
--image-folder
/LLaVA//data/eval/llava-bench-in-the-wild/images
--answers-file
/LLaVA/path/to/answer
--temperature
0
--conv-mode
vicuna_v1
```

Log: 
```
Traceback (most recent call last):
  File "/root/share/llava/llava/eval/model_vqa.py", line 100, in <module>
    eval_model(args)
  File "/root/share/llava/llava/eval/model_vqa.py", line 34, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, args.model_base, model_name)
  File "/LLaVA/llava/model/builder.py", line 56, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3462, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/LLaVA/llava/model/language_model/llava_llama.py", line 46, in __init__
    self.model = LlavaLlamaModel(config)
  File "/LLaVA/llava/model/language_model/llava_llama.py", line 38, in __init__
    super(LlavaLlamaModel, self).__init__(config)
  File "/LLaVA/llava/model/llava_arch.py", line 32, in __init__
    super(LlavaMetaModel, self).__init__(config)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 956, in __init__
    [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 956, in <listcomp>
    [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 756, in __init__
    self.self_attn = LLAMA_ATTENTION_CLASSES[config._attn_implementation](config=config, layer_idx=layer_idx)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 299, in __init__
    self.attention_dropout = config.attention_dropout
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 265, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'LlavaConfig' object has no attribute 'attention_dropout'
```

I look forward to hearing some reply.
Thanks.

**Comment by homiec** [comment]
i have the same question

**Comment by homiec** [comment]
in the pyproject.toml : "transformers==4.37.2" 
however, in the transformers/models/llama/modeling_llama.py line 299 
self.attention_dropout = config.attention_dropout
but the attention_dropout not in the config.json of llava-v1.5-7b

**Comment by homiec** [comment]
i can add   "attention_dropout": 0.5 in config.json  , it deals, but another problem occured：
AttributeError: 'LlavaConfig' object has no attribute 'rope_theta'

**Comment by homiec** [comment]
> with our llava config in main branch

sorry, can you tell the file path? i did not find it in the main branch

**Comment by Madhumitha-MCW** [comment]
@haotian-liu  Still the issue occurs with transformers 4.43.2. Is this bug fixed on the main?

**Comment by tavyscrolls** [comment]
same on newest, various attributes depending on model

**Comment by dingyue772** [comment]
> @haotian-liu Still the issue occurs with transformers 4.43.2. Is this bug fixed on the main?
just change the other loading code as the "Fix lora loading" commit code. That could work.

**Comment by ShobhaRajanna** [comment]
> > @haotian-liu Still the issue occurs with transformers 4.43.2. Is this bug fixed on the main?
> > just change the other loading code as the "Fix lora loading" commit code. That could work. 

Hey, can you able to resolve this "LlavaConfig' object has no attribute 'rope_theta"?

**Comment by riebeb** [comment]
same here

**Comment by cristoben** [comment]
The same problem when i try to eval the 1.5-7b,do you have any suggestions?

**Comment by yiwei-chenn** [comment]
I have the same problem when evaluating the llava-1.5-lora model in huggingface.

Currently, the llava1.5-lora still have some missing values on config.json file. 

Followed the instruction in #1169 , I solved the question by modifying the code of loading config file from
```python
        if 'lora' in model_name.lower() and model_base is not None:
            lora_cfg_pretrained = AutoConfig.from_pretrained(model_path)
            tokenizer = AutoTokenizer.from_pretrained(model_base, use_fast=False)
            print('Loading LLaVA from base model...')
            model = LlavaLlamaForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs
``` 
to 
```python
        if 'lora' in model_name.lower() and model_base is not None:           
            from llava.model.language_model.llava_llama import LlavaConfig
            lora_cfg_pretrained = LlavaConfig.from_pretrained(model_path)      
            tokenizer = AutoTokenizer.from_pretrained(model_base, use_fast=False)
            print('Loading LLaVA from base model...')
            model = LlavaLlamaForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs)
```

**Comment by cristoben** [comment]
thanks a lot for your methods,I will try it later୧꒰•̀ᴗ•́꒱୨



---Original---
From: "Chen ***@***.***&gt;
Date: Thu, Nov 14, 2024 12:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [haotian-liu/LLaVA] [Usage] LlavaConfig object has no attribute'attention_dropout' (Issue #1075)




 
I have the same problem when evaluating the llava-1.5-lora model in huggingface.
 
Currently, the llava1.5-lora still have some missing values on config.json file.
 
Followed the instruction in #1169 , I solved the question by modifying the code of loading config file from
         if 'lora' in model_name.lower() and model_base is not None:             lora_cfg_pretrained = AutoConfig.from_pretrained(model_path)             tokenizer = AutoTokenizer.from_pretrained(model_base, use_fast=False)             print('Loading LLaVA from base model...')             model = LlavaLlamaForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs
 
to
         if 'lora' in model_name.lower() and model_base is not None:                        from llava.model.language_model.llava_llama import LlavaConfig             lora_cfg_pretrained = LlavaConfig.from_pretrained(model_path)                   tokenizer = AutoTokenizer.from_pretrained(model_base, use_fast=False)             print('Loading LLaVA from base model...')             model = LlavaLlamaForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs)

**Comment by ciroimmobile** [comment]
This was a problem with older versions of the transformer, and I added these three lines to solve the problem
lora_cfg_pretrained.attention_dropout = 0.0  
lora_cfg_pretrained.rope_theta = 10000  
lora_cfg_pretrained.attention_bias = False 

> The same problem when i try to eval the 1.5-7b,do you have any suggestions?

**Comment by YANGTUOMAO** [comment]
> i can add "attention_dropout": 0.5 in config.json , it deals, but another problem occured： AttributeError: 'LlavaConfig' object has no attribute 'rope_theta'

bro ,i meet exactly same error, have you solved this problem?
