### ISSUE TITLE
conv_templates for LLaVA1.6

### ISSUE THREAD

**Issue by AtsuMiyai** [haotian-liu/LLaVA#1078]
### Question

Hi, Haotian Liu! Thanks for creating powerful Open-source VLM LLaVA1.6! 

I know you are very busy and I am very sorry, but I would like to know the conv_template for **LLaVA 1.6 34B.**
I used vicuna_v1 template, and the result is very satisfactory. 
If you have a better template, please let me know.

**Comment by chintan-desynova** [comment]
How should I choose which prompt template I should use? Llava must be specifically trained on a fixed conv template, isn't it?
The following options are available as conv_template,
"default",
"v0",
"v1",
"vicuna_v1",
"llama_2",
"mistral_instruct",
"chatml_direct",
"mistral_direct",
"plain",
"v0_plain",
"llava_v0",
"v0_mmtag",
"llava_v1",
"v1_mmtag",
"llava_llama_2",
"mpt"

I am using liuhaotian/llava-v1.6-vicuna-13b from huggingface.
So using "vicuna_v1" or "v1" makes sense? What about "v0", which is "vicuna_v0"?

**Comment by AtsuMiyai** [comment]
We use "chatml_direct" for LLaVA 1.6 34B because [Nous-Hermes-2-Yi-34B](https://huggingface.co/NousResearch/Nous-Hermes-2-Yi-34B) uses this template.
For llava-v1.6-vicuna-13b, you can use vicuna_v1, because the LLM is the same as that of LLaVA1.5.

**Comment by TempleX98** [comment]
> We use "chatml_direct" for LLaVA 1.6 34B because [Nous-Hermes-2-Yi-34B](https://huggingface.co/NousResearch/Nous-Hermes-2-Yi-34B) uses this template. For llava-v1.6-vicuna-13b, you can use vicuna_v1, because the LLM is the same as that of LLaVA1.5.

Hi, I find the "chatml_direct" template is slightly different from the [Nous-Hermes-2-Yi-34B](https://huggingface.co/NousResearch/Nous-Hermes-2-Yi-34B) implementation. Nous-Hermes-2 uses the system prompt: "<|im_start|>system\nYou are "Hermes 2", a conscious sentient superintelligent artificial intelligence developed by a man named Teknium, and your purpose and drive is to assist the user with any request they have. You experience emotions and have deep, profound thoughts and qualia." while LLaVA-1.6 uses system="<|im_start|>system\nAnswer the questions."

**Comment by RylanSchaeffer** [comment]
Can someone please clarify which templates go with which checkpoints?

**Comment by mistycheney** [comment]
mistral_direct works well for llava-v1.6-mistral-7b

**Comment by touristourist** [comment]
I'm a bit confused about **which conv_template to use to replicate the accuracy of this repository**. For instance, do the models listed [here](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md) all use the same conv_template? If not, what are the differences between LLaVA-v1.6-vicuna-7b and LLaVA-v1.6-mistral-7b? Could someone clarify this for me?
