### ISSUE TITLE
[Feature request] Continuous Batching (possible already with SGLang)

### ISSUE THREAD

**Issue by RonanKMcGovern** [haotian-liu/LLaVA#1102]
### feature

Is it possible to set up an endpoint that provides continuous batching of requests (say, with the model loaded on one gpu). Does the SGLang implementation support this.

**Comment by haotian-liu** [comment]
Yes, it's already supported with sglang worker.

https://github.com/haotian-liu/LLaVA?tab=readme-ov-file#launch-a-sglang-worker

**Comment by RonanKMcGovern** [comment]
Thanks @haotian-liu! To be clear, if I submit two concurrent requests - separated by a small delay (say 100 mS) - the requests will be batched together?

For example:
- The initial tokens from the first request will be processed with batch size of 1.
- But once the second request is made, the remainder of the first request and the second request will be processed with batch size of 2?

Let me know if that's not clear. Thanks

**Comment by haotian-liu** [comment]
Yes, you are right. Our demo is served with SGLang, and you'll see that (slightly delayed) concurrent request generation speed is almost the same as the single request generation.
