### ISSUE TITLE
[Question] Demo - Language-only Instructions

### ISSUE THREAD

**Issue by brucewlee** [haotian-liu/LLaVA#1105]
### Question

How is LLaVa generating responses without images? Is a blank image allowed by default?

If so, does this mean that LLaVa can essentially be used as a language-only use too?

**Comment by haotian-liu** [comment]
LLaVA performs text-only training and inference with text-only -- you do not need to add a blank image.

**Comment by shushankyadav** [comment]
@haotian-liu is there any specific format of data that needs to be followed for text-only training?? kindly suggest or share any such example code and data set available for the same.
