### ISSUE TITLE
[Question] What should be the base model for Lightning 7B (v1.1) delta?

### ISSUE THREAD

**Issue by Tongcheng** [haotian-liu/LLaVA#111]
### Question

I saw the README instruction seems to suggest use LLaMA-7B for the lightning 7B basis, though another issue (https://github.com/haotian-liu/LLaVA/issues/86) seems to suggest we should use Vicuna-7B as basis.

Could you clarify which one is the right basis model to use for Lightning 7B?

Thanks a lot!

**Comment by haotian-liu** [comment]
Please use the LLaMA-7B as the base.  We train based on Vicuna-7B, but release the delta from LLaMA, so that people do not need to convert the Vicuna first in order to use our checkpoint.  Thanks.

**Comment by Tongcheng** [comment]
I see! Thanks for the fast response @haotian-liu , and appreciate your great work!

**Comment by haotian-liu** [comment]
Thanks for your interest in our work :)
