### ISSUE TITLE
I followed the steps exactly, yet I got the following error message, what should I do??

### ISSUE THREAD

**Issue by cosmosanalytics** [haotian-liu/LLaVA#1130]
### Describe the issue

![image](https://github.com/haotian-liu/LLaVA/assets/100080151/5997a4db-65f3-4b28-ba09-700b94443216)

You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-c05d8f95fe9d> in <cell line: 24>()
     22 })()
     23 
---> 24 eval_model(args)

3 frames
/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py in _load_pretrained_model(cls, model, state_dict, loaded_keys, resolved_archive_file, pretrained_model_name_or_path, ignore_mismatched_sizes, sharded_metadata, _fast_init, low_cpu_mem_usage, device_map, offload_folder, offload_state_dict, dtype, is_quantized, keep_in_fp32_modules)
   3977             is_safetensors = archive_file.endswith(".safetensors")
   3978             if offload_folder is None and not is_safetensors:
-> 3979                 raise ValueError(
   3980                     "The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder`"
   3981                     " for them. Alternatively, make sure you have `safetensors` installed if the model you are using"

ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

**Comment by KansaiTraining** [comment]
this is not a solution...

**Comment by suyanli220** [comment]
can I ask how the problem be solved?
