### ISSUE TITLE
[Usage]  Unable to load the  LLaVA-CC3M-Pretrain-595K dataset

### ISSUE THREAD

**Issue by CloudedLeopard17** [haotian-liu/LLaVA#1139]
### Describe the issue

Issue: I am trying to load the CC3M dataset using the datasets library but it is giving me the error **UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte**. Is anybody able to load the data correctly?

**Comment by yummyKnight** [comment]
You should directly download it from HF without using datasets library
