### ISSUE TITLE
The demo web page is down. 

### ISSUE THREAD

**Issue by AlirezaSalehy** [haotian-liu/LLaVA#1151]
### Describe the issue

Hi, thanks in advance for the significant effort.  The demo web page at URL https://llava.hliu.cc/ is not working properly. 

Command:
```
I upload the image via the provided way and write an arbitrary prompt, then hit the send button.
```

Log: 

```
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.
```

Screenshots:
![image](https://github.com/haotian-liu/LLaVA/assets/49995349/bcace2e7-85dd-46c4-bdee-f2ae735af375)

I also mention that I've tried different connection access points So I'm pretty sure that there is no issue with the internet connection. Also tested in several intervals in time span of about 4 hours so it seems that high traffic isn't the case, too.

**Comment by CAholder** [comment]
I cant even load the gradio link anymore

**Comment by haotian-liu** [comment]
Thank you it's now been fixed and up again :)

**Comment by fbrand-new** [comment]
Hello, it seems that the demo still has some problems:
![image](https://github.com/haotian-liu/LLaVA/assets/17751421/5290f1b2-271e-44cc-a909-747e676037b9)
I tried uploading an image but it stops at "undefined" every time. Reproduced both in Firefox and Chrome.
I can still ask the question but it complains 
![image](https://github.com/haotian-liu/LLaVA/assets/17751421/7b21b981-0547-4a9b-8233-a30677dccad9)
