### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by fbrand-new** [haotian-liu/LLaVA#1168]
Hello, it seems that the demo still has some problems:
![image](https://github.com/haotian-liu/LLaVA/assets/17751421/5290f1b2-271e-44cc-a909-747e676037b9)
I tried uploading an image but it stops at "undefined" every time. Reproduced both in Firefox and Chrome.
I can still ask the question but it complains 
![image](https://github.com/haotian-liu/LLaVA/assets/17751421/7b21b981-0547-4a9b-8233-a30677dccad9)

_Originally posted by @fbrand-new in https://github.com/haotian-liu/LLaVA/issues/1151#issuecomment-1959546940_

**Comment by alarmgoose** [comment]
Yup. Would be nice if I could run this exact version in colab.

**Comment by haotian-liu** [comment]
The demo is fixed now. Thanks!
