### ISSUE TITLE
Image error

### ISSUE THREAD

**Issue by Rishbhu** [haotian-liu/LLaVA#1171]
### Describe the issue

Issue:
Whenever I ask it to analyze an image, the image doesnt get run through fully and it just says 'undefined'
Command:
```
PASTE THE COMMANDS HERE.
```

Log: 
```
PASTE THE LOGS HERE.
```

Screenshots:
You may attach screenshots if it better explains the issue.
![Screenshot 2024-02-23 232553](https://github.com/haotian-liu/LLaVA/assets/99981600/17162cbb-3748-4194-b848-d83c61a00330)

**Comment by haotian-liu** [comment]
It's been fixed now. Thanks.
