### ISSUE TITLE
[Usage] How to unfreeze the visual encoder when fine-tuning LLaVA?

### ISSUE THREAD

**Issue by zengxingchen** [haotian-liu/LLaVA#1173]
### Describe the issue

Issue:
How to unfreeze the visual encoder when fine-tuning LLaVA?

**Comment by yushuinanrong** [comment]
Have you resolved it?

**Comment by zengxingchen** [comment]
> Have you resolved it?

Just unfreeze the forward process, which is currently no_grad(). Also, set require_grad = True in some places.

**Comment by CR400AF-A** [comment]
> > Have you resolved it?
> 
> Just unfreeze the forward process, which is currently no_grad(). Also, set require_grad = True in some places.

Hi, I'm curious about performance trained with visual encoder unfreeze, but I don't have GPU resource now. Does it drop or rise?

**Comment by Road2Redemption** [comment]
Can you provide where to add requires_grad=True?

**Comment by Purshow** [comment]
Hi~ I have the same question.Have you sovled it?

**Comment by muzairkhattak** [comment]
@Purshow you can remove no_grad() from here: https://github.com/haotian-liu/LLaVA/blob/c121f0432da27facab705978f83c4ada465e46fd/llava/model/multimodal_encoder/clip_encoder.py#L45

Additionally, explicitly set the require grad to true for the vision parameters in trainer.py

Something like the below:
`for name, p in model.get_model().vision_tower.named_parameters():
    p.requires_grad = True`

**Comment by Purshow** [comment]
> @Purshow you can remove no_grad() from here:
> 
> https://github.com/haotian-liu/LLaVA/blob/c121f0432da27facab705978f83c4ada465e46fd/llava/model/multimodal_encoder/clip_encoder.py#L45
> 
> Additionally, explicitly set the require grad to true for the vision parameters in trainer.py
> 
> Something like the below: `for name, p in model.get_model().vision_tower.named_parameters(): p.requires_grad = True`
Thanks!

**Comment by ThisisBillhe** [comment]
I am curious how many parameters are added to the optimizer? Since we only set requires_grad to the model and do not explicitly control the optimizer.
