### ISSUE TITLE
How can I get llava-13b-v1 parameters

### ISSUE THREAD

**Issue by TheShy-Dream** [haotian-liu/LLaVA#118]
### Question

Hello author, I have found that llava-13b-v1 has stronger image annotation capabilities than llava13b-v0, so what should I do to obtain the weights of llava-13b-v1。
The first image is from [demo](https://llava.hliu.cc/) using llava-13b-v1
![image](https://user-images.githubusercontent.com/58178926/236722103-8c201ef2-5cc9-4886-98b5-549094619a69.png)
The second image is from my webui using llava-13b-v0
![image](https://user-images.githubusercontent.com/58178926/236722142-d04ce5c5-ae87-4733-8700-de5c37f96a5d.png)

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our work.  We'll release v1 weights this week, thanks!

**Comment by haotian-liu** [comment]
Hi, it's released [here](https://huggingface.co/liuhaotian/LLaVA-13b-delta-v1-1).

**Comment by TheShy-Dream** [comment]
Hi,many thanks!!!
