### ISSUE TITLE
How to load CLIP from local

### ISSUE THREAD

**Issue by XipengY** [haotian-liu/LLaVA#120]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:

Command:
```
PASTE THE COMMANDS HERE.
```
python llava/train/train_mem.py \
    --model_name_or_path ./checkpoints/llama-vicuna/7B-convert \
    --data_path data/cc3m_595k/chat.json \
    --image_folder data/cc3m_595k/images \
    --vision_tower ./checkpoints/clip-l \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end \
    --bf16 False \
    --output_dir ./checkpoints/llava-7b-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2400 \
    --save_total_limit 1 \
    --learning_rate 2e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --report_to wandb

Log: 
```
PASTE THE LOGS HERE.
```
You are using a model of type llama to instantiate a model of type llava. This is not supported for all configurations of models and can yield errors.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.87s/it]
Using pad_token, but it is not set yet.
> /root/LLaVA/llava/train/train.py(505)train()
-> if model_args.vision_tower is not None:
(Pdb) c
Traceback (most recent call last):
  File "/root/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/root/LLaVA/llava/train/train.py", line 506, in train
    model_vision_dict = model.model.initialize_vision_modules(
  File "/root/LLaVA/llava/model/llava.py", line 61, in initialize_vision_modules
    vision_tower = CLIPVisionModel.from_pretrained(vision_tower)
  File "/root/conda3.10/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2170, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/root/conda3.10/lib/python3.10/site-packages/transformers/models/clip/configuration_clip.py", line 233, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/conda3.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/conda3.10/lib/python3.10/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/conda3.10/lib/python3.10/site-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: ./checkpoints/clip-l does not appear to have a file named config.json. Checkout 'https://huggingface.co/./checkpoints/clip-l/None' for available files.

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by haotian-liu** [comment]
`OSError: ./checkpoints/clip-l does not appear to have a file named config.json. Checkout`

Hi, can you check if you have the configuration file set properly?

`./checkpoints/clip-l/config.json`

**Comment by XipengY** [comment]
Thanks reply!
Set vision_tower as  "./checkpoints/clip-l/config.json" not work.

Also set vision_tower as the directory of "./checkpoints/clip-l"
meanwhile, modify line 59 of llava.py as follows:
# image_processor = CLIPImageProcessor.from_pretrained(vision_tower)
image_processor = CLIPImageProcessor.from_pretrained(os.path.join(vision_tower, 'preprocessor_config.json'))

**Comment by haotian-liu** [comment]
Oh I mean, is `config.json` in this folder `./checkpoints/clip-l/`?  It seems to be saying that it cannot find this file.

**Comment by 459737087** [comment]
Hi! Did you solve the problem
