### ISSUE TITLE
Does LLaVA's package dependencies conflict with those of MedCLIP?When I replace the vision encoder of LLaVA with MedCLIP, the following error occurs

### ISSUE THREAD

**Issue by 20191864218** [haotian-liu/LLaVA#1203]
### Question

When I replace the vision encoder of LLaVA with MedCLIP, the following error occurs.

`RuntimeError: Error(s) in loading state_dict for MedCLIPModel:
        Unexpected key(s) in state_dict: "text_model.model.embeddings.position_ids". `

**Comment by ameer-khu** [comment]
@20191864218 Hi, can you let me know how you resolved this issue? What changes do we need to make to integrate MedCLIP?
