### ISSUE TITLE
Does LLaVA's package dependencies conflict with those of MedCLIP?

### ISSUE THREAD

**Issue by 20191864218** [haotian-liu/LLaVA#1204]
### Question

When I replace the vision encoder of LLaVA with MedCLIP, the following error occurs.

`RuntimeError: Error(s) in loading state_dict for MedCLIPModel:
        Unexpected key(s) in state_dict: "text_model.model.embeddings.position_ids". `

**Comment by SachJbp** [comment]
What was the resolution here?

I encountered the same issue:

```
from medclip import MedCLIPModel, MedCLIPVisionModelViT
# load MedCLIP-ViT
clip_model = MedCLIPModel(vision_cls=MedCLIPVisionModelViT)
clip_model.from_pretrained()
RuntimeError: Error(s) in loading state_dict for MedCLIPModel:
	Unexpected key(s) in state_dict: "text_model.model.embeddings.position_ids". 
```
