### ISSUE TITLE
[Question] Is a LLaVA 1.6 the same as LLaVA-NeXT?

### ISSUE THREAD

**Issue by AL3708** [haotian-liu/LLaVA#1210]
### Question

https://llava-vl.github.io/blog/2024-01-30-llava-next/ compares LLaVA-NeXT to previous version 1.5. Also googling LLaVA 1.6 redirects to LLaVA-NeXT. So is there naming inconsistency and they are same models?

**Comment by NielsRogge** [comment]
Yes
