### ISSUE TITLE
[Question] Why does CLI inference give different result than the gradio served UI result?

### ISSUE THREAD

**Issue by copperwiring** [haotian-liu/LLaVA#122]
### Question

I am using an image which looks like this: https://archive.md/JPiRZ . When I upload the image on the webpage, I see this

![image](https://user-images.githubusercontent.com/23316280/236790731-72435242-8b84-4f23-9e62-63b2a7f969e2.png)
 
but when I use inference on CLI as mentioned here, by using command:

`python -m llava.eval.run_llava --model-name LLaVA-7B-v0 --image-file sample.jpg --query "Describe the scene in the image" `, I get few words description 

`© 2018 The New York Times Company`. Running this inference CLI multiple times gives different results but very similar (and wrong) e.g. `© 2015 Bloomberg Finance LP` and , snapshot below

![image](https://user-images.githubusercontent.com/23316280/236791946-4ceee5a5-54a7-490a-b8ed-dcddf53b085d.png)

![image](https://user-images.githubusercontent.com/23316280/236792587-41fb53f1-4b25-422b-ad13-301fd37d2210.png)

I know I am using 7B-v0 for CLI and 7B-lightning for UI example (because it didnt have 7B-v0), I would either ways expect more detailed response than just few words.

**Comment by penghe2021** [comment]
Also pay attention to the sample parameters, the web demo uses Max output tokens: 512, which is different in CLI example

**Comment by copperwiring** [comment]
Ah! good catch
