### ISSUE TITLE
[Usage] ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model'

### ISSUE THREAD

**Issue by Pompey21** [haotian-liu/LLaVA#1291]
### Describe the issue

Issue:
Hi, I've been trying to setup the project on my local machine and after downloading/installing all necessary pip libraries I tried running the exemplary test script (see below) but am running into problems.
I created a new python file in the home directory of the project - where llava folder is also present.

Also please note that I made a fork and names it deep-llava. Nothing has been changed yet.

Command:
```
from llava.model.builder import load_pretrained_model
from llava.mm_utils import get_model_name_from_path
from llava.eval.run_llava import eval_model

model_path = "liuhaotian/llava-v1.5-7b"

tokenizer, model, image_processor, context_len = load_pretrained_model(
    model_path=model_path,
    model_base=None,
    model_name=get_model_name_from_path(model_path)
)
```

Log: 
```
Traceback (most recent call last):
  File "/path-on-my-machine/deep-llava/test.py", line 1, in <module>
    from llava.model.builder import load_pretrained_model
  File "/path-on-my-machine/deep-llava/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (/path-on-my-machine/deep-llava/llava/model/__init__.py)
```

**Comment by zhaohm14** [comment]
As discussed in [issue #1101](https://github.com/haotian-liu/LLaVA/issues/1101), I've tried the following package versions and they seem to work fine in my environment:

- `transformers==4.37.2`
- `accelerate==0.28.0`
- `torch==2.1.2`

**Comment by wentaoyuan** [comment]
> As discussed in [issue #1101](https://github.com/haotian-liu/LLaVA/issues/1101), I've tried the following package versions and they seem to work fine in my environment:
> 
> * `transformers==4.37.2`
> * `accelerate==0.28.0`
> * `torch==2.1.2`

I have exactly the same versions but still running into `ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model'`

**Comment by zhaohm14** [comment]
@wentaoyuan Maybe you can comment out the `try...except...` block in `llava/model/__init__.py`

```python
# try:
from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
from .language_model.llava_mpt import LlavaMptForCausalLM, LlavaMptConfig
from .language_model.llava_mistral import LlavaMistralForCausalLM, LlavaMistralConfig
# except:
#     pass
```
to find out more detailed error information.
https://github.com/haotian-liu/LLaVA/issues/1101#issuecomment-1933385973

**Comment by CrispyFeSo4** [comment]
Sad that I‘ve tried all the advice above but it doesn't work.
However, I replaced `from .model import LlavaLlamaForCausalLM` with `from .model.language_model.llava_llama import LlavaLlamaForCausalLM`, and it worked.

Maybe you can try it first.
