### ISSUE TITLE
如何批量化推理 How to implement batch reasoning in LLava? [Question] 

### ISSUE THREAD

**Issue by fisher75** [haotian-liu/LLaVA#1298]
### Question

I recently used LLava to do batch inference, using thousands of images in my data set, and then recording the results. Is this functionality already available in llava? If not, what part of the code should I modify in llava? I feel like where should I write a for loop?

**Comment by bjzhb666** [comment]
Same question, how to solve it?

**Comment by fisher75** [comment]
> Same question, how to solve it?

To my knowledge should use SGLang, but don't know about details...

**Comment by fisher75** [comment]
> Same question, how to solve it?

btw bro, could leave a WeChat? can discuss

**Comment by bjzhb666** [comment]
ok, wxid_b4d5n9oqkr2f22

**Comment by fisher75** [comment]
Can't find it. Just use mine, FisherZz75

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Hongbo Zhao ***@***.***>
发送时间: Wednesday, March 20, 2024 5:46:45 PM
收件人: haotian-liu/LLaVA ***@***.***>
抄送: Haozhuang Chi ***@***.***>; Author ***@***.***>
主题: Re: [haotian-liu/LLaVA] 如何批量化推理 How to implement batch reasoning in LLava? [Question] (Issue #1298)


ok, wxid_b4d5n9oqkr2f22

―

**Comment by merrymercy** [comment]
https://github.com/sgl-project/sglang/tree/main/benchmark/llava_bench

**Comment by fisher75** [comment]
> https://github.com/sgl-project/sglang/tree/main/benchmark/llava_bench

我想做一个多轮对话的批量推理，请问格式应该是什么样子的呢？我做这个的目的是为了实现某种CoT的思想，请问可行吗？

**Comment by merrymercy** [comment]
可行。按照这个格式写多轮对话的SGLang function https://github.com/sgl-project/sglang/blob/2af565b3bb22cb8ba06acc17a2bbfa8d0ade0145/examples/quick_start/srt_example_chat.py#L10-L13

**Comment by fisher75** [comment]
> 可行。按照这个格式写多轮对话的SGLang function https://github.com/sgl-project/sglang/blob/2af565b3bb22cb8ba06acc17a2bbfa8d0ade0145/examples/quick_start/srt_example_chat.py#L10-L13

感谢回复啊老哥，但是我看了之后觉得可能你误解了，你贴的代码我看是给LLM的多轮对话推理用的，而我想做的是用VLM的能力也就是用LLava，具体来说就是我想知道假如可以用多轮对话的话，在https://github.com/sgl-project/sglang/tree/main/benchmark/llava_bench中提供的questions的jsonl应该以什么形式怎么改？
例如怎么把这个改成多轮对话：
`{"image": "001.jpg", "text": "What is the name of this famous sight in the photo?", "category": "conv", "question_id": 0}`

**Comment by zeyuwang-zju** [comment]
你好，如果我想对一批图片进行推理，但是每个图片只需要一个问题，问题都是一样的，这样的话还可以吗

**Comment by fisher75** [comment]
> 你好，如果我想对一批图片进行推理，但是每个图片只需要一个问题，问题都是一样的，这样的话还可以吗

肯定可以，这个听起来是最简单的

**Comment by zeyuwang-zju** [comment]
好的，已经解决了，谢谢！

2024-04-26 13:35:09 "Haozhuang Chi" ***@***.***> 写道：

你好，如果我想对一批图片进行推理，但是每个图片只需要一个问题，问题都是一样的，这样的话还可以吗

肯定可以，这个听起来是最简单的

**Comment by gehong-coder** [comment]
> 好的，已经解决了，谢谢！ 2024-04-26 13:35:09 "Haozhuang Chi" ***@***.***> 写道： 你好，如果我想对一批图片进行推理，但是每个图片只需要一个问题，问题都是一样的，这样的话还可以吗 肯定可以，这个听起来是最简单的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

这个实现已经有了吗，我的需求和你一样，请求支援，感谢

**Comment by hadolop** [comment]
> 你好，如果我想对一批图片进行推理，但是每个图片只需要一个问题，问题都是一样的，这样的话还可以吗

同样的问题，请教如何实现？

**Comment by fengluo233** [comment]
> > 你好，如果我想对一批图片进行推理，但是每个图片只需要一个问题，问题都是一样的，这样的话还可以吗
> 
> 同样的问题，请教如何实现？

Hello, I got the same question! Have you already solved it?
