### ISSUE TITLE
[Usage] LLAVA 1.6 inference doesn't work when the best resolution is not a multiple of 224

### ISSUE THREAD

**Issue by siddharthshah52** [haotian-liu/LLaVA#1300]
Issue:
I ran the run_llava script with an image of dimensions 640 x 1316. The best resolution selected by the [select_best_resolution](https://github.com/haotian-liu/LLaVA/blob/7440ec9ee37b0374c6b5548818e89878e38f3353/llava/mm_utils.py#L12) function is (336, 1008). The supported resolutions for LLAVA 1.6 can be found in it's [config.json](https://huggingface.co/liuhaotian/llava-v1.6-34b/blob/main/config.json#L16-L37) file. However, this results in tensor mismatch errors. This is due to mismatch in [divide_to_patches](https://github.com/haotian-liu/LLaVA/blob/7440ec9ee37b0374c6b5548818e89878e38f3353/llava/mm_utils.py#L77) and [get_anyres_image_grid_shape](https://github.com/haotian-liu/LLaVA/blob/7440ec9ee37b0374c6b5548818e89878e38f3353/llava/mm_utils.py#L99) functions. Since, 336 and 1008 are not perfectly divisible by CLIPImageProcessor's 224 patch size, the divide_to_patches produces a patch at the edge with padding done by PIL Image crop function. However, the get_anyres_image_grid_shape function takes the floor value on number of patches in width and height thus giving tensor mismatch error during inference. I tried two things (separately):

1. Take ceil instead of floor in get_anyres_image_grid_shape function. However, this returned empty text.
2. Don't take the patch at the edge in divide_to_patches. However, this returned gibberish text.

Running inference on square images (or when best resolution is square) works fine.

Command:
```
python3 run_llava -- --model-path models/llava-v1.6-34b --image-file test.jpg --query "Describe this image and its style in a very detailed manner." --load-4bit
```

Log: 
```
RuntimeError: The expanded size of the tensor (17920) must match the existing size (7168) at non-singleton dimension 0.  Target sizes: [17920, 32, 1].  Tensor sizes: [7168, 1, 1]
```

**Comment by siddharthshah52** [comment]
Both of my solutions seem to work

**Comment by siddharthshah52** [comment]
Both of my solutions work. Just that the observed empty text or gibberish text seems to happen when using batch size > 1. This happens irrespective of the resolutions of the images. Will open a separate issue for this.

**Comment by boyugou** [comment]
isn't LLaVa 1.6 using 336 to patchify? https://huggingface.co/liuhaotian/llava-v1.6-34b/blob/main/config.json#L16-L37:~:text=1008%2C,336

LLaVA-1.5-HD used 224
