### ISSUE TITLE
[Usage] Is there a python script to run infer ?

### ISSUE THREAD

**Issue by hollyaoyaozi** [haotian-liu/LLaVA#1317]
### Describe the issue

Hi deer author，

I have 2 questions:
1) I found that there is a **predict.py** in the root dir and **run_llava.py** in LLaVA/llava/eval dir. I wonder which can be used to run infer ?
2) Refering to the guide of installation on windows, when i ran 'pip install -e .'，pytorch 2.1.2 cpu version will be installed, which is conflicted with the step of installation of pytorch 2.0.1 gpu version (pip install torch==2.0.1+cu117 torchvision==0.15.2+cu117 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu117). So which version is required exactly ？

Thanks !

**Comment by prokaryote-hgy** [comment]
@hollyaoyaozi Hi, which script did you use for inference?

**Comment by anas-zafar** [comment]
Hi @hollyaoyaozi @prokaryote-hgy did you figure out which script to use? Thanks
