### ISSUE TITLE
[Usage] about Chinese data finetuning

### ISSUE THREAD

**Issue by PoseidomWong** [haotian-liu/LLaVA#134]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:
When I fine-tuned the whole network with Chinese data, which is step 3 of the training script you wrote, I got the following error. However, when I use your data to finetune, it doesn't appear. What do you think might be the cause of this error? Looking forward to your reply，thank you.
Command:
```
torchrun --nnodes=1 --nproc_per_node=8 --master_port=25001 \
    llava/train/train_mem.py \
    --model_name_or_path ./checkpoints/llama-vicuna-7b \
    --version $WEIGHT_VERSION \
    --data_path ./data/total_instruct.json \
    --image_folder /home/wf/LLaVA_Data/COCO/train2014 \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter ./checkpoints/mm_projector/llava-lightning-7b-pretrain.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 True \
    --output_dir ./checkpoints \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 5000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

Log: 
```
Traceback (most recent call last):
  File "/home/wf/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/home/wf/LLaVA/llava/train/train.py", line 665, in train
    trainer.train()
  File "/home/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1644, in train
    return inner_training_loop(
  File "/home/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1913, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2659, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2691, in compute_loss
    outputs = model(**inputs)
  File "/home/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/miniconda3/envs/llava/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wf/LLaVA/llava/model/llava.py", line 225, in forward
    outputs = self.model(
  File "/home/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wf/LLaVA/llava/model/llava.py", line 149, in forward
    cur_image_features = image_features[cur_image_idx]
IndexError: index 16 is out of bounds for dimension 0 with size 16

```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by loveyao72** [comment]
I meet the same error. Did you found the solution?

**Comment by PoseidomWong** [comment]
I delete the data，it works

**Comment by Byshev333** [comment]
the reason is data preprocess is wrong。In my case,  query contain more than one “<image>\n”  of "\n<image>" token

**Comment by findalexli** [comment]
Did you guys delete the questions  with more than '\n' and it worked? I tried but is still getting the same error @Byshev333 @PoseidomWong can you eleorabote? Thank yo!

**Comment by CrazyBrick** [comment]
@PoseidomWong hi, I met the same error, I don't quite understand what you mean by deleting data,  are you referring to deleting all Chinese datasets？

@Byshev333 hi, but I only have one '\n' token, what should I do?

@findalexli hi,have you solved this problem?

**Comment by PoseidomWong** [comment]
> @PoseidomWong hi, I met the same error, I don't quite understand what you mean by deleting data, are you referring to deleting all Chinese datasets？
> 
> @Byshev333 hi, but I only have one '\n' token, what should I do?
> 
> @findalexli hi,have you solved this problem?
It's been too long since I solved it, I remember it seemed like it was caused by some abnormal data at the time, and after deleting it, it was resolved

**Comment by CrazyBrick** [comment]
> @CrazyBrick It's been too long since I solved it, I remember it seemed like it was caused by some abnormal data at the time, and after deleting it, it was resolved

what is abnormal?I don't understand, can you provide some examples?
```
"conversations": [
      {
        "from": "human",
        "value": "<image>\n这幅画面是什么样的氛围"
      },
      {
        "from": "gpt",
        "value": "这幅画面是室内拍摄，女人侧身看向前方，房间内部展现，可见钢琴等家具，光线较暗，人像带有暗部，整体氛围显得安静思索。 "
      },
    ]
```
is this abnormal?

**Comment by PoseidomWong** [comment]
> > @CrazyBrick It's been too long since I solved it, I remember it seemed like it was caused by some abnormal data at the time, and after deleting it, it was resolved
> 
> what is abnormal?I don't understand, can you provide some examples?
> 
> ```
> "conversations": [
>       {
>         "from": "human",
>         "value": "<image>\n这幅画面是什么样的氛围"
>       },
>       {
>         "from": "gpt",
>         "value": "这幅画面是室内拍摄，女人侧身看向前方，房间内部展现，可见钢琴等家具，光线较暗，人像带有暗部，整体氛围显得安静思索。 "
>       },
>     ]
> ```
> 
> is this abnormal?

我无法举例说明，但你可以打印导致这一问题的数据，并对其进行分析或删除。

**Comment by CrazyBrick** [comment]
OK，I see，thank you for your reply~



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 27, 2023 14:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [haotian-liu/LLaVA] [Usage] about Chinese data finetuning (Issue#134)




   
@CrazyBrick It's been too long since I solved it, I remember it seemed like it was caused by some abnormal data at the time, and after deleting it, it was resolved
  
what is abnormal?I don't understand, can you provide some examples?
 "conversations": [       {         "from": "human",         "value": "<image&gt;\n这幅画面是什么样的氛围"       },       {         "from": "gpt",         "value": "这幅画面是室内拍摄，女人侧身看向前方，房间内部展现，可见钢琴等家具，光线较暗，人像带有暗部，整体氛围显得安静思索。 "       },     ]  
is this abnormal?
  
我无法举例说明，但你可以打印导致这一问题的数据，并对其进行分析或删除。
