### ISSUE TITLE
[Question] Some weights of LlavaTaiyiForCausalLM were not initialized from the model checkpoint，When I use MLP after pretrain for inference, I get an error

### ISSUE THREAD

**Issue by 20191864218** [haotian-liu/LLaVA#1354]
### Question

`Some weights of LlavaTaiyiForCausalLM were not initialized from the model checkpoint at /root/autodl-tmp/Taiyi and are newly initialized: ['transformer.mm_projector.0.bias', 'transformer.mm_projector.0.weight', 'transformer.mm_projector.2.bias', 'transformer.mm_projector.2.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/LLaVA/llava/serve/cli.py", line 137, in <module>
    main(args)
  File "/root/LLaVA/llava/serve/cli.py", line 34, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/root/LLaVA/llava/model/builder.py", line 124, in load_pretrained_model
    model.load_state_dict(mm_projector_weights, strict=False)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LlavaTaiyiForCausalLM:
        size mismatch for transformer.mm_projector.0.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([1048576, 1]).
        size mismatch for transformer.mm_projector.2.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([8388608, 1]).`
        
I would be grateful if someone could help me

**Comment by haozhang1234** [comment]
I also have this problem. How did you solve it？If I could receive your help, I would be extremely grateful！
