### ISSUE TITLE
[Question] how to use finetune weight to inference ?

### ISSUE THREAD

**Issue by huilin66** [haotian-liu/LLaVA#1377]
### Question

To finetune llava-v1.5-7b, I followed scripts/v1_5/finetune_lora.sh and used the following instruction:

`#!#!/bin/bash

deepspeed llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path ./ckpt/vicuna-7b-v1.5 \
    --version v1 \
    --data_path /nfsv4/23039356r/data/defect_caption/llava_v1_5_vqa320.json \
    --image_folder /nfsv4/23039356r/data/defect_caption \
    --vision_tower ./ckpt/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter ./ckpt/llava-v1.5-7b/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-7b-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

`

It seems that the training results of llava-v1.5-7b should contain "pytorch_model-00001-of-00002.bin" and "pytorch_model-00001-of-00002.bin", which are about 13.5G.

But my finetune results only contain "non_lora_trainables.bin", 42MB.

Can anyone help me with this problem? Thanks very much!

![c899c83d7d7d57d6d70489fc5989edc](https://github.com/haotian-liu/LLaVA/assets/143692339/5c1e0b22-663e-4fcc-a609-18b9841f5fe5)

**Comment by huilin66** [comment]
I use merge_lora_weights.py to merge the results, thanks.

**Comment by wuwu-C** [comment]
Hey! I have met some errors when I run merge_lora_weights.py.
`OSError: /data/user4/cww/LLaVA/checkpoint/LLaVA.finetune/geochat-LLAVA15-7B-Vicuna-finetune_lora/checkpoint-2234 does not appear to have a file named config.json. Checkout 'https://huggingface.co//data/user4/cww/LLaVA/checkpoint/LLaVA.finetune/geochat-LLAVA15-7B-Vicuna-finetune_lora/checkpoint-2234/main' for available files.`
My lora finetuned checkpoint do not have config.json, but I saw you have this file.can you help me?
![image](https://github.com/haotian-liu/LLaVA/assets/96038200/5eb59d9e-ce29-4939-bcb1-2b8516d3e927)

**Comment by ShawnAn-WHU** [comment]
@wuwu-C Have you solved this problem? I used the finetune_lora.sh and get the same files as yours.

**Comment by keanshi-nlp** [comment]
Hi, the merge_lora script seems not load mm_projector's weight. It warns me that the mm_projector's weights is newly initialized when I tried to merge lora's weight to pretrained llava. Can you describe the detail of how to merge them? Thanks!

**Comment by BeautiLu** [comment]
> Hi, the merge_lora script seems not load mm_projector's weight. It warns me that the mm_projector's weights is newly initialized when I tried to merge lora's weight to pretrained llava. Can you describe the detail of how to merge them? Thanks!

Met the same issue here, may I ask if you have solved it?

**Comment by keanshi-nlp** [comment]
> > Hi, the merge_lora script seems not load mm_projector's weight. It warns me that the mm_projector's weights is newly initialized when I tried to merge lora's weight to pretrained llava. Can you describe the detail of how to merge them? Thanks!
> 
> Met the same issue here, may I ask if you have solved it?

Using `peft==0.14.0` and `transformers==4.37.2` is work on my server.
