### ISSUE TITLE
[Question] How to use pretrained projector in finetuning?

### ISSUE THREAD

**Issue by Hesh0629** [haotian-liu/LLaVA#1404]
### Question

Hello,

I'm trying to finetune llava-v1.57b with my pretrained projector.
However, when i use --pretrain_mm_mlp_adapter option in finetune_task_lora.sh, i met error message below.

![Screenshot 2024-04-15 at 10 57 31 PM](https://github.com/haotian-liu/LLaVA/assets/57738176/ecdac0b7-1b5d-4f59-ac43-db4d998f2449)

how can i use my projector in finetuning...?

**Comment by Hesh0629** [comment]
I just solved issue by switching projector file in model directory.
Before that, i downloaded model from hugging face hub.

**Comment by Hesh0629** [comment]
I just solved issue by switching projector file in model directory.
Before that, i downloaded model from hugging face hub.

**Comment by fangxin2github** [comment]
I met same problem. Can you explain it in detail？ thank u.

**Comment by hvgupta** [comment]
> I just solved this by switching projector file in model directory. Before that, I downloaded model from hugging face hub.

can you elaborate?
