### ISSUE TITLE
Multi-turn question (The second turn is only text question.)

### ISSUE THREAD

**Issue by AtsuMiyai** [haotian-liu/LLaVA#1412]
### Question

<img width="806" alt="スクリーンショット 2024-04-17 11 02 49" src="https://github.com/haotian-liu/LLaVA/assets/65175432/68a96c80-7149-4250-b505-c40607385789">

Thanks for your work! 

This is a quick question.
I'll try multi-turn questions. Especially, the second turn is only a text question.
Could someone tell me how to implement this?

Thanks for your cooperation!

**Comment by not-hermione** [comment]
> ### Question
> <img alt="スクリーンショット 2024-04-17 11 02 49" width="806" src="https://private-user-images.githubusercontent.com/65175432/323046252-68a96c80-7149-4250-b505-c40607385789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NzY3MTEsIm5iZiI6MTcxMzQ3NjQxMSwicGF0aCI6Ii82NTE3NTQzMi8zMjMwNDYyNTItNjhhOTZjODAtNzE0OS00MjUwLWI1MDUtYzQwNjA3Mzg1Nzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDIxNDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNzFiNGZjZDVmYmIxYzk4YjBiMTcxYzY3Y2FhMzYyMTkyYWQ4OWNmYzk1YmYwYzNhMzYwMGU1ZWZiNDkxNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lOaOQakPBNVdtZhE89ZnPlkVdQv_hms1pHukwqJv4yY">
> Thanks for your work!
> 
> This is a quick question. I'll try multi-turn questions. Especially, the second turn is only a text question. Could someone tell me how to implement this?
> 
> Thanks for your cooperation!

could you please tell me how to do this in python? the second turn is only a text question with reference to the earlier image.

**Comment by not-hermione** [comment]
Any update on this, please?

**Comment by AtsuMiyai** [comment]
@not-hermione Sorry for the late reply.
I think that the simplest way is to put your previous conversations into text input.

text_input = {USER: <image>\nWhat color is the car?\nAssistant: The car in this image is yellow. \nUSER:What color is the person's clothes?\nAssistant: }

**Comment by not-hermione** [comment]
thanks a lot for your reply. for the second turn, do we have to input the image again for context?

**Comment by AtsuMiyai** [comment]
I think so.

**Comment by not-hermione** [comment]
> I think so.

thanks.. I also found this: https://huggingface.co/docs/transformers/en/model_doc/llava#transformers.LlavaForConditionalGeneration:~:text=For%20multiple%20turns%20conversation%3A
