### ISSUE TITLE
[Question] Tokenizer.pad_token_id is NoneType, which requires float 

### ISSUE THREAD

**Issue by tian969** [haotian-liu/LLaVA#1431]
### Question

Hello, I want to change the LLaVA base model from llama2 to llama3, but I encountered error during executing these lines:

input_ids = torch.nn.utils.rnn.pad_sequence(
input_ids,
batch_first=True,
padding_value=self.tokenizer.pad_token_id)

the llama3 tokenizer's pad_token_id is None, which can not be a valid input in this method. How can I resolve this problem?
The model and tokenizer is correctly loaded.
<img width="932" alt="model-arch" src="https://github.com/haotian-liu/LLaVA/assets/102512042/30568d47-e07f-4cf7-8e1e-e6892a2cd358">
<img width="1425" alt="tokenizer-arch" src="https://github.com/haotian-liu/LLaVA/assets/102512042/51a2f469-b341-4f17-b177-7974cd0c6209">
<img width="1143" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/102512042/17c54570-f2c3-47e0-a1bf-866e37fa2816">

**Comment by chanangad** [comment]
Try setting pad_token_id to eos_token_id

**Comment by tian969** [comment]
Thanks to your help. It works!

**Comment by mmaaz60** [comment]
Hi @tian969 , @chanangad,

A better work-around for `pad` token in `LLaMA-3` would be to add a special token to tokenizer and then save it along with the model configs. For example, you may use the following code to achieve this,

```
def smart_tokenizer_and_embedding_resize(
    special_tokens_dict: Dict,
    tokenizer: transformers.PreTrainedTokenizer,
    model: transformers.PreTrainedModel,
):
    """Resize tokenizer and embedding.

    Note: This is the unoptimized version that may make your embedding size not be divisible by 64.
    """
    num_new_tokens = tokenizer.add_special_tokens(special_tokens_dict)
    model.resize_token_embeddings(len(tokenizer))

    if num_new_tokens > 0:
        input_embeddings = model.get_input_embeddings().weight.data
        output_embeddings = model.get_output_embeddings().weight.data

        input_embeddings_avg = input_embeddings[:-num_new_tokens].mean(
            dim=0, keepdim=True)
        output_embeddings_avg = output_embeddings[:-num_new_tokens].mean(
            dim=0, keepdim=True)

        input_embeddings[-num_new_tokens:] = input_embeddings_avg
        output_embeddings[-num_new_tokens:] = output_embeddings_avg
```
```
if tokenizer.pad_token is None:
    print(f"Adding pad token as '<pad>'")
    smart_tokenizer_and_embedding_resize(
        special_tokens_dict=dict(pad_token="<pad>"),
        tokenizer=tokenizer,
        model=model,
    )
```
And finally,

```
model.config.pad_token_id = tokenizer.pad_token_id
```

Here you add `<pad>` token, resize the embeddings and finally save this information in your model config.

---

Following above, we train LLaMA-3 based LLaVA-v1.5 model and achieve very good results. All the codes (fully supported with official LLaVA framework), pretrained chekcpoints and evaluation results are available on our GitHub Repo at [LLaVA++](https://github.com/mbzuai-oryx/LLaVA-pp).

The pretrained models are available at [Hugging Face](https://huggingface.co/collections/MBZUAI/llava-662b38b972e3e3e4d8f821bb).

Note that in addition to LLaMA-3, we also support `Phi-3-Mini-3.8B` model which is as good as `LLaVA-v1.5-13B` model on vision-language benchmarks.

I hope it will be helpful. Thanks and do let me know if you have any questions.
