### ISSUE TITLE
have problem when resume model

### ISSUE THREAD

**Issue by zht8506** [haotian-liu/LLaVA#1453]
Hi, thank you excellent work. i want to run llava-v1-80k with lora. The model can be trained normally.
however, when i resume the checkpoints from work_dir (work_dir/checkpoint-xx), i meeting some error.
I found that my ssh to cluster was killed. 
![image](https://github.com/haotian-liu/LLaVA/assets/81303574/42713ea0-2905-473d-8f8a-d671d1a1ec20)
Also, i found that Memory usage exceeds upper limit
![image](https://github.com/haotian-liu/LLaVA/assets/81303574/62168702-0a47-42a6-b9eb-c01161f5e883)
So, how to solve this problem, how to correctly resume model.
thank you very much.

**Comment by xing0047** [comment]
Hi, may I ask if there is any update over the checkpoint resuming issue?

**Comment by zht8506** [comment]
> Hi, may I ask if there is any update over the checkpoint resuming issue?

i find that it is the cup memory exceed the limitation. I solve this problem by only using 6 gpu (CUDA_VISIBLE_DEVICE=0,1,2,3,4,5) in a 8gpu machine.
