### ISSUE TITLE
[Question] Did LLAVA finetune all LLAMA weights or a part of LLAMA weights?

### ISSUE THREAD

**Issue by JulioZhao97** [haotian-liu/LLaVA#147]
### Question

Did LLAVA finetune all LLAMA weights or just a part of LLAMA weights ? Just wonder. I run the stage2 finetune on SQA and looked the ```param.requires_grad```, it seems that all params in LLAMA is open in finetuning.
![image](https://github.com/haotian-liu/LLaVA/assets/40555727/ead0e8ff-7493-4d95-9597-579b9d8f7367)

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our work. For stage-2 finetuning, it finetunes the full model.

**Comment by JulioZhao97** [comment]
> Hi, thank you for your interest in our work. For stage-2 finetuning, it finetunes the full model.

Thank you for the explaining !
