### ISSUE TITLE
[Question] Instruction tuning data

### ISSUE THREAD

**Issue by YuanLiuuuuuu** [haotian-liu/LLaVA#156]
### Question

What are ``llava_instruct_80k.json`` and ``llava_instruct_150k.json`` used for? It seems they are not mentioned in the paper.

**Comment by timovr-dev** [comment]
Seems like they (at least 80k version) were used for visual instruction tuning according to [this](https://github.com/haotian-liu/LLaVA/blob/4682aa6f0a999603f9d21c033328c01bcc0a9f54/scripts/train_lightning_mpt.sh) bash script.

**Comment by YuanLiuuuuuu** [comment]
What is the difference between the two files above and those of [conversation_58k.json](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/raw/main/conversation_58k.json), [detail_23k.json](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/raw/main/detail_23k.json) and [complex_reasoning_77k.json](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/raw/main/complex_reasoning_77k.json)

**Comment by haotian-liu** [comment]
Hi @YuanLiuuuuuu and @timovr-dev
Thank you for your interest in our work. ``llava_instruct_150k.json`` is the merged version of [conversation_58k.json](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/raw/main/conversation_58k.json), [detail_23k.json](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/raw/main/detail_23k.json) and [complex_reasoning_77k.json](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/raw/main/complex_reasoning_77k.json), as described in the paper as
> We collect 158K unique language-image instruction-following samples in total, including 58K in conversations, 23K in detailed description, and 77k in complex reasoning, respectively.

``llava_instruct_80k.json`` is a filtered subset of ``llava_instruct_150k.json`` after the release of the paper, for training the LLaVA Lightning model. This 80k subset contains 40k conversation and 40k reasoning data, with no image overlap.  We'll update the README to include these clarifications soon.

Please let me know if there are other concerns/doubts, thanks.

**Comment by YuanLiuuuuuu** [comment]
Thank you for your timely reply.
