### ISSUE TITLE
Facing error while using FSDP for training

### ISSUE THREAD

**Issue by mmaaz60** [haotian-liu/LLaVA#159]
Hi @haotian-liu 

I am getting the following errors while using FSDP training with 7B Lightening model.
```
import flash_attn_cuda                                                                                                                                                                                 
ImportError: /share/softwares/anaconda/anaconda3/envs/llava_beta/lib/python3.10/site-packages/flash_attn_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c106SymIntltEl
```

```
**Torch:** 2.1.0.dev20230515+cu118
**CUDA:** Build cuda_11.8.r11.8/compiler.31833905_0
**Flash-attn:** 1.0.5
```

I have downloaded/installed the LLaVA repo after May 1st.
![image](https://github.com/haotian-liu/LLaVA/assets/55104795/a5be293d-365b-4c7f-921e-21094af560f6)

**Comment by haotian-liu** [comment]
Hi, thanks for your interest in our work.

There seems to be some update in the CUDA drivers in the latest PyTorch nightly, you may need to make sure the CUDA version matchse with the PyTorch CUDA version.  Do you want to do FSDP pretraining, or FSDP finetuning?  If you just want to use the FSDP finetuning, you can use the stable version of PyTorch with CUDA 11.7 with the commands this user from our community provides: https://github.com/haotian-liu/LLaVA/issues/123#issuecomment-1539434115. Thanks!

**Comment by mmaaz60** [comment]
It works fine with the stable pytorch 2.0 version as well. Thanks
