### ISSUE TITLE
[Question] The output of the llava-v1.6 model does not match my input prompt

### ISSUE THREAD

**Issue by Zenkus7** [haotian-liu/LLaVA#1595]
### Question

When using llava v1.6, I entered an image and provided the following prompt: "There are four aspects you must consider: 1) weather: ranging from sunny to snowy... 2) time: the time of day including daytime and nighttime. 3) road: the type of roads, including urban, suburban, rural, or highway. 4) lane: a description of the lane conditions. Please describe this image from fo." "Our aspects mentioned above and give the result in JSON format.".But the model outputs me a series of dialogue combinations, as shown in the picture below. Has anyone encountered this situation.
![Uploading image.png…]()

**Comment by zhanxuejie** [comment]
![Uploading drive.png…]()
