### ISSUE TITLE
[Usage] how to load the trained lora?

### ISSUE THREAD

**Issue by feiyangsuo** [haotian-liu/LLaVA#1597]
### Describe the issue

**Question:** 
I've trained a lora with scripts/v1_5/finetune_task_lora.sh. How to load the trained lora (as well as the original LLaVA model) for inference?

**What I've done:**
I've trained a lora with scripts/v1_5/finetune_task_lora.sh, and got a folder like this:
![image](https://github.com/user-attachments/assets/441f0006-ca42-4ccd-9d8c-c1680ef6593b)
I tried to modify the quickstart inference code into:
```
model_base = "liuhaotian/llava-v1.5-7b"
model_path = "/mnt/workspace/pyprojects/LLaVA-custom/work_dir/llava-v1.5-7b-task-lora"
prompt = "What are the things I should be cautious about when I visit here?"
image_file = "https://llava-vl.github.io/static/images/view.jpg"

args = type('Args', (), {
    "model_path": model_path,
    "model_base": model_base,
    "model_name": get_model_name_from_path(model_path),
    "query": prompt,
    "conv_mode": None,
    "image_file": image_file,
    "sep": ",",
    "temperature": 0,
    "top_p": None,
    "num_beams": 1,
    "max_new_tokens": 512
})()

eval_model(args)
```
(I just set `model_path` to the trained lora dir and `model_base` to original LLaVA model repo)

but I got error like this:
```
Traceback (most recent call last):
  File "/mnt/workspace/pyprojects/LLaVA-custom/_test_lora.py", line 29, in <module>
    eval_model(args)
  File "/mnt/workspace/pyprojects/LLaVA-custom/llava/eval/run_llava.py", line 55, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(
  File "/mnt/workspace/pyprojects/LLaVA-custom/llava/model/builder.py", line 54, in load_pretrained_model
    lora_cfg_pretrained = LlavaConfig.from_pretrained(model_path)
  File "/mnt/workspace/conda_envs/llava/lib/python3.10/site-packages/transformers/configuration_utils.py", line 605, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/mnt/workspace/conda_envs/llava/lib/python3.10/site-packages/transformers/configuration_utils.py", line 634, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/mnt/workspace/conda_envs/llava/lib/python3.10/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/mnt/workspace/conda_envs/llava/lib/python3.10/site-packages/transformers/utils/hub.py", line 356, in cached_file
    raise EnvironmentError(
OSError: /mnt/workspace/pyprojects/LLaVA-custom/work_dir/llava-v1.5-7b-task-lora does not appear to have a file named config.json. Checkout 'https://huggingface.co//mnt/bn/sunyi-dev/mlx/users/suofeiyang/pyprojects/LLaVA-custom/work_dir/llava-v1.5-7b-task-lora/checkpoint-20/main' for available files.
```

(Alse checked repo liuhaotian/llava-v1-0719-336px-lora-vicuna-13b-v1.3, and found that the dir structure is different from the trained lora's dir.)

**Comment by kumudlakara-bbc** [comment]
Hi @feiyangsuo, I have the same issue. Were you able to figure this out?

**Comment by feiyangsuo** [comment]
> Hi @feiyangsuo, I have the same issue. Were you able to figure this out?

still investigating

**Comment by feiyangsuo** [comment]
I guess it's not feasible (or some extra coding required) since my directory only contains tmp lora weights @kumudlakara-bbc 
https://github.com/haotian-liu/LLaVA/issues/1245

**Comment by Aabdihamzehkolaei-CLGX** [comment]
Something to be mindful about is the model_name parameter. If you don't specify that, the script generates it based on the model path and it might cause some issues. Trace the model_name in the script and make sure it's what you need.

**Comment by SuperheroZLP** [comment]
请问解决了吗？我也一样的问题

**Comment by yuanjunchai** [comment]
You could refer to this link, which is llava-v1.5-13b-lora model: https://huggingface.co/liuhaotian/llava-v1.5-13b-lora/tree/main.
So first, you need to utilize 'zero_to_fp32.py' to merge Deepspeed ckpt slides into .bin file, such as 'non_lora_trainables.bins'. And then you could using merge LoRA model with model base.
