### ISSUE TITLE
Running on MacOS

### ISSUE THREAD

**Issue by conorhearn1** [haotian-liu/LLaVA#161]
### feature

Do you have any plans to support running this on an Apple M2 processor? 

Thank you!

**Comment by haotian-liu** [comment]
Hi, we are working on support running the model on Apple Silicon.  There is a contribution from the community that currently supports this: https://github.com/cameronbergh/LLaVA-MPS/tree/mps, and you may try it out. We'll update once we finish the integration.  Thanks!

**Comment by ricoelmostico** [comment]
Hello ! Have this fork been merged or work on an apple compatiblity been done?
Thank you !

**Comment by louis030195** [comment]
Also interested, mostly to speed up development

**Comment by filipe-m-almeida** [comment]
You can start the worker jobs with --device mps and it will use the metal torch backend.

It's still a fairly inefficient code path, so you may be better off using the llama.cpp implementation: https://github.com/ggerganov/llama.cpp

**Comment by tljstewart** [comment]
@filipe-m-almeida how would one use llama.ccp instead of this this worker?

```python
python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-v1.5-13b --device mps
```

**Comment by haotian-liu** [comment]
macOS support is updated with quantization coming later. You can try both llama.cpp or the support of macOS in this repo.
