### ISSUE TITLE
[Question] Inference Code

### ISSUE THREAD

**Issue by bryanwong17** [haotian-liu/LLaVA#1645]
### Question

Thank you for the excellent work! I am curious if LLaVA is exclusively available for CLI inference. Is it possible to perform LLaVA inference using code without relying on the CLI? The reason for my inquiry is that using CLI inference is not convenient for generating text for a large number of images for research purposes. Thank you!

**Comment by Racktic** [comment]
i'm wondering the same thing! what's your solution?
