### ISSUE TITLE
[Question] Learning is completed, but only the weights of the projector are output.

### ISSUE THREAD

**Issue by onaka-ga-pkpk** [haotian-liu/LLaVA#1650]
### Question

We would like to make Mistral-7B-v0.3 our VLM with our own Continual Pre-Training and SFT.
I followed the tutorial, ran `pretrain.sh` and `finetune.sh` (Not Lora) and the training appeared to complete successfully. However, only three files, `config.json`, `mm_projector.bin`, and `trainer_state.json`, were output in the output directory.
How can I complete the training correctly?

**Comment by jzh15** [comment]
I came across your issue where after running pretrain.sh and finetune.sh, the output directory only contains config.json, mm_projector.bin, and trainer_state.json, but no model files were generated. I'm experiencing the same issue and was wondering if you found a solution.

Could you please share how you resolved this?

Thanks in advance!

**Comment by keanshi-nlp** [comment]
> I came across your issue where after running pretrain.sh and finetune.sh, the output directory only contains config.json, mm_projector.bin, and trainer_state.json, but no model files were generated. I'm experiencing the same issue and was wondering if you found a solution.
> 
> Could you please share how you resolved this?
> 
> Thanks in advance!

I came across the same issue. The pretrain output onlu contains config.json, mm_projector.bin and trainer_state.json, have you solved it?
