### ISSUE TITLE
[Question] What base python version should `LLaVA`  use ? like  `3.10` ,`3.11` ? 

### ISSUE THREAD

**Issue by q2333gh** [haotian-liu/LLaVA#1696]
### Question

I searched for issues.not find answer.

**Comment by Weili-0234** [comment]
You can refer to `2. Install Package` in the [README](https://github.com/haotian-liu/LLaVA#install) file, which uses `python=3.10`

**Comment by q2333gh** [comment]
Thanks alot ! I will try it ! 

> You can refer to `2. Install Package` in the [README](https://github.com/haotian-liu/LLaVA#install) file, which uses `python=3.10`
