### ISSUE TITLE
Maybe A bug

### ISSUE THREAD

**Issue by tensorboy** [haotian-liu/LLaVA#17]
https://github.com/haotian-liu/LLaVA/blob/main/llava/conversation.py#L96

The parameter of resize of pil  is (width, height) instead of (H, W) at your code:
<img width="614" alt="Screen Shot 2023-04-19 at 1 52 11 PM" src="https://user-images.githubusercontent.com/17189055/233197388-55dbb920-74fe-4857-92c7-b9ad520e8873.png">

reference: https://pillow.readthedocs.io/en/stable/reference/Image.html

**Comment by haotian-liu** [comment]
Thank you for pointing this out! Yes, it is indeed a mistake.

However, coincidentally it does not become a bug and becomes a naming error instead, as we obtained the width and height also using the PyTorch convension: `height, width = image.size`.

I will swap the `height` and `width` and seems like we're good to go?
