### ISSUE TITLE
[Question] How can I use the CLI after running the fine-tuning script?

### ISSUE THREAD

**Issue by Silverasdf** [haotian-liu/LLaVA#1726]
### Question

Hello, I was getting this error after trying to run the CLI with my custom fine-tuned model. My issue is that, after I ran finetune-lora.sh with no issues, it seems that there are multiple files missing from the directory. What is/are the step(s) that I need to take in order to fix this?

![Screenshot 2024-10-09 130210](https://github.com/user-attachments/assets/e826d81f-54ff-4f41-b141-af1749b5b111)

Thanks!

**Comment by IMOsbo** [comment]
I had a very similar issue with this... I don't think it's ever explicitly said anywhere, but I had to merge the LORA parameters with the model base before `llava.serve.cli` worked.

```
python scripts/merge_lora_weights.py \
    --model-path /path/to/lora_model \
    --model-base /path/to/base_model \
    --save-model-path /path/to/merge_model
```

<https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#create-merged-checkpoints>

**Comment by Silverasdf** [comment]
Thank you for providing this information. I think I may be one step closer to getting this to work. Actually, I was able to get it while providing the same model base I used in the finetune-lora script! However, I could not run the script correctly when I tried to run the actual merge script. Did you end up getting an error like this?

From the looks of it, the Traceback is from a python library rather than the code I could try modifying, but I figured it would be worth asking anyways.

```py
Traceback (most recent call last):
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 558, in save_pretrained
    raise ValueError(str([w.message for w in caught_warnings]))
ValueError: [UserWarning('`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.'), UserWarning('`do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rdpperuski/LLaVA/scripts/merge_lora_weights.py", line 22, in <module>
    merge_lora(args)
  File "/home/rdpperuski/LLaVA/scripts/merge_lora_weights.py", line 10, in merge_lora
    model.save_pretrained(args.save_model_path)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2364, in save_pretrained
    model_to_save.generation_config.save_pretrained(save_directory)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/generation/configuration_utils.py", line 560, in save_pretrained
    raise ValueError(
ValueError: The generation config instance is invalid -- `.validate()` throws warnings and/or exceptions. Fix these issues to save the configuration.

Thrown during validation:
[UserWarning('`do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.'), UserWarning('`do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.')]```

**Comment by YUECHE77** [comment]
> I had a very similar issue with this... I don't think it's ever explicitly said anywhere, but I had to merge the LORA parameters with the model base before `llava.serve.cli` worked.
> 
> ```
> python scripts/merge_lora_weights.py \
>     --model-path /path/to/lora_model \
>     --model-base /path/to/base_model \
>     --save-model-path /path/to/merge_model
> ```
> 
> https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#create-merged-checkpoints

Hello,

Could you please give more information about running CLI?

I've merged the LORA parameters with the base_model, but when I run the CLI, I got many mismatched parameters:

![image](https://github.com/user-attachments/assets/09137098-018e-4006-93a5-5a2d56d322c5)

Here is my merged model folder:

![image](https://github.com/user-attachments/assets/98fd1830-fe96-4266-89f1-d866acf55e38)

And the LoRA folder:

![image](https://github.com/user-attachments/assets/6a504f04-1cf1-4d64-bf20-923f57ca6c80)

Thank you!
