### ISSUE TITLE
[Question] Not able to load https://huggingface.co/liuhaotian/llava-lcs558k-scienceqa-vicuna-13b-v1.3 into google colab. Please help 🙏🙏

### ISSUE THREAD

**Issue by cookiesupers22** [haotian-liu/LLaVA#1737]
### Question

# Load model directly
from transformers import AutoProcessor, AutoModelForCausalLM

processor = AutoProcessor.from_pretrained("liuhaotian/llava-lcs558k-scienceqa-vicuna-13b-v1.3")
model = AutoModelForCausalLM.from_pretrained("liuhaotian/llava-lcs558k-scienceqa-vicuna-13b-v1.3")
I am trying to run the above code in google colab from this huggingface Llava model: https://huggingface.co/liuhaotian/llava-lcs558k-scienceqa-vicuna-13b-v1.3

For some reason, I keep getting this error I have no idea what to do:

Traceback (most recent call last)

HTTPError               Traceback (most recent call last)

 in hf_raise_for_status(response, endpoint_name)
    405     try:
--> 406         response.raise_for_status()
    407     except HTTPError as e:

/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py

 in hf_raise_for_status(response, endpoint_name)
    405     try:
--> 406         response.raise_for_status()
    407     except HTTPError as e:

/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py
18 frames

HTTPError: 404 Client Error: Not Found for url: 
https://huggingface.co/liuhaotian/llava-lcs558k-scienceqa-vicuna-13b-v1.3/resolve/main/preprocessor_config.json

The above exception was the direct cause of the following exception:

EntryNotFoundError                        Traceback (most recent call last)

EntryNotFoundError: 404 Client Error. (Request ID: Root=1-67100499-78a68eb3676bcc6b7eaa4c27;c4259ef9-af93-4126-8bb4-561929fbfae1)

Entry Not Found for url: .
https://huggingface.co/liuhaotian/llava-lcs558k-scienceqa-vicuna-13b-v1.3/resolve/main/preprocessor_config.json

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)

 in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)
    434         if revision is None:
    435             revision = "main"
--> 436         raise EnvironmentError(
    437             f"{path_or_repo_id} does not appear to have a file named {full_filename}. Checkout "
    438             f"' for available files."

/usr/local/lib/python3.10/site-packages/transformers/utils/hub.pyhttps://huggingface.co/{path_or_repo_id}/{revision}'

OSError: liuhaotian/llava-lcs558k-scienceqa-vicuna-13b-v1.3 does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/liuhaotian/llava-lcs558k-scienceqa-vicuna-13b-v1.3/main' for available files.

**Comment by shardi-b** [comment]
Having the very same issue!

**Comment by cookiesupers22** [comment]
> Having the very same issue!

Try this. Just got it working for me.
#works with scienceqa checkpoints one
from llava.model.builder import load_pretrained_model
from llava.mm_utils import get_model_name_from_path
from llava.eval.run_llava import eval_model


model_path = "liuhaotian/llava-lcs558k-scienceqa-vicuna-13b-v1.3"

tokenizer, model, image_processor, context_len = load_pretrained_model(
    model_path=model_path,
    model_base=None,
    model_name=get_model_name_from_path(model_path)
)

**Comment by mrgransky** [comment]
What is the reason that we can't load the models using transformers?
