### ISSUE TITLE
[Question] How can I create optimizer.pt file for the checkpoint when I finetune the model?

### ISSUE THREAD

**Issue by Bleking** [haotian-liu/LLaVA#1739]
### Question

I would like to create checkpoints so I can try gradually increasing the epoch and find out when the model start to overfit. I heard that optimizer.pt file is required in order to start from a specific checkpoint defined by 'resume_from_checkpoint' argument.

Whenever I form a checkpoint, it appears like this
![image](https://github.com/user-attachments/assets/82a53634-42c7-4c88-8b11-f3f517b6e5c7)
without any optimizer.pt.

I have tried adding `torch.save(trainer.optimizer.state_dict(), os.path.join(training_args.output_dir, 'optimizer.pt'))` line at the bottom of the 'train' function of 'train.py' code but neither does it work.

This is my script for your information:

> #!/bin/bash
> 
> deepspeed llava/train/train_xformers.py \
>     --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
>     --deepspeed ./scripts/zero3_offload.json \
>     --model_name_or_path liuhaotian/llava-v1.5-13b \
>     --version v1 \
>     --data_path ./playground/data/train.json \
>     --valid_data_path ./playground/data/valid.json \
>     --image_folder ./playground/data/ \
>     --vision_tower openai/clip-vit-large-patch14-336 \
>     --mm_projector_type mlp2x_gelu \
>     --mm_vision_select_layer -2 \
>     --mm_use_im_start_end False \
>     --mm_use_im_patch_token False \
>     --image_aspect_ratio pad \
>     --group_by_modality_length True \
>     --fp16 True \
>     --output_dir ./checkpoints/results \
>     --num_train_epochs 1 \
>     --per_device_train_batch_size 4 \
>     --per_device_eval_batch_size 4 \
>     --gradient_accumulation_steps 8 \
>     --evaluation_strategy "steps" \
>     --save_strategy "steps" \
>     --save_steps 1000 \
>     --save_total_limit 1 \
>     --learning_rate 2e-5 \
>     --weight_decay 0.01 \
>     --warmup_ratio 0.03 \
>     --lr_scheduler_type "cosine" \
>     --logging_steps 1 \
>     --tf32 False \
>     --model_max_length 2048 \
>     --gradient_checkpointing True \
>     --dataloader_num_workers 4 \
>     --lazy_preprocess True \
>     --report_to wandb
>     --load_best_model_at_end True \
>     --resume_from_checkpoint ./checkpoints/results/checkpoint-##

How did you guys get to create a checkpoint to continue finetuning from? What should I do with the script and the 'train.py' code? Any advice?

Thank you.

**Comment by XindiWu** [comment]
The optimizer states are saved by DeepSpeed, and when using DeepSpeed with multiple GPUs, it splits the optimizer state across different ranks (one file per GPU). You don't need to modify the saving code because DeepSpeed is already handling the optimizer state saving correctly. The saved optimizer states are under ./global_step6 folder.

**Comment by Bleking** [comment]
Thank you for the information. Well, I had tried adding `torch.save(trainer.optimizer.state_dict(), os.path.join(training_args.output_dir, 'optimizer.pt'))` line at the bottom of the "train" function in the [train.py](https://github.com/haotian-liu/LLaVA/blob/main/llava/train/train.py) code but it looks like it was not a necessary act.
