### ISSUE TITLE
LLaVA-MPT-7b weights

### ISSUE THREAD

**Issue by aolivtous** [haotian-liu/LLaVA#179]
### Question

Hi, congrats on your amazing work!
I was wondering if the weights of LLaVA-MPT-7b model are available somewhere after pretraining and finetuning.
Thanks!

**Comment by haotian-liu** [comment]
Hi, please checkout the weights of MPT model [here](https://huggingface.co/liuhaotian/LLaVA-Lightning-MPT-7B-preview).

**Comment by aolivtous** [comment]
Thanks!

**Comment by harrietfiagbor** [comment]
Also, is finetuning the LLava-MPT-7B weights any different from the finetuning process? Since you stated that it can be used directly without delta weights, finetuning is just giving dataset in llava instruct format?

**Comment by haotian-liu** [comment]
@harrietfiagbor 

There is not difference in the finetuning process.  This decision (w/o delta weights) is simply due to the LLaMA license (and the general practice in the community).

We now release full model weights that do not require delta weight merging.
