### ISSUE TITLE
[Usage] RuntimeError: Failed to import transformers.trainer

### ISSUE THREAD

**Issue by EEElisa** [haotian-liu/LLaVA#1808]
### Describe the issue

I run the following script for fine-tuning:
```
sh scripts/v1_5/finetune_task_lora.sh
```

Here's the error message I got:
```
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'EncoderDecoderCache' from 'transformers' (/usr/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/__init__.py)
```

It looks like there's a mismatch between transformers and other libraries.

**Comment by zhangye0402** [comment]
facing the same problem, did you solve it?
thank you!

**Comment by TuuSiwei** [comment]
+1

**Comment by Murasame-sway** [comment]
pip install peft==0.10.0 can solve the problem，my transformers version is 4.42.0
