### ISSUE TITLE
[Usage] Slow inference speed

### ISSUE THREAD

**Issue by shawnshenjx** [haotian-liu/LLaVA#186]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue:
Slow inference speed
Command:
```
python run_llava.py --model-name /home/shawn/desktop/LLaVA-13B-v0 --image-file "https://llava-vl.github.io/static/images/view.jpg" --query "Describe."
```

Log: 
```
Inference Time:15.626604557037354
The image features a serene scene with a wooden pier extending out over a large body of water, such as a lake or a mountain-surrounded bay. The water is calm and clear, reflecting the beauty of the surrounding landscape. There are a few small boats scattered on the water, adding to the peaceful atmosphere.

The pier itself has a few steps, and a bench is located at the end of the pier, inviting visitors to sit and enjoy the view. The entire scene is framed by trees and mountains, making it a picturesque and inviting location for relaxation or contemplation.
```

I am using a server with 3x3090 GPU cards. Why the inference speed is this slow? I tried multiple times and the inference time is usually around 15-25 seconds. I only measure the time for this function:     
with torch.inference_mode():
        output_ids = model.generate(
            input_ids,
            images=image_tensor.unsqueeze(0).half().cuda(),
            do_sample=True,
            temperature=0.2,
            max_new_tokens=1024,
            stopping_criteria=[stopping_criteria])

This one costs 15-25 seconds. May I ask why is that?

**Comment by hszhoushen** [comment]
> ### When did you clone our code?
> I cloned the code base after 5/1/23
> 
> ### Describe the issue
> Issue: Slow inference speed Command:
> 
> ```
> python run_llava.py --model-name /home/shawn/desktop/LLaVA-13B-v0 --image-file "https://llava-vl.github.io/static/images/view.jpg" --query "Describe."
> ```
> 
> Log:
> 
> ```
> Inference Time:15.626604557037354
> The image features a serene scene with a wooden pier extending out over a large body of water, such as a lake or a mountain-surrounded bay. The water is calm and clear, reflecting the beauty of the surrounding landscape. There are a few small boats scattered on the water, adding to the peaceful atmosphere.
> 
> The pier itself has a few steps, and a bench is located at the end of the pier, inviting visitors to sit and enjoy the view. The entire scene is framed by trees and mountains, making it a picturesque and inviting location for relaxation or contemplation.
> ```
> 
> I am using a server with 3x3090 GPU cards. Why the inference speed is this slow? I tried multiple times and the inference time is usually around 15-25 seconds. I only measure the time for this function: with torch.inference_mode(): output_ids = model.generate( input_ids, images=image_tensor.unsqueeze(0).half().cuda(), do_sample=True, temperature=0.2, max_new_tokens=1024, stopping_criteria=[stopping_criteria])
> 
> This one costs 15-25 seconds. May I ask why is that?

How do you fix this problem, did you just turn off the screen output of language description?

**Comment by WilTay1** [comment]
i got the same slow, very slow. Can you please show how to solve it? Thanks.
