### ISSUE TITLE
Question about the object detection

### ISSUE THREAD

**Issue by Richar-Du** [haotian-liu/LLaVA#19]
When encoding the image to prompt, you mentioned *captions* and *bounding boxes*, I wonder which object detection model you utilized to generate the bounding boxes?

**Comment by wanxinzzz** [comment]
> When encoding the image to prompt, you mentioned _captions_ and _bounding boxes_, I wonder which object detection model you utilized to generate the bounding boxes?

I think the bounding boxes come from ground truth in coco dataset

**Comment by haotian-liu** [comment]
Hi @Richar-Du both annotations come from the original COCO dataset: captions from coco-caption-2014 annotation, and boxes from coco-instances-2014 annotations.

Thanks @wanxinzzz for answering!

**Comment by Richar-Du** [comment]
Got it, thanks for your explanations :)
