### ISSUE TITLE
[Question] How much GPU memory is required for inference

### ISSUE THREAD

**Issue by xielong** [haotian-liu/LLaVA#191]
### Question

I'm currently trying to use your project for some inference tasks and I'm wondering about the GPU memory requirements. Could you please provide some guidance on how much GPU memory is typically needed for inference using this model?

I'd appreciate it if you could also share any tips on how to optimize memory usage, or any methods to run the model on a GPU with less memory.

**Comment by haotian-liu** [comment]
Hi, typically the 7B model can run with a GPU with less than 24GB memory, and the 13B model requires ~32 GB memory.  You can use multiple 24-GB GPUs to run 13B model as well following the instructions [here](https://github.com/haotian-liu/LLaVA#launch-a-model-worker-multiple-gpus-when-gpu-vram--24gb).

We are also working on bitsandbytes to further cut down the memory cost.  What kind of GPUs are you thinking of currently?

**Comment by xielong** [comment]
Thank you for your response. I'm just getting started with large models and don't have much knowledge about GPUs. However, I should be trying to run inference on the public cloud.

**Comment by haotian-liu** [comment]
Just for your reference, we now support 4-bit/8-bit inference, which can reduce the GPU memory footprint by 4x/2x respectively, as a cost of a slight performance (accuracy) degradation. You can also try with multiple GPU inference as documented above.

https://github.com/haotian-liu/LLaVA#launch-a-model-worker-4-bit-8-bit-inference-quantized

**Comment by xielong** [comment]
Thanks, I'll give it a try.

**Comment by haotian-liu** [comment]
Closing for now. Please feel free to re-open or open a new issue, if there are any other questions. Thank you!
