### ISSUE TITLE
Discussion about training in Stage 1 [Discussion] 

### ISSUE THREAD

**Issue by xianghuisun** [haotian-liu/LLaVA#195]
### Discussion

I have a question about training. Specifically, In stage 1: Pre-training for Feature Alignment. The statement in the paper is: 
```
In training, we keep both the visual encoder and LLM weights frozen, and maximize the likelihood of (3) with trainable parameters θ = W (the projection matrix) only.
```
But there is an additional update to the embed_tokens of LLM in the code.
```
            if tune_mm_mlp_adapter:
                self.get_model().orig_embeds_params = [self.get_input_embeddings().weight.data.clone().to(device=device)]
                for p in self.get_input_embeddings().parameters():
                    p.requires_grad = True
```
If we do not update the embed_tokens of LLM, does the performance will decreased significantly?

**Comment by wangjiongw** [comment]
I met the same problem. Since the projector is pretrained in stage 1 while ViT & LLM freeze, how can I test the performance of naive mm projector ?

**Comment by haotian-liu** [comment]
Hi, we find that removing these additional tokens does not affect the performance, and we thus remove these tokens in our latest release. Thanks.
