### ISSUE TITLE
[Question] Five sentences about an image for GPT4 prompting

### ISSUE THREAD

**Issue by jun297** [haotian-liu/LLaVA#198]
### Question

![image](https://github.com/haotian-liu/LLaVA/assets/25261314/4e8765c3-7f81-4123-bea8-77ef22a0f081)
Like the prompt in table 10, how can I get the five sentences from an image?

**Comment by haotian-liu** [comment]
Hi, the five sentences from the image are obtained from COCO 2014 Captions annotation, which you can download [here](https://cocodataset.org/#download), thanks!

**Comment by jun297** [comment]
Thanks a lot!
