### ISSUE TITLE
Llava-mpt weights

### ISSUE THREAD

**Issue by harrietfiagbor** [haotian-liu/LLaVA#202]
### Question

Hello, thanks for your amazing work. Wanted to know if the Llava-mpt supports finetuning?

Also, there is a new quantization called qlora that I want to implement on the model but it seems the transformer library you have here is not up to date to do that. Can it be upgraded to incorporate the new changes?

**Comment by haotian-liu** [comment]
Hi @harrietfiagbor 

Thank you for your interest in our work.

LLaVA-MPT supports finetuning, and you can follow the scripts here: https://github.com/haotian-liu/LLaVA/blob/main/scripts/train_lightning_mpt.sh

Regarding QLora, I am also interested in this work and I have actually been trying their code base in the past weekend.  I am currently working on integrating the basic version (LoRA) in the code base, and I'll investigate the `transformer` compatibility issue later today or tomorrow. I am aware of at least one compatibility issue that needs to be resolved to upgrade the package.  I'll send you an update by tomorrow :)

**Comment by harrietdede** [comment]
Hey @haotian-liu 

Thanks for your quick reply. Really appreciated. Also, to clarify my question, the preview version available can be finetuned directly without any projector weights right? I just want to run the finetune script. Don't know if it is the right thing to do

**Comment by haotian-liu** [comment]
Do you mean that you want to start with my released checkpoint, and further finetune to some other datasets?  In this case, you can simply run the following command (change base checkpoint to the released checkpoint, and remove `--pretrain_mm_mlp_adapter`).

```
torchrun --nnodes=1 --nproc_per_node=8 --master_port=25001 \
    llava/train/train_mem.py \
    --model_name_or_path liuhaotian/LLaVA-Lightning-MPT-7B-preview \
    --version v1 \
    --data_path /path/to/llava_instruct_80k.json \
    --image_folder /Data/haotian/coco/train2014 \
    --vision_tower openai/clip-vit-large-patch14 \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 True \
    --output_dir ./checkpoints \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 5000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'MPTBlock' \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

**Comment by harrietfiagbor** [comment]
Thank you so much @haotian-liu. This was really helpful

**Comment by kahnchana** [comment]
Did you get a `WARNING: tokenization mismatch: 450 vs. 451. (ignored)` message when doing this?

**Comment by harrietfiagbor** [comment]
@kahnchana Yes , I did get such a warning which led me into getting this error, 
`TypeError: LlavaMPTForCausalLM.forward() got an unexpected keyword argument 'inputs_embeds'`
Did you encounter anything like this?

**Comment by findalexli** [comment]
@harrietfiagbor @kahnchana  Were you able to resolve the issue? Can I ask you how?

**Comment by haotian-liu** [comment]
Apologies for the confusion. For MPT models, there was some compatibility issue, which has been resolved in the latest code base.  Please check out the latest code base and MPT checkpoints should work :)

**Comment by haotian-liu** [comment]
Closing for now. Please feel free to re-open or open a new issue, if there are any other questions. Thank you!
