### ISSUE TITLE
[Question] Question about the replace_token

### ISSUE THREAD

**Issue by penghe2021** [haotian-liu/LLaVA#203]
### Question

In the model_worker code, it will replace the 'image_patch' token with the line:
https://github.com/haotian-liu/LLaVA/blob/8b21169def6c8ed57afa5e7bf790c1a91b530940/llava/serve/model_worker.py#L218
My question is: is this line only for single image input, or we need to do it for every image patch token when we try multi image input.

**Comment by haotian-liu** [comment]
The `DEFAULT_IMAGE_PATCH_TOKEN` basically creates a placeholder for the tokenizer to prepare for the space for us to put in image features extracted from visual encoder.

https://github.com/haotian-liu/LLaVA/blob/main/llava/model/llava.py#L151

The current (expected) behavior is that if you want to query about two images, for example:
```
Human: Describe image A: <image>
Assistant: <response>
Human: Image B: <image>
Assistant: <response>
```
The model has the access to the first image as well, we will replace each `<image>` with `'<IM_PATCH_TOKEN>'*<patch_num_per_image>`.

Please let me know if there is anything unclear, thanks.

**Comment by penghe2021** [comment]
Sorry I missed the notification. Thanks, that's very clear, previously I thought the number 256 means the max number of images in the entire conversation.
