### ISSUE TITLE
[Question] Running LLaVA-13b-v1-1 locally gets slightly different results with web demo

### ISSUE THREAD

**Issue by jun297** [haotian-liu/LLaVA#209]
### Question

Hi, I am running LLaVA-13B-v1-1 in web UI or CLI

I am trying to reproduce the results as the same as the web demo (https://llava.hliu.cc/)

However, I got slightly diffrent results with examples

From web UI:
<code>
The unusual aspect of this image is that a man is ironing clothes while standing on the back of a moving car. This is an unconventional and dangerous way to iron clothes, as it poses significant risks to the man's safety and the safety of others on the road. Typically, ironing is done at home or in a designated area, not on the back of a moving vehicle. Additionally, the man is wearing a yellow sweater, which is not common attire for someone ironing clothes in public.
</code>
From web demo:
<code>
The unusual aspect of this image is that a man is standing on a portable ironing board in the middle of a busy city street, ironing clothes. This is not a typical scene you would expect to see in an urban environment, as ironing is usually done in the comfort and privacy of one's home. The man's actions are drawing attention and likely causing curiosity among the people passing by and the traffic around him. Additionally, there is a parked yellow SUV in the background, which further contributes to the uncommon setting of the scene.
</code>
while it is possible to regenerate the same result itself with some images, I also failed to reproduce the same results with other images

I used 0.01 temperature and 1024 max output token for both results

**Comment by haotian-liu** [comment]
Hi @jun297, thank you for the interest in our work and for bringing this to our attention.  There was some maintenance in our lab A6000 workstations which we use to host the demo, we switch servers several times this week.   Unfortunately in one of the deployment this Wednesday, there was some issues with the model configuration.  It is now updated and the behavior should be the same with your local one.

**Comment by jun297** [comment]
@haotian-liu Thanks a lot!
Now the web demo has the same results as the web UI, however, I failed to reproduce the same results in CLI. Is it intended?
I used 0.01 temperature and 1024 max token as well and checked prompt but there was no difference.

**Comment by haotian-liu** [comment]
Hi @jun297 

Currently the webui and cli should have the same prompt settings. We've also updated the CLI to support multiturn conversation. You can see the documentation [here](https://github.com/haotian-liu/LLaVA#cli-inference).

**Comment by jun297** [comment]
@haotian-liu thanks
I forgot to close this. 
I think that the difference comes from different conv_mode, resulting different prompt

**Comment by euanong** [comment]
I'm still encountering this issue -- has this been fixed? If not, which checkpoint should I use to run LLaVA from in order to match the results of the demo?
