### ISSUE TITLE
Any plan to release the cc3m filtered data and the weight of the linear layer after the 1st training stage?

### ISSUE THREAD

**Issue by Richar-Du** [haotian-liu/LLaVA#21]
It would be valuable to train our model based on the linear layer after the 1st training stage. Meanwhile, will the filtered cc3m data be released?

Thanks a lot!

**Comment by WooKimm** [comment]
+1

**Comment by jpWang** [comment]
+1

**Comment by haotian-liu** [comment]
Hi @Richar-Du @WooKimm @jpWang , thank you for your interest in our work!

Our pretraining dataset is released.  Please see [here](https://github.com/haotian-liu/LLaVA#pretraining-dataset).

The linear layer weights is also released.  Please see [here](https://github.com/haotian-liu/LLaVA#llava-pretrained-projector-weights).

**Comment by Richar-Du** [comment]
Great! Thanks a lot!
