### ISSUE TITLE
[Usage] Model config in huggingface has incorrect token ids for start and end of sequence

### ISSUE THREAD

**Issue by jihan-yin** [haotian-liu/LLaVA#213]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

The model config at https://huggingface.co/liuhaotian/LLaVA-Lightning-7B-delta-v1-1/tree/main has an incorrect mapping of the bos token id and eos token id, for both the `generation_config.json` and `config.json` (the prior doesn't matter as it just points to the latter).

In Llava, the bos token id is set to 0, and the eos token id is set to 1. You can see this is incorrect by loading the tokenizer from the model weights and printing `tokenizer.bos_token_id` and `tokenizer.eos_token_id`. They should be `1` and `2`, respectively. This matches the base model, vicuna, as seen here - https://huggingface.co/lmsys/vicuna-7b-delta-v1.1/blob/main/config.json.

Because of this issue, if you try to do batch generation with the decoder, you will run into errors when the model tries to generate `eos` but fails. Here is a 100% reproducible example with the llava-7b-lightning checkpoint:

```
prompts = ['Answer these questions:\nQ: Who sang who wants to be a millionaire in high society?\nA: Frank Sinatra\nQ: Who won oscar for best director this month?\nA:', 'Answer these questions:\nQ: Who sang who wants to be a millionaire in high society?\nA: Frank Sinatra\nQ: When was the first dark tower book published?\nA:']
for p in prompts:
    print(p)
inputs = tokenizer(prompts, padding=True, return_tensors='pt')
out = model.generate(**inputs, max_new_tokens=50)
```

This will error out with a CUDA error, because the model generates the token `1` to mark the eos for one of the two samples in the batch, when it should have generated a `2`.

**Comment by jihan-yin** [comment]
Actually, it seems even with this change, we will still get an error when the model generates the eos token id on a different example:

```
prompts = ['Answer these questions:\nQ: Who sang who wants to be a millionaire in high society?\nA: Frank Sinatra\nQ: How many members in order of the phoenix?\nA:', 'Answer these questions:\nQ: Who sang who wants to be a millionaire in high society?\nA: Frank Sinatra\nQ: The secret life of walter mitty james thurber pdf?\nA:']
for p in prompts:
    print(p)
tokenizer.padding_side = 'left'
inputs = tokenizer(prompts, padding=True, return_tensors='pt')
out = model.generate(**inputs, max_new_tokens=50)
```

**Comment by jihan-yin** [comment]
Ah resolved the above, we have to set the `pad_token_id` to 0 as well. This is because huggingface's greedy generation will automatically set all following token ids to the `pad_token_id` when the `eos_token` is encountered for a sample in a batch. Llava's `pad_token_id` is set to -1, which results in the cuda indexing error.

**Comment by haotian-liu** [comment]
HI @jihan-yin 

Thanks for providing the information on this!  I will be working on fixing these tokenization errors next week, and hopefully we can have the HF inference pipeline and batch inference working soon :)

**Comment by xiujiesong** [comment]
Hi haotian,

Thanks for the great work. Is the HF inference pipeline available now？

**Comment by haotian-liu** [comment]
Hi @xiujiesong 

We have supported HF inference pipeline for both [offline generation](https://github.com/haotian-liu/LLaVA/blob/main/llava/eval/run_llava.py) and [streaming generation](https://github.com/haotian-liu/LLaVA/blob/main/llava/serve/cli.py).
