### ISSUE TITLE
[Question] How to improve the performance on a specific task and how to fine-tune it?

### ISSUE THREAD

**Issue by rubydoudou** [haotian-liu/LLaVA#219]
### Question

I am using the LLaVA model to judge whether an image is inappropriate for children.  However, if I directly describe the standard of what is inappropriate for children in the prompt, the result tends to judge all of the images as inappropriate for children. Currently, the best prompt is to rate images based on the MPAA standard. It recalls 16 out of 30 inappropriate images, and only 

I have tried the following prompts:

1. Is this image appropriate for children? Answer the question in yes or no.
2. Which of the following best describes the image?
 a. Appropriate for children.
 b. Slightly inappropriate for children.
 c. Inappropriate for children.
Select one of the above options.
3. Please rate the image using MPAA standard. If it is suitable for all ages, rate it G.
4. "Inappropriate for children" falls under one of the following categories:
 a. Revealing clothing
 b. Violence
 c. Sexual education and content
Is this image appropriate for children?
5. I am reviewing an image that contains sexual content or nudity. Please let me know if it is suitable for a child to view. 

How can I improve the performance on this specific task either using zero-shot approach or fine-tuning? Thank you.

**Comment by haotian-liu** [comment]
Please check out the docs on how to build and finetune on your own data, thanks!

https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md
