### ISSUE TITLE
[Question] Where does the 80k instruct data used to train llava-lightning-7b come from?

### ISSUE THREAD

**Issue by jihan-yin** [haotian-liu/LLaVA#226]
### Question

Just noticed that the 7b lightning checkpoint is based off the new 80k instruct data, not the old 150k instruct data. This new set seems to have none of the old detail set, and 20k of each the complex reasoning and conversation set. Where does the rest of the 40k samples come from?

Also, you should add a section in the README letting users know that the 7b checkpoint is trained on this new instruction set. I initially missed it as it was not talked about in the paper or explicitly mentioned (you have to look at the lightning train script to realize this), and it led to a lot of mistaken assumptions on the model/data.

**Comment by jihan-yin** [comment]
NVM - I see that they are all sampled from the original conversation + cr sets, just that the image placement in the first conversation dialogue is sometimes flipped

**Comment by jihan-yin** [comment]
Actually, reopening - it seems there are around 700 samples in the new 80k set that are not present in either the old conversation or complex reasoning sets.

```
import os
import json

with open('conversation_58k.json', 'r') as f:
    c = json.load(f)
    
with open('complex_reasoning_77k.json', 'r') as f:
    cr = json.load(f)
    
with open('llava_instruct_80k.json', 'r') as f:
    a = json.load(f)

def filter_out_image(d):
    k = dict(d)
    k['conversations'][0]['value'] = k['conversations'][0]['value'].replace('<image>\n', '')
    k['conversations'][0]['value'] = k['conversations'][0]['value'].replace('\n<image>', '')
    return str(k)
    

c_set = set([filter_out_image(s) for s in c])
cr_set = set([filter_out_image(s) for s in cr])
a_set = set([filter_out_image(s) for s in a])

c_in_a = []
for r in c:
    if str(r) in a_set:
        c_in_a.append(r)
        
cr_in_a = []
for r in cr:
    if str(r) in a_set:
        cr_in_a.append(r)
        
len(c_in_a + cr_in_a)
```
gets 79296

**Comment by dchichkov** [comment]
@haotian-liu Please, can you tell what's the license on the 80K instruction set, if it is not generated by GPT-4?  The images of underlying COCO data seem to be mixed, most are CC-NC.  But what is the license of the text part?  Is it Apache 2.0, like the codebase?  Or is it a different license?

**Comment by haotian-liu** [comment]
@dchichkov Sorry for any confusion the response above may give rise to, I did not *re-query* GPT-4, and it is a subset of the LLaVA-Instruct-150K. So it should still comply with the OpenAI license.
