### ISSUE TITLE
Can LLaVa support Chinese QA?[Question] 

### ISSUE THREAD

**Issue by CaicaiJason** [haotian-liu/LLaVA#238]
### Question

how can i do to make LLaVa answers my question in Chinese?

**Comment by DexterGuo** [comment]
经过测试，如果不做任何操作，原生llava基本上不会用中文回答；如果有微调的数据集，直接进行微调即可，不用做过多的其他操作；

**Comment by haotian-liu** [comment]
LLaVA-1.5 has an intriguing emergent capability of answering Chinese questions, with no Chinese multimodal instruction data. We believe it can be further improved when finetuned on Chinese instruction data.
