### ISSUE TITLE
[Question] Fine-tuning Issues.

### ISSUE THREAD

**Issue by Hiusam** [haotian-liu/LLaVA#243]
### Question

Hi Haotian,

I am writing to ask what is your fine-tuning script. As long as I specify
```
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer'
```
It will raise:
<img width="1012" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/43744525/b45932a1-6236-4dce-92d8-83e7bb8a328a">
Is this caused since I am not using pytorch2.0? I am using pytorch 1.12.1
But without specifying fsdp, it will OOM even if I use graident checkpointing.

Also, in your train.py, this will raise an error:
<img width="977" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/43744525/df12cfe4-45f2-4301-b4b5-c9e5567fbb41">

Thank you very much for your reply!

**Comment by findalexli** [comment]
I think you need to update to pytorch 2.0
