### ISSUE TITLE
[Question] About lora inference

### ISSUE THREAD

**Issue by crystraldo** [haotian-liu/LLaVA#245]
### Question

After fine-turning with lora in deepspeed. How to merge the lora weights to pre-training weights or how to load lora weights for testing directly?

**Comment by zengxijuan** [comment]
I have the same question, have you solved now?

**Comment by zengxijuan** [comment]
I find that  https://stackoverflow.com/questions/76459034/how-to-load-a-fine-tuned-peft-lora-model-based-on-llama-with-huggingface-transfo

**Comment by haotian-liu** [comment]
Hi, you can use [this script](https://github.com/haotian-liu/LLaVA/blob/main/scripts/merge_lora_weights.py) for merge lora weights. We'll update this in instruction as well. Thanks.

**Comment by LeoLee7** [comment]
> > Hi, you can use [this script](https://github.com/haotian-liu/LLaVA/blob/main/scripts/merge_lora_weights.py) for merge lora weights. We'll update this in instruction as well. Thanks.
> 
> what is the model-base parameter after pretrain?

The model-base is the name of your finetuned model, like `liuhaotian/llava-v1.5-13b`
The model-path is the path where you save the LoRA folder, like `llava-v1.5-13b-task-lora-YOUR-FINETUNE-MODEL` under `./checkpoints`

**Comment by 20191864218** [comment]
> > > Hi, you can use [this script](https://github.com/haotian-liu/LLaVA/blob/main/scripts/merge_lora_weights.py) for merge lora weights. We'll update this in instruction as well. Thanks.
> > 
> > 
> > what is the model-base parameter after pretrain?
> 
> The model-base is the name of your finetuned model, like `liuhaotian/llava-v1.5-13b` The model-path is the path where you save the LoRA folder, like `llava-v1.5-13b-task-lora-YOUR-FINETUNE-MODEL` under `./checkpoints`

Hello, my understanding of this part of the code is that model_base is the LLM, and model_path is the path where you save the LoRA folder， if my understanding is correct?Thanks
`python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-vicuna-7b-v1.1-lcs_558k-instruct_80k_3e-lora-preview-alpha --model-base /path/to/vicuna-v1.1`
