### ISSUE TITLE
[Feature request] Could you please merge some installation steps to reduce carbon emission?

### ISSUE THREAD

**Issue by shamio** [haotian-liu/LLaVA#249]
### feature

I really like your work and its so strong model, but i have a request. The installation process is difficult for beginner and non-coder users. Please make it easier that more people can use it. Also please merge the below steps and make it possible for users to downland the trained and ready-to-use model instead of going through these processes. Honestly there is no need that every single person goes through this difficult procedure and uses a lot of electricity to produce the same results. by making the files ready to download, you can help reduce carbon emission. The steps i mentioned are as below ( but I'm sure some other steps can be reduced too )
```
Get the original LLaMA weights in the huggingface format by following the instructions [here](https://huggingface.co/docs/transformers/main/model_doc/llama).
Use the following scripts to get LLaVA weights by applying our delta ([13b-v0](https://huggingface.co/liuhaotian/LLaVA-13b-delta-v0), [7b-v0](https://huggingface.co/liuhaotian/LLaVA-7b-delta-v0), [lightning-7B-v1-1](https://huggingface.co/liuhaotian/LLaVA-Lightning-7B-delta-v1-1)). It will automatically download delta weights from our Hugging Face account.
```

**Comment by haotian-liu** [comment]
Hi, thank you for the suggestion.

The delta weights were initially released in this way following the common practice of Vicuna and Alpaca series models, due to the LLaMA license.

For our latest checkpoints, we release the merged checkpoints directly. Thanks.
