### ISSUE TITLE
[Usage] Floating point exception when following fine-tuning example

### ISSUE THREAD

**Issue by jpgard** [haotian-liu/LLaVA#252]
Thanks for the awesome repo and the exciting progress on multimodal learning. Looking forward to trying out the model and building off of it, but having some issues getting started with fine-tuning my own to replicate the training process you describe in the repo.

### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

Issue: I am attempting to run the fine-tuning command given in the main repo [here](https://github.com/haotian-liu/LLaVA#fine-tuning-with-local-gpus) to verify my setup works before making some changes to the code for my own experiments.

I downloaded the training datasets from hugging face, along with the vicuna checkpoints.

I am attempting to train the model on a single A40 40GB GPU. 

Training seems to *almost* work (the models are restored and data seems to load fine), but when the model begins training, it fails with simply `Floating point exception`. Any idea what the cause might be?

Command:
```
python llava/train/train_mem.py \
    --model_name_or_path ./checkpoints/llama-vicuna-7b \
    --data_path /home/joshg/llava-cc3m-pretrain-595k/chat.json \
    --image_folder /home/joshg/llava-cc3m-pretrain-595k/img \
    --vision_tower openai/clip-vit-large-patch14 \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end \
    --bf16 True \
    --output_dir ./checkpoints/llava-7b-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2400 \
    --save_total_limit 1 \
    --learning_rate 2e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --report_to none
```

Log: 
There are no logs (unless the training logs somewhere I am not aware of?). The tail end of the output looks like:

```
[...]
You are using a model of type llama to instantiate a model of type llava. This is not supported for all configurations of models and can yield errors.
[...]
self_attn.v_proj.bias', 'text_model.encoder.layers.0.mlp.fc2.weight', 'text_model.encoder.layers.0.self_attn.q_proj.weight', 'text_model.embeddings.token_embedding.weight', 'text_model.encoder.layers.8.self_attn.k_proj.weight', 'text_model.encoder.layers.0.layer_norm2.weight', 'text_model.encoder.layers.7.self_attn.out_proj.weight', 'text_model.encoder.layers.3.mlp.fc1.bias', 'text_model.encoder.layers.10.layer_norm1.weight', 'text_model.encoder.layers.11.self_attn.v_proj.weight']
- This IS expected if you are initializing CLIPVisionModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CLIPVisionModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
WARNING:root:Loading data...
WARNING:root:Formatting inputs...Skip in lazy mode
  0%|                                                                 | 0/4651 [00:00<?, ?it/s]
Floating point exception
```

Additional details:
* Using Conda environment, set up following the steps in the README (no additional packages installed)
* Debian GNU/Linux 10 (buster) 
* CUDA Version: 11.6
* `transformers @ git+https://github.com/huggingface/transformers.git@cae78c46d658a8e496a815c2ee49b9b178fb9c9a`
* `torch==2.0.1`

**Comment by jpgard** [comment]
I ran the script using gdb (as described [here](https://discuss.pytorch.org/t/dealing-with-floating-point-exceptions/51882/2)) and it also outputs the following on failure:

```
Thread 1 "python" received signal SIGFPE, Arithmetic exception.
0x00007ff70c1b6141 in cudnn::backend::Tensor::finalize_internal() ()
   from /usr/local/cuda/lib64/libcudnn_cnn_infer.so.8
```

**Comment by ManuelFay** [comment]
also get the error when running in in non-distributed training

**Comment by haotian-liu** [comment]
Hi @ManuelFay and @jpgard , I have not encountered this before. Two things we may try is to see reduce the batch size to 1, and disable flash attention (using `train.py` instead of `train_mem.py`). If any of these work, we can have more insight on what is happening.

You may also try the latest code base using the scripts [here](https://github.com/haotian-liu/LLaVA/blob/main/scripts/pretrain.sh).

Please let me know if there are any updates that I can help with, thanks.

**Comment by ManuelFay** [comment]
yes, I managed to make it work by disabling flash attention and using torch 1.12 instead of 2+. Works with batch sizes of 8 or 16 in LoRA, so probably just a flash attention problem or cuda problem on the A100.

Thanks for the response, I'll try looking into it more in depth at some point !
Thanks for the great work !

**Comment by haotian-liu** [comment]
Glad to hear that you've made it work. Please feel free to re-open / open new issue if you encounter any other issues.
