### ISSUE TITLE
[Question] Asking for a simple script to get text and video features

### ISSUE THREAD

**Issue by ymartin-mw** [haotian-liu/LLaVA#257]
### Question

First of all - Amazing work on this one.

I'm a bit getting lost with the repo, may I request a simple few line script that does something like the following:
```python
model = CLIPViP("pretrain_clipvip_base_32.pt")
text_features = model.encode_text("This is a very cute cat")
video_features = model.encode_video("vid_file.mp4")
cosine(text_features, video_features)
```

[Extra] Preferably I wish to get the video features for a batch of mp4 files with different lengths

Thank you

**Comment by haotian-liu** [comment]
Hi, the description above seems not matching the designed purpose of LLaVA. It may be more suitable to look for something like CLIP for videos?

I am closing the issue right now, but please feel free to re-open if I misunderstood the request. Thanks!
