### ISSUE TITLE
[Question] How to run llava-13b/llava-7b locally

### ISSUE THREAD

**Issue by r3shma** [haotian-liu/LLaVA#259]
### Question

Hello,
Could you please help me on how to run the llava-13 model locally (like in your online demo)? I am currently able to only see the MPT lightning model option in the dropdown when I launch the Gradio demo. 

Your README has instructions on downloading the weights. Do I need to download and store the weights in any specific location in order to run inference with the llava-13b. Appreciate your help. Thanks.

**Comment by r3shma** [comment]
Also, can I use the weights from here: https://huggingface.co/decapoda-research/llama-13b-hf directly instead of using the deltas? How to install the model and run inference in this case?

**Comment by r3shma** [comment]
I realised we just need to launch another model worker after downloading the weights and applying the delta using this command: `python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000/ --port 40000 --worker http://localhost:40000/ --model-path /path/to/model/weights` . Thanks, closing this issue.

**Comment by r3shma** [comment]
Sorry @haotian-liu, I do have a follow up question. How to get both the models to show up in the dropdown?
I have launched both model workers, but I see only the LLaVA-13B-v1-1 in the gradio demo dropdown:
```
python3 -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000/ --port 40001 --worker http://localhost:40000/ --model-path liuhaotian/LLaVA-Lightning-MPT-7B-

python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000/ --port 40000 --worker http://localhost:40000/ --model-path ../llava_models/LLaVA-13B-v1-1
```
Appreciate any help.

**Comment by haotian-liu** [comment]
Hi @r3shma 

Sorry for the confusion. You need to change the port from 40000 to 40001.

Also, can you please help confirm if the [updated README](https://github.com/haotian-liu/LLaVA/tree/main#launch-a-model-worker) is clearer about launching multiple workers? And please let me know in any way you feel it can be improved. Thanks.

**Comment by r3shma** [comment]
Thanks a lot, everything is now working as expected. Thanks for the help and great work on this project. Updated README LGTM!
