### ISSUE TITLE
Time takes for each stage training

### ISSUE THREAD

**Issue by gordonhu608** [haotian-liu/LLaVA#26]
Hi, How long does it take to train for stage 1 and stage 2 on how many say A100 (40g) GPU. Thank you!

**Comment by haotian-liu** [comment]
Hi @gordonhu608 

We pretrain our model on CC3M-595K data on 8x A100s for around 5 hours. The instruction tuning of the initial release takes ~10 hours on the same machine using full 150K data. We also find using a smaller subset (even as small as, say 15k, which finishes within an hour) can achieve similar performance. We'll update details of these experiments later.
