### ISSUE TITLE
[Question] Question about the arguments in the training script

### ISSUE THREAD

**Issue by hyojinie** [haotian-liu/LLaVA#260]
### Question

Hi, 
Thanks for sharing your work. I have a few questions about some of the arguments used in the training script. 

- `DataArguments.sep_image_conv_front`: What does this parameter mean? I'd like to know details of why this option exists. 
- `TrainingArguments.force_fsdp`: What does this parameter do? I couldn't find where it is being used.

Thank you very much in advance!

**Comment by haotian-liu** [comment]
Hi, these are parameters used in earlier code versions, and now we move to DeepSpeed and thus removed the need of these. Thanks.
