### ISSUE TITLE
which version of vicuna weight (v0 or v1.1?) should be used

### ISSUE THREAD

**Issue by jpWang** [haotian-liu/LLaVA#27]
Thanks for your great work! 
In fine-tune command there is a 
--model_name_or_path /path/to/llama-vicuna-13b .
And I just want to ask that which version of vicuna weight (v0 or v1.1?) should be used?

**Comment by PhanTask** [comment]
> Hi, thank you for your interest in our work. We used Vicuna-v0 weights.
> 
> Note that when you are performing [weights conversion](https://github.com/haotian-liu/LLaVA#llava-13b), you should use LLaMA weights as the base weight instead of Vicuna weights.

Hi, thanks for the great work. A follow-up question: does it mean LLaVA's delta weights include Vicuna's delta weights? Which means, we do not need to first convert LLaMA to Vicuna, and we do not need to even download Vicuna's delta weight. Is this correct?

**Comment by haotian-liu** [comment]
@PhanTask You're right.  Our delta is computed by directly comparing with LLaMA.

**Comment by PhanTask** [comment]
Wow thanks for your prompt reply! Really appreciate your great work.
