### ISSUE TITLE
[Question] Running without flash-attn

### ISSUE THREAD

**Issue by TonyXuQAQ** [haotian-liu/LLaVA#275]
### Question

Hi, I wanna know if there is any way to run LLaVA **without** flash-attn. I ran into several issues with V100 GPUs, and I found that these issues are caused by fast-attn.

Thanks!

**Comment by haotian-liu** [comment]
Hi @TonyXuQAQ, you can run without flash-attention by replacing `train_mem.py` with `train.py` in your command. We'll add this tip into our documentation as well. Thanks!

**Comment by YerongLi** [comment]
on V100 I am still getting OOM error, https://github.com/haotian-liu/LLaVA/issues/290#issue-1815329831
