### ISSUE TITLE
[Question] How to conduct inference after finetuning using deepspeed + LoRA

### ISSUE THREAD

**Issue by yifannnwu** [haotian-liu/LLaVA#276]
### Question

Hi, thanks for this excellent work! 

After finetune using deepspeed + LoRA using officially provided script, the model was saved in ./checkpoints/deepspeed_llava-13b-v1.3-finetune_lora. When I tried to inference this model using run_llava.py, I encountered error ValueError: Unrecognized configuration class <class 'llava.model.llava.LlavaConfig'> to build an AutoTokenizer. I am wondering any other step I need to do to process the model after finetune to make it able to work? 

Thanks in advance for any help.

**Comment by YerongLi** [comment]
If you can run the training workflow, why not just looking into the training iterations.

**Comment by YerongLi** [comment]
How did you get the model file for this?
```
--model_name_or_path ./checkpoints/vicuna-$MODEL_VERSION-$WEIGHT_VERSION
```

**Comment by yifannnwu** [comment]
The latest code solved this issue.
