### ISSUE TITLE
where can i get the model LLaVA-13B-v0 in ./checkpoints/LLaVA-13B-v0?

### ISSUE THREAD

**Issue by haorunze** [haotian-liu/LLaVA#28]

**Comment by haotian-liu** [comment]
Hi, please follow the instructions here to download the delta weights and convert to the target weights.  We need this extra conversion step due to the LLaMA license, similar to Vicuna, Koala, etc.

https://github.com/haotian-liu/LLaVA#llava-weights

**Comment by haotian-liu** [comment]
Hi, I am closing this issue, due to the inactivity.  Hope your problem has been resolved.  If you have further concerns, please feel free to re-open or open a new issue.  Thanks!
