### ISSUE TITLE
Llama 2 integration

### ISSUE THREAD

**Issue by LukeBailey181** [haotian-liu/LLaVA#280]
### feature

Llama 2 was released today. Would be super cool to see this integrated as the language decoder to LLaVA as it used RLHF and appears to have great performance.

**Comment by JulianYocum** [comment]
This would be excellent!

**Comment by haotian-liu** [comment]
I am excited as well! We've updated our code base with the support for LLaMA-2, as well as some initial preview checkpoints on it :) Stay tuned for more checkpoints!

**Comment by LukeBailey181** [comment]
Amazing thank you! Are these previews weight deltas that we should apply to our own copies of the llama 2 weights using the same code in the repo for applying llama 1 weight deltas?

**Comment by haotian-liu** [comment]
@LukeBailey181 Sorry for the confusion. LLaMA-2 based checkpoints are released with merged weights, and you do not need to apply delta any more.

We've updated the docs in [MODEL ZOO](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md#model-zoo). Thanks!
