### ISSUE TITLE
[Question] How to input video?

### ISSUE THREAD

**Issue by RyanLiu112** [haotian-liu/LLaVA#285]
### Question

Thanks for the great work!

Can LLaVA take videos or multiple video frames (e.g., 4 frames) as inputs without the addition of temporal processing layers? I'm interested in using LLaVA to generate descriptions for videos and multiple images, but I'm unsure about how to implement this. Could you please provide some advice? I appreciate your help in advance.

**Comment by haotian-liu** [comment]
Hi @RyanLiu112 

Thank you for your interest. Currently LLaVA does not support processing videos yet, but I can imagine this would require pretraining and instruction tuning at least on some video clips.

You can potentially start from the pretrained LLaVA checkpoints and perform both pretraining and instruction tuning and see how it works.

**Comment by RyanLiu112** [comment]
Thanks for your response!
