### ISSUE TITLE
where is the llava_instruct_150k.json

### ISSUE THREAD

**Issue by yix-chen** [haotian-liu/LLaVA#29]
Hi, in ''download_data.sh'' we can only download ''complex_reasoning_77k.json  conversation_58k.json  detail_23k.json'', I wonder if we need to concat them to llava_instruct_150k.json?

**Comment by haotian-liu** [comment]
Thank you for pointing this out.  For convenience of the usage, I have uploaded concatenated version [llava_instruct_150k.json](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/blob/main/llava_instruct_150k.json) as well.

**Comment by haotian-liu** [comment]
Hi, I am closing this issue, due to the inactivity.  Hope your problem has been resolved.  If you have further concerns, please feel free to re-open or open a new issue.  Thanks!
