### ISSUE TITLE
[Question] 请问Multimodal Chatbot训练了几个epochs

### ISSUE THREAD

**Issue by bebory** [haotian-liu/LLaVA#297]

**Comment by haotian-liu** [comment]
Hi, we usually pretrain for 1 epoch, and finetune for 1 epoch for lightning, and 3 epoch for the models mentioned in the paper. We are exploring different schedules for different training techniques.

You can check out the detailed schedules, training datasets used for checkpoints in [MODEL ZOO](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md).

Thanks.
