### ISSUE TITLE
[Question] Incorrect inference with llama-2

### ISSUE THREAD

**Issue by TonyXuQAQ** [haotian-liu/LLaVA#298]
### Question

Hi authors, I recently tried with llama-2, and thanks for sharing the code to support llava with llama2.

1. I downloaded the llava-llama-2-13b-chat and llama-2-13b-chat. 
2. Then I convert llama-2-13b-chat to llama-2-13b-chat-hf.
3. I run the code to extract llava from llava-delta by
```
python3 -m llava.model.apply_delta \
    --base /path/to/llama-2-13b-chat-hf \
    --target /output/path/to/LLaVA-13B-llama2 \
    --delta liuhaotian/LLaVA-13b-llama2-lighting
```
4. Run inference code
```
python -m llava.eval.run_llava \
    --model-path /path/to/LLaVA-13B-llama2 \
    --image-file "https://llava-vl.github.io/static/images/view.jpg" \
    --query "What are the things I should be cautious about when I visit here?"
```

However, the output is just meaningless characters. And I noticed that ```llava.eval.run_llava.py``` has been updated, and ```args``` has been changed from ```model-name``` to ```model-path``` and ```model-base```. But these is no explanation and examples about ```model-path``` and ```model-base```.

Could you please tell me if  I have the correct implementation steps, and could you please add new examples about the inference code. Thanks in advance.

**Comment by haotian-liu** [comment]
Hi, apologies for the confusion. Starting from the latest checkpoints, we directly release the original checkpoints instead of the delta weights. You can directly use our checkpoints, without doing the conversion.

We'll fix the README asap.
