### ISSUE TITLE
assert input_embeddings.shape == embed_tokens_weight.shape

### ISSUE THREAD

**Issue by yix-chen** [haotian-liu/LLaVA#30]
Error message:
File "/home/ubuntu/project/llava/llava/train/train.py", line 479, in train
assert input_embeddings.shape == embed_tokens_weight.shape
AssertionError

I download the projector weights from https://huggingface.co/liuhaotian/LLaVA-13b-pretrain-projector-v0, and use vicuna-13b as base model.

**Comment by haotian-liu** [comment]
Hi, please pull the latest code, as it is updated to only load the additional embeddings this morning, in compliance to the LLaMA license.  Thanks!

https://github.com/haotian-liu/LLaVA/blob/main/llava/train/train.py#L479-L483

**Comment by haotian-liu** [comment]
Hi, I am closing this issue, due to the inactivity.  Hope your problem has been resolved.  If you have further concerns, please feel free to re-open or open a new issue.  Thanks!
