### ISSUE TITLE
error when running llava-llama-2-13b-chat-lightning-preview model in CLI

### ISSUE THREAD

**Issue by r3shma** [haotian-liu/LLaVA#309]
### Question

Hi @haotian-liu 

I was trying to run the llava-llama-2-13b-chat-lightning-preview model thorugh the CLI but got the following error:

raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/llava_models/llava-llama-2-13b-chat-lightning-preview'. Use `repo_type` argument if needed.

I am not sure what changes are needed to the eval script to make this work. Appreciate any help!

**Comment by haotian-liu** [comment]
Hi @r3shma this error is very likely due to that `/home/llava_models/llava-llama-2-13b-chat-lightning-preview` does not exist on disk. Please check if you are using the correct path, or you can load from huggingface directly by using `liuhaotian/llava-llama-2-13b-chat-lightning-preview`.

**Comment by r3shma** [comment]
Thank you!
