### ISSUE TITLE
How to reproduce the evaluation of science qa score.

### ISSUE THREAD

**Issue by gordonhu608** [haotian-liu/LLaVA#31]
Hi, when I'm loading the question.jsonl in eval model vqa science.py. You directly implemented it as json.load() and I'm receiving a error. However since it's a json line file, shouldn't you do [json.load(line) for line in file]

Anyway, my question is could you provide more information on how to reproduce your science qa score. I encountered many problems when reproducing it. Simpling specifying which file to load for each parser argument also helps a lot!  The following link you provided is also a 404 error. Thanks for your efforts ahead for making your work reproducible. 

![image](https://user-images.githubusercontent.com/24793015/233563798-f833b5a5-8a02-43ca-b7fd-2e6493b0f258.png)

**Comment by haotian-liu** [comment]
Hi @gordonhu608
Thank you for your interest in our work!

We have converted the weights for release, and also updated instructions: https://github.com/haotian-liu/LLaVA#scienceqa.

Please let me know if you have further questions.

**Comment by haotian-liu** [comment]
Hi, I am closing this issue, due to the inactivity.  Hope your problem has been resolved.  If you have further concerns, please feel free to re-open or open a new issue.  Thanks!
