### ISSUE TITLE
[Feature request] Git auto release with CD

### ISSUE THREAD

**Issue by Floodnut** [haotian-liu/LLaVA#319]
### feature

I want git pipeline about release automation.
Can I add workflows about that? I want to contribute to this project.

Or, is there a reason not to automate?

**Comment by haotian-liu** [comment]
Hi @Floodnut 

Thank you for bringing this up and for offering this. I am not very familiar with this. Can you please explain what is the usual process of Git auto release using CD and what kind of benefits it can bring? How would it affect our current workflow? Thanks!

**Comment by Floodnut** [comment]
> Hi @Floodnut
> 
> Thank you for bringing this up and for offering this. I am not very familiar with this. Can you please explain what is the usual process of Git auto release using CD and what kind of benefits it can bring? How would it affect our current workflow? Thanks!

Thank you for your reply about this suggestion @haotian-liu !

Github has git release and tag system like this.
you can manage your project versions explicitly.
<img width="466" alt="example_of_docker_cli" src="https://github.com/haotian-liu/LLaVA/assets/15941204/872326ac-cf1f-473c-91dd-194631d2e384">

If you need to release and you feel hassle that create release manually, you can automate to create release.
It is simple system.
- CD workflow catch `merge` commit and extract version tag like this. (v1.0.0)
- Then, make a release with extracted version tag.

However, if you need a procedure  to check manually with minimal safety guards to create a release, this may not be necessary.

**Comment by haotian-liu** [comment]
Thanks for the info! The explanation makes a lot of sense. For now, I feel maybe manual tagging and release works better for me, as I think it will be beneficial to document each changes both in CHANGELOG as well as the release message, for people to be clear about each release. Do you have any other opinions?  Thanks!

**Comment by Floodnut** [comment]
> Thanks for the info! The explanation makes a lot of sense. For now, I feel maybe manual tagging and release works better for me, as I think it will be beneficial to document each changes both in CHANGELOG as well as the release message, for people to be clear about each release. Do you have any other opinions? Thanks!

That's cool! Thank you for your interest. Thanks!
