### ISSUE TITLE
[Feature request] Multiple runs for CLI inference example

### ISSUE THREAD

**Issue by shileims** [haotian-liu/LLaVA#324]
### feature

Multiple runs are really helpful in understanding how the model works.

**Comment by haotian-liu** [comment]
Hi, can you elaborate the request more? Do you mean output three different answers for the same request?
Thanks.

**Comment by shileims** [comment]
Hi @haotian-liu ,
    Thanks for your reply.
    I can output multiple questions to get final answers.
   For example, I have two questions. (1). What does the image include? (2). Can you tell me what is the color of the object in the image? I hope to input the first question into the model to get the first answer. And then input the second question to get the final answer. Through the web demo you provided, I tried and designed multiple steps prompts to get what I want. But the code is difficult to extract. In other words, Would you provide a Python script for the web demo to input multiple questions. Not a single run demo.

**Comment by haotian-liu** [comment]
Hi @shileims, I get your point now. We have supported CLI inference with multiple turn conversations, but it seems that I have never officially document it yet.

Just updated that in [readme](https://github.com/haotian-liu/LLaVA#cli-inference), and please try it out, and also feel free to follow up if there are issues with the current cli interface. Thanks.

**Comment by shileims** [comment]
Hi @haotian-liu , really appreciate your reply. I am trying it now. Thank you so much!
