### ISSUE TITLE
[Question] Encoding speed enhanced

### ISSUE THREAD

**Issue by SinanAkkoyun** [haotian-liu/LLaVA#327]
### Question

Hi! Thank you for all the groundbreaking work and for sharing it.

What are current bottlenecks of encoding an image? I am working on a real-time LlaVA and need to cut down encoding speed to as low as possible

I would be very grateful for a high level assession of bottlenecks and what could be improved

**Comment by haotian-liu** [comment]
@SinanAkkoyun 

Thanks for your interest and for bringing up this interesting topic. To my understanding, LLaVA can start outputing tokens very soon after receiving the image, and the inference time for image encoding should be minimal, while the text decoding will take a long time.

Can you elaborate a bit more on why you feel that the image encoding may be the bottleneck? And how long do you expect the decoding sequence be?

Thanks.

**Comment by SinanAkkoyun** [comment]
> Thanks for your interest and for bringing up this interesting topic. To my understanding, LLaVA can start outputing tokens very soon after receiving the image, and the inference time for image encoding should be minimal, while the text decoding will take a long time.

Ah okay, when I experimented with it when it came out, the CLIP image encoding took around a second

> Can you elaborate a bit more on why you feel that the image encoding may be the bottleneck?

IT was just like that when I tested it, token generation of the 7B and 13B models are very fast (I will finetune a 3B model for even faster inference)

> And how long do you expect the decoding sequence be?

The decoding sequence will be a couple of tokens only, at max 10 tokens

Thank you very much for your help and interest in my problem!

**Comment by SinanAkkoyun** [comment]
Oh, and the intention behind the speedup is that I also want to supply time coherent sequences

**Comment by haotian-liu** [comment]
I see. For this case, maybe it will be a good idea to try to optimize the vision encoder as well.

Several possibilities includes:

(1) quantize CLIP, but I am not very familiar with the literature there;
(2) use a smaller CLIP backbone. We support train with different vision backbones, and if you want to try with different CLIP backbones, it is as simple as change `--vision_tower` in the command line to the correct one (e.g. CLIP ViT-B/32: [openai/clip-vit-base-patch32](https://huggingface.co/openai/clip-vit-base-patch32). Note that there may be performance degradation when you switch to a smaller backbone. It should also support OpenCLIP checkpoints as well. You may also port your own checkpoints following [this script](https://github.com/haotian-liu/LLaVA/blob/main/llava/model/multimodal_encoder/clip_encoder.py).

In any case, I would suggest benchmarking the models yourself, and make sure that we are dealing with the real bottleneck. Thanks!

**Comment by SinanAkkoyun** [comment]
Thank you very much! I will definitely look into your suggested approaches.
I have a question not regarding inference but training of the encoder, I want to finetune a test CLIP model on ingame rendered footage. I am aware of the contrastive text training of CLIP but I wanted to ask is there a way to enhance spatial 3d understanding of the images in some way?

Thank you very much

**Comment by haotian-liu** [comment]
Hi @SinanAkkoyun 

I do not have direct experiments on that, but my feeling is that a few instruction tuning on this may help a lot on the performance of this specific task. You can try creating some simple instruction tuning dataset based on existing ones (it may not even need to be some output from ChatGPT), and we can get a sense of how it performs before and after finetuning on these data.

**Comment by SinanAkkoyun** [comment]
Hi @haotian-liu 
Thank you very much for the answer! I will definitely try to synthesize a 3D spatial finetuning dataset (similar to the microsoft bounding box paper but with actual 3D data from renderings)

I also wanted to take the opportunity to congratulate you on all your work you have done, also the MedLLaVa, such great results!

Is there a way to finetune the CLIP encoder itself? Given the text contrast nature I am not so sure if there even will be enough spatial information encoded

I am looking very forward to your response, thank you

**Comment by haotian-liu** [comment]
I have a similar intuition here. But if the data is clean enough, there is still some possibility that it can be learnt. Anyway, maybe the easiest would be to let the LLM learn instead of hoping that the spatial relationship will be encoded within the CLIP encoder?

**Comment by SinanAkkoyun** [comment]
Ok, I will build the dataset and test for it, thank you for your intuition and inputs, that means a lot to me!
