### ISSUE TITLE
May I know the effect of filtering CC3M? If I use all CC3M for stage1 pre-training, will the result be good or not?

### ISSUE THREAD

**Issue by qibao77** [haotian-liu/LLaVA#33]

**Comment by haotian-liu** [comment]
Hi @qibao77, thank you for the interest in our work.

The main reason for filtering CC3M is for:
(1) creating a more balanced pretraining dataset, as shown in our paper and project page;
(2) to save pretraining cost.

We have some that our method is pretty robust and generalizable w.r.t. the pretraining dataset choice, so using the full CC3M set probably would not hurt.

We are working on a comparison with different pretraining set currently and will provide an update very soon.

**Comment by haotian-liu** [comment]
Hi, I am closing this issue, due to the inactivity.  Hope your problem has been resolved.  If you have further concerns, please feel free to re-open or open a new issue.  Thanks!
