### ISSUE TITLE
[Feature request] Distributed inference

### ISSUE THREAD

**Issue by shileims** [haotian-liu/LLaVA#331]
### feature

Hi Author,
    Thanks for your excellent work.
    I would like to perform distributed inference in one machine with multiple gpu cards. Is it possible?

**Comment by haotian-liu** [comment]
Hi, you may check out the batch inferencing docs in ScienceQA: https://github.com/haotian-liu/LLaVA/blob/main/docs/ScienceQA.md

We may support the batch inference later, but currently we have a lot other TODOs that need us take care of..

**Comment by shileims** [comment]
Hi @haotian-liu ,
    Thanks for your reply. Yes, definitely your plan for future work is more valuable. I will check the ScienceQA part.
