### ISSUE TITLE
[Feature request] Input bounding box and output bounding box for image understanding

### ISSUE THREAD

**Issue by shileims** [haotian-liu/LLaVA#333]
### feature

Hi Author,
     Since this is a really good work for image understanding based on LLM, I would like to ask do you have plan to extend the functionality of image understanding for inputting bounding box and outputting bounding box. Thanks

**Comment by haotian-liu** [comment]
Hi, this is partially supported in the latest llava-1.5. Please check out the data mixture here: https://github.com/haotian-liu/LLaVA#visual-instruction-tuning, or for our paper for more info. Thank you.
