### ISSUE TITLE
[Usage] load the checkpoint of llava-llama-2

### ISSUE THREAD

**Issue by Espere-1119-Song** [haotian-liu/LLaVA#337]
### When did you clone our code?

I cloned the code base before 5/1/23, but have pulled the latest code base

### Describe the issue

Issue: When I load the checkpoint of llava-llama-2 in model zoo, I meet the error as follows:

Log: 
```
You are using a model of type llava to instantiate a model of type llava_mpt. This is not supported for all configurations of models and can yield errors.
*** OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ckpt/llava.

```
![屏幕截图 2023-08-01 225311](https://github.com/haotian-liu/LLaVA/assets/77435739/9af72a86-6fe6-4bb0-a489-a7dff7df0d5e)

**Comment by haotian-liu** [comment]
Hi, it is strange that it goes to the MPT. Can you provide the full command you used? Thanks.

**Comment by gnimyang** [comment]
when I using follow command, I meet a problem.
from transformers import pipeline
pipe = pipeline("text-generation", model="liuhaotian/llava-v1-0719-336px-lora-vicuna-13b-v1.3")
![image](https://github.com/haotian-liu/LLaVA/assets/130719420/dbdf435f-7c49-4499-b780-55b4b03d6c16)

**Comment by gnimyang** [comment]
I am a new starter, is there any other ways to download the pre-trained model？
Is it possible to check the model has already been downloaded correctly to the local manually, where to change the parameter to load the model locally? Can you show me the folder structure?

**Comment by haotian-liu** [comment]
Hi, for CLI inference, please follow our instructions [here](https://github.com/haotian-liu/LLaVA#cli-inference).

**Comment by jeferay** [comment]
I faced the same issue when I was using the local parameters (cloned from huggingface).
<img width="1210" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/55432916/c8892500-84c5-4365-8792-7ceaabdc0ffc">

**Comment by haotian-liu** [comment]
Maybe check if your folder contains the proper index.json file? It should *NOT* contain `pytorch_model.bin` actually as it is sharded.

![image](https://github.com/haotian-liu/LLaVA/assets/6631389/42eab07a-1eb2-4545-b988-8e26598f4097)

**Comment by jeferay** [comment]
Oops! Thanks for this. My bad. It should work now.
