### ISSUE TITLE
some urls in CC-3M Pretrain 595K metadata.json are broken

### ISSUE THREAD

**Issue by yix-chen** [haotian-liu/LLaVA#34]
some urls in CC-3M Pretrain 595K metadata.json are broken, could you please provide the downloaded images?

**Comment by haotian-liu** [comment]
Hi @yix-chen can you provide what's the percentage of data not available?  I will need to check to see if I can provide these images directly.  If the percentage is not high (~10%), the performance shall be similar.

**Comment by jianantian** [comment]
same problem, some url are broken, i only get ~72% readable image out of total 595375 data from metadata.json.

**Comment by yix-chen** [comment]
Hi @haotian-liu , same results as @jianantian , appreciate it if you could provide these images.

**Comment by haotian-liu** [comment]
Hi @jianantian @yix-chen 

Thank you for your feedback!  We have uploaded the images to huggingface.  Please see [here](https://github.com/haotian-liu/LLaVA#pretraining-dataset) and the disclaimer below.  Thanks!

Upon the request from the community, as ~15% images of the original CC-3M dataset are no longer accessible, we upload images.zip for better reproducing our work in research community. It should not be used for any other purpose. The use of these images must comply with the CC-3M license. This may be taken down when requested by the original CC-3M dataset owner or owners of the referenced images.

**Comment by haotian-liu** [comment]
Hi, I am closing this issue, due to the inactivity.  Hope your problem has been resolved.  If you have further concerns, please feel free to re-open or open a new issue.  Thanks!
