### ISSUE TITLE
[Usage] the poetry install cannot work in this project, is the pyproject.toml file erro?

### ISSUE THREAD

**Issue by gnimyang** [haotian-liu/LLaVA#340]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

poetry install cannot work in this project, is the pyproject.toml file error?

[tool.poetry] section not found in /public/home/mike/LLaVA/pyproject.toml

**Comment by haotian-liu** [comment]
Hi, what is your environment (OS, Python version), and if you followed our instructions [here](https://github.com/haotian-liu/LLaVA#install) to create the conda environment?

I have installed the package from scratch (an empty conda env) yesterday, and it works for me. Thanks.

**Comment by gnimyang** [comment]
I try it on my windows and linux, both fail to work, I using poetry install command. The pyproject.toml file has dependencies, but I cannot make it work by using "poetry install command"
![image](https://github.com/haotian-liu/LLaVA/assets/130719420/a2113af0-515e-4d50-8bc6-3e9cdf7889ad)
![图片_20230803194020](https://github.com/haotian-liu/LLaVA/assets/130719420/e7dea296-d200-41e8-ac07-12ed208c2cdf)

**Comment by gnimyang** [comment]
![image](https://github.com/haotian-liu/LLaVA/assets/130719420/025d740d-541e-4a2e-a132-23b0f04457fc)
![image](https://github.com/haotian-liu/LLaVA/assets/130719420/d71dac29-0b63-4edf-a079-02cf28795f4f)

**Comment by gnimyang** [comment]
wow, it is work! thanks, so it is no need to use "poetry install" command. OK, thanks

**Comment by gnimyang** [comment]
thanks!

**Comment by haotian-liu** [comment]
Please feel free to reopen the issue if you encounter any other related issues. thanks.
