### ISSUE TITLE
[Usage] Inference issue with LLaMA-2-13B-Chat 

### ISSUE THREAD

**Issue by rohan598** [haotian-liu/LLaVA#343]
### When did you clone our code?

I cloned the code base after 5/1/23

### Describe the issue

**Issue:** 
Unable to perform inference using run_llava. Trying to run inference for llava-llama-2-13b-chat.
Model Weights taken from [hugging face](https://huggingface.co/liuhaotian/llava-llama-2-13b-chat-lightning-preview/tree/main). 
Projector weights taken from [hugging face](https://huggingface.co/liuhaotian/llava-pretrain-llama-2-13b-chat/tree/main) (newer link)

**Command:**
```
python -m llava.eval.run_llava --model-path /fullpathto/llava-llama-2-13b-chat-lightning-preview --image-file /fullpathto/tmp.png --query "Describe this file in detail" 
```

**System Details:**
OS: 20.04.6 LTS (Focal Fossa)
GPU: A6000 Nvidia
CPU: AMD x86_64
Log: 
```
Screenshot of logs attached
```

**Screenshots:**
<img width="567" alt="issue-ss" src="https://github.com/haotian-liu/LLaVA/assets/25100847/5b7c4729-04dc-4742-bbe1-7cf7ae44952c">

**Comment by haotian-liu** [comment]
Hi @rohan598 

I forgot to update the prompt template in `run_llava.py`, and just fix that in https://github.com/haotian-liu/LLaVA/commit/4f801cd99fe2006e95d9946a36710ce125075484. Although strangely, it works for me even without this fix (despite a slight degradation of the quality of the response).

Can you try exactly the same image/prompt that I used to see if the problem still persists?

```
python -m llava.eval.run_llava --model-path ./checkpoints/llava-llama-2-13b-chat-lightning-preview --image-file https://llava-vl.github.io/static/images/view.jpg --query "What are the things I should be cautious about when I visit here"
```

Also, we've recently updated our interactive cli chat [here](https://github.com/haotian-liu/LLaVA#cli-inference), in case you are interested in this as well.

**Comment by rohan598** [comment]
Thank you this change worked!
