### ISSUE TITLE
[Question] The ability of few-shot in-context learning

### ISSUE THREAD

**Issue by yongliang-wu** [haotian-liu/LLaVA#344]
### Question

Dear authors, LLaVA is an amazing model. But I'm curious about whether it can do "in-context-learning". I want to do some exploration on it.

**Comment by haotian-liu** [comment]
Currently LLaVA is not explicitly finetuned for performing ICL, and the benefit of Multimodal ICL is recently starting to be started :) Looking forward to your exploration results, thanks!
