### ISSUE TITLE
[Question] Batch inference?

### ISSUE THREAD

**Issue by Jinyi6** [haotian-liu/LLaVA#345]
### Question

Hi,

Great job! I found that currently only inference with batch size equal to 1 is supported. How can I implement inference with batch size not equal to 1? What are the code details that are worth noting when I am modifying code? Thank you very much!

![image](https://github.com/haotian-liu/LLaVA/assets/77571182/2d6a42a2-3f74-45c9-a8ca-0f54ac247e45)

**Comment by k1e3v1i4n** [comment]
logits_processor is what u need

**Comment by haotian-liu** [comment]
Hi, thank you, and I am trying to work on an efficient batch inference. Closing this and consolidating the discussion to https://github.com/haotian-liu/LLaVA/issues/754. Thanks.
