### ISSUE TITLE
is there any different between lora-vicuna-13b-v1.3 and lora-merge-vicuna-13b-v1.3

### ISSUE THREAD

**Issue by gnimyang** [haotian-liu/LLaVA#349]
### Question

I don't really understand why you using merge to express those model difference, and the merge version is much smaller than the normal, which method you used to compress the model size?

**Comment by haotian-liu** [comment]
LoRA merge is by merging the LoRA weights to the base checkpoint, so it will be same size as the Vicuna checkpoints.

LoRA is the adapter weights, which is much smaller than the LoRA weights.

You can check out the explanation of LoRA from Hugging Face here: https://huggingface.co/docs/diffusers/training/lora
