### ISSUE TITLE
Projector weights of LLaVA after the Instruction Tuning 

### ISSUE THREAD

**Issue by FuxiaoLiu** [haotian-liu/LLaVA#352]
### Question

Thanks for your amazing work! I want to fine-tune LLaVA based on the checkpoint(projector weights) after the instruction tuning on llava_instruct_150k.json. However, it seems that there are only projector weights from the first pretraining stage. Is it possible to get the projector weights after the instruction tuning? Thanks!

**Comment by haotian-liu** [comment]
Hi, you may extract the projector weights manually using [this now-deleted script](https://github.com/haotian-liu/LLaVA/blob/36b28148223f04ad0d8e54ca7764f1fa31216eb6/scripts/extract_mm_projector.py), but it may give you unexpected behavior, as we finetune the LLM, and using incompatible projector weights and LLMs can result in bad/garbled outputs.
