### ISSUE TITLE
[Question] Can't reproduce the result of LLaVA7B

### ISSUE THREAD

**Issue by FuxiaoLiu** [haotian-liu/LLaVA#353]
### Question

I finetune llava7b on v100, 8GPU with the following script (llava_instruct_150k.json):

deepspeed ./llava/train/train.py \
    --deepspeed zero3_offload.json\
    --model_name_or_path /apdcephfs_cq3/share_1603164/user/fuxiaoliu/vicuna-7b-v1.3\
    --version v1 \
    --data_path /llava_instruct_150k.json \
    --image_folder /apdcephfs_cq3/share_1603164/user/fuxiaoliu/llava_dataset/train2017 \
    --vision_tower /apdcephfs_cq3/share_1603164/user/fuxiaoliu/llava_dataset/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter /apdcephfs_cq3/share_1603164/user/fuxiaoliu/projector/mm_projector.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False\
    --fp16 True \
    --output_dir /apdcephfs_cq2/share_1603164/user/fuxiaoliu/checkpoints_llava/llava-17b-finetune_llava \
    --num_train_epochs 3 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 500 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \

The projector is from here:
<img width="1022" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/60458715/8aae726d-b675-4026-8abd-a2afd8ffbc0d">

My output model weight looks like this:
<img width="379" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/60458715/047ef812-adcb-4fb0-aab9-53275eff2cb5">

I try to load the model weight in the web demo, and try the following questions:
<img width="820" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/60458715/204b3b2e-dfb1-4e70-98f3-3da8cb93c1c0">

It seems that the answer doesn't follow the instruction.

However, when I don't use the image and directly ask about the question:
<img width="526" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/60458715/b3c4d832-f7cb-45dd-b608-c8c3872816c0">

It follows the instructions. Do you have any ideas?

**Comment by haotian-liu** [comment]
Hi Fuxiao,

I have not trained model with both FP16 and zero3_offload. I am not sure if there are some issues with this specific configuration, but the commands you are using generally looks good to me.

I tried to train a lightning version (80k+1epoch, FP16, zero3 w/o offload) this morning, and it seems to be working fine. I have attached the command I used and the log below. Unfortunately I do not have the resource to run zero3 offload this week, as this somehow will cause all other processes on our lab machine to halt..

You may try running with the Lightning data (which is quicker and easier to verify).

Wandb: https://api.wandb.ai/links/lht/jjsx93kz

```
llava/train/train_mem.py --local_rank=0 --deepspeed dev_scripts/ds_zero3.json --model_name_or_path ./checkpoints/vicuna-7b-v1-3 --version v1 --data_path ./playground/data/llava_instruct/conv_reason_no_overlap_80k.json --image_folder /nobackup/haotian/datasets/coco/train2017 --vision_tower openai/clip-vit-large-patch14 --pretrain_mm_mlp_adapter ./checkpoints/ds_llava-vicuna-7b-v1-3-pretrain_blip558k_plain/mm_projector.bin --mm_vision_select_layer -2 --mm_use_im_start_end False --mm_use_im_patch_token False --bf16 False --fp16 True --output_dir ./checkpoints/ds_llava-vicuna-7b-v1-3-pretrain_blip558k_plain-finetune_80k_1e_fp16 --num_train_epochs 1 --per_device_train_batch_size 16 --per_device_eval_batch_size 4 --gradient_accumulation_steps 1 --evaluation_strategy no --save_strategy steps --save_steps 50000 --save_total_limit 1 --learning_rate 2e-5 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 1 --tf32 True --model_max_length 4096 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to wandb
```

```
md5sum ds_llava-vicuna-7b-v1-3-pretrain_blip558k_plain/mm_projector.bin
c96e816e8a1ae5f730fff68f21a00909  ds_llava-vicuna-7b-v1-3-pretrain_blip558k_plain/mm_projector.bin
```
