### ISSUE TITLE
[Discussion] Llava on a Multimodal Leaderboard?

### ISSUE THREAD

**Issue by chigkim** [haotian-liu/LLaVA#354]
### Discussion

@haotian-liu could you submit Llava-Llama-2 on the leader board below when it's officially out?
https://github.com/BradyFU/Awesome-Multimodal-Large-Language-Models/tree/Evaluation
Hopefully it scores better.

**Comment by haotian-liu** [comment]
LLaVA-1.5 is now on the leaderboard and SoTA on more :)
