### ISSUE TITLE
[Question] Readme vs Script for per_device_train_batch_size and increase the gradient_accumulation_steps

### ISSUE THREAD

**Issue by chigkim** [haotian-liu/LLaVA#360]
### Question

According to Readme, it sounds like Global Batch Size (per_device_train_batch_size * gradient_accumulation_steps) should be 128.
However, both From scripts/pretrain.sh and scripts/finetune.sh have --per_device_train_batch_size 16 --gradient_accumulation_steps 1.
That sounds like Global Batch Size is 16, not 128?
Which is correct?
What about finetune, is Global Batch Size the same?
Also, in order to train with fewer gpus, when you you reduce per_device_train_batch_size by x amount, do you just multiply gradient_accumulation_steps by x?
If we take the scripts (--per_device_train_batch_size 16 --gradient_accumulation_steps 1) as an example, do you divide per_device_train_batch_size/4 and multiply gradient_accumulation_steps*4? Then you replace with --per_device_train_batch_size 4 --gradient_accumulation_steps 4.
Lastly, I think it would be clearer if we had different documentation files (one for original paper and one for new).
Thanks!

**Comment by haotian-liu** [comment]
Just corrected this error in the README, global batch size should be: per_device_train_batch_size x gradient_accumulation_steps x **num_gpus**.

We used 8 GPUs in pretraining / finetuning, so the global batch size is 16x1x8=128.

> Lastly, I think it would be clearer if we had different documentation files (one for original paper and one for new).

Great suggestion. We'll add this later. Thanks.

**Comment by chigkim** [comment]
Thanks for the info!
global batch size  = per_device_train_batch_size x gradient_accumulation_steps x num_gpus
That makes sense. Could you clarify one more thing?
Readme said:
"You may run this with a single A100 GPU with the following code.
Pretrain: LLaVA-13B, 1x A100 (80G). Time: ~33 hours."
python llava/train/train_mem.py \
  --per_device_train_batch_size 16
  --gradient_accumulation_steps 8
Does the per_device_train_batch_size  stays the same as 16? Readme said: "To train on fewer GPUs, you can reduce the per_device_train_batch_size and increase the gradient_accumulation_steps accordingly."
On a related note, 1x A100 80gb only works for pretraining, not finetuning?
I asked about using 1x a100 80gb for finetuning on another discussion.
https://github.com/haotian-liu/LLaVA/discussions/356

**Comment by haotian-liu** [comment]
> "You may run this with a single A100 GPU with the following code.
> Pretrain: LLaVA-13B, 1x A100 (80G). Time: ~33 hours."
> python llava/train/train_mem.py
> --per_device_train_batch_size 16
> --gradient_accumulation_steps 8
> Does the per_device_train_batch_size stays the same as 16? Readme said: "To train on fewer GPUs, you can reduce the per_device_train_batch_size and increase the gradient_accumulation_steps accordingly."

Yes, as 16x8x1=128

> On a related note, 1x A100 80gb only works for pretraining, not finetuning?
Yes. You need LoRA/QLoRA for finetuning on a single A100.

**Comment by chigkim** [comment]
Thanks so much!
Then should the readme say "reduce the per_device_train_batch_size *or* increase the gradient_accumulation_steps," not "reduce the per_device_train_batch_size *and* increase the gradient_accumulation_steps?"
I was thinking I had to both decrease and increase like 4 (per_device_train_batch_size) * 32 (gradient_accumulation_steps) *1 (ngpu). :)

**Comment by chigkim** [comment]
Huge thanks @haotian-liu for answering all my questions!
I finally had a chance to score renting 8x A100 80gb gpus, and I successfully finetuned llama-2-13b.
Also I tried with --per_device_train_batch_size 8 * --gradient_accumulation_steps 4 * 4 a100 80gb gpus. It gave me a warning about clearing memory once in a while, but it finished the process, and the output was usable.

**Comment by HashmatShadab** [comment]
> Huge thanks @haotian-liu for answering all my questions! I finally had a chance to score renting 8x A100 80gb gpus, and I successfully finetuned llama-2-13b. Also I tried with --per_device_train_batch_size 8 * --gradient_accumulation_steps 4 * 4 a100 80gb gpus. It gave me a warning about clearing memory once in a while, but it finished the process, and the output was usable.

Hi, did you face out of memory issues with using batch of 16 with 4 A100 80 GB?
