### ISSUE TITLE
[Question] Using 8bit and 4bit quantization is much slower than non-quantization model

### ISSUE THREAD

**Issue by TangsengT** [haotian-liu/LLaVA#366]
### Question

Hi, 

When I use **run_llava.py** , I set the argument in the load function:

`load_pretrained_model(args.model_path, args.model_base, model_name,
                                                                           load_8bit=args.load_8bit,
                                                                           load_4bit=args.load_4bit)`
to use the quantization inference, but the inference speed is much slower than model before using quantization.
I use the same image and same prompt, and the speed downs to half of the original inference speed using 8bit quantization.
And compared to original inference speed, using 4bit quantization shows nearly the same inference speed without any improvement.

To find what the problem is, I take a look to my memory usage and it truly decreases using quantization.

Could you give me some ideas for this question?

Thanks a lot!

**Comment by haotian-liu** [comment]
The 4-bit should be faster with the latest bnb update. 8-bit is still slower for me. I am observing similar things for LLMs like Vicuna, so maybe we cannot do much.

Please let me know if you find that some code with LLMs that are actually faster with 8-bit, and I'd be happy to look into it. Thanks.

**Comment by forever208** [comment]
same here, in A100, the speed is: 
not using 4-bit or 8-bit > using 4-bit > using 8-bit
@haotian-liu may I ask that, how much would this 4-bit 8-bit quantification affect the performance according to your experience?

**Comment by Changlin-Lee** [comment]
Same performance on A6000

> same here, in A100, the speed is: `not using 4-bit or 8-bit` > `using 4-bit` > `using 8-bit` @haotian-liu may I ask that, how much would this 4-bit 8-bit quantification affect the performance according to your experience?
