### ISSUE TITLE
[Question] Llama-2 specify 2048 or 4096 for max_position_embeddings and model_max_length?

### ISSUE THREAD

**Issue by chigkim** [haotian-liu/LLaVA#369]
### Question

Llama-2 has increased 4096 context size compare to 2048 for the original Llama.
Should I change 2048 to 4096 for max_position_embeddings in config.json (hf model format) and --model_max_length in finetune.sh?
Or, should I keep it 2048?

**Comment by haotian-liu** [comment]
2048 for training as most data falls into this range, and it may cause OOM if the seq is too long. 4096 for inference is fine if you want longer sequences.

**Comment by chigkim** [comment]
Thanks!
