### ISSUE TITLE
[Discussion] Dead project is dead on Windows?

### ISSUE THREAD

**Issue by DarkAlchy** [haotian-liu/LLaVA#380]
### Discussion

Seems Deepspeed is just not happening on a modern Windows machine with a modern GPUas CUDA 11.1?  Seriously?  

Is there any way to get this to work without deepspeed as the pip install -e . dies on the installation part for deepspeed?

**Comment by DarkAlchy** [comment]
I worked around this error as the -e , is totally broken, but I made it all the way to the model for it to bomb out.  Having to open three conda terminals is a bit odd and no dice.  Can't find a single llm for images that works on Windows so time to toss in the towel.

**Comment by haotian-liu** [comment]
Please check the latest doc for Windows. I tested on my Windows 11 PC and it works now for 16-bit inference. Quantization will be supported later.

https://github.com/haotian-liu/LLaVA/blob/main/docs/Windows.md
