### ISSUE TITLE
[Question] Why "PROMPT_VERSION=plain" is used for both llama-2 and vicuna-v1.3 in the pretraining script ?

### ISSUE THREAD

**Issue by dingning97** [haotian-liu/LLaVA#385]
### Question

I noticed that "PROMPT_VERSION=plain" is used for both llama-2 and vicuna-v1.3 in the pretraining script.
Why not using "PROMPT_VERSION=v1" for vicuna-v1.3 and "PROMPT_VERSION=llava_llama_2" for llama-2 in the pretraining script? While the finetuning script does so...

**Comment by daiqing98** [comment]
Have you solved the issue? I am using vicuna-13b-v1.5

**Comment by haotian-liu** [comment]
We simplified the pretraining prompts by removing additional instructions like Describe the image details, which we find to allow the zero-shot inference and can slightly improve the training speed.

https://github.com/haotian-liu/LLaVA/releases/tag/v1.0.1
