### ISSUE TITLE
[Question] How to define the model_name_or_path in finetuen.sh

### ISSUE THREAD

**Issue by FHL1998** [haotian-liu/LLaVA#389]
### Question

I have one dumb question that bothers me a lot: If I want to fine-tune LLaVa with my own dataset, how do I set the value of `model_name_or_path`? Should it be something like `lmsys/vicuna-7b-v1.3` or the model tuned by the author already？ Or does this depend on whether I want to fine-tune the model or the adaptor?

**Comment by haotian-liu** [comment]
You should set it to LLaVA's model path. You can check out the example scripts: https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task.sh.

Thanks.
