### ISSUE TITLE
[Question] How to use generated Adapter files from lora finetuning? for inference?

### ISSUE THREAD

**Issue by arpitsahni04** [haotian-liu/LLaVA#390]
### Question

How to use generated Adapter files from lora finetuning? for inference? it says missing KeyError: 'LlavaConfig'
![image](https://github.com/haotian-liu/LLaVA/assets/81643693/16c8cbcf-c9e9-4517-acdf-437eb8232f95)
this is what gets generated. how to convert this to llava weights to use with gradio

**Comment by FHL1998** [comment]
Same issue here, have you solved it?

**Comment by arpitsahni04** [comment]
no still looking for solution @haotian-liu

**Comment by FHL1998** [comment]
> no still looking for solution @haotian-liu
I figured it out, you just have to set the `--model-base`.

**Comment by arpitsahni04** [comment]
What to set --model-base as?

**Comment by haotian-liu** [comment]
You can refer to the instructions [here](https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#launch-a-model-worker).

Model base should be the same as the base LLM you used to train LoRA.
