### ISSUE TITLE
[Usage] Training loss of fine tuning by LoRA is converged to around 1 after 4000 steps

### ISSUE THREAD

**Issue by QiYang03101994** [haotian-liu/LLaVA#399]
### Describe the issue

Issue: Thanks for making the effort to do such great work. I tried fine-tuning the model on 2 A6000 with deep speed and LoRA since I cannot fit my model on two A6000 by using full fine-tuning. However, I noticed that the training loss is coverage to 1.0, which is not good. It would be great if you have any suggestions about why that happened. 

Command:
```
################# LLaMA-2 ##################
PROMPT_VERSION="llava_llama_2"
MODEL_VERSION="llama-2-7b-chat"
################# LLaMA-2 ##################

deepspeed llava/train/train_mem.py \
    --deepspeed /local_storage/yangq6/code/python/LLaVA/scripts/zero2.json \
    --lora_enable True \
    --model_name_or_path /local_storage/yangq6/Model/llama2/Llama-2-7b-chat-hf \
    --version $PROMPT_VERSION \
    --data_path /local_storage/yangq6/Data/llava_instruct_150k.json \
    --image_folder /local_storage/yangq6/Data/train2017 \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter ./checkpoints/llava-$MODEL_VERSION-pretrain/mm_projector.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-$MODEL_VERSION-finetune \
    --num_train_epochs 2 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

screenshots
![image](https://github.com/haotian-liu/LLaVA/assets/54153021/35f99eca-bc30-4b08-9593-773351267f23)

**Comment by ccx1997** [comment]
hello, have you solved the problem? What is the final loss the model converged to?

**Comment by johnmullan** [comment]
How many it/s are you getting with this?

**Comment by haotian-liu** [comment]
Hi, this loss seems okay to me given that it is only trained for a single epoch. You may check out our official logs: https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md

**Comment by daiqing98** [comment]
> Hi, this loss seems okay to me given that it is only trained for a single epoch. You may check out our official logs: https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md

@haotian-liu Hi, I am trying to use finetune_lora.sh with 8*A100(40G), however, the it went divergent after around 1000 steps:
Here is the record:
<img width="654" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/95208297/da326bb9-cd0d-4c26-9dd4-9aea3b296505">

And here is the command:

`/sfs/weka/scratch/mac5vs/LLaVA/llava/train/train_mem.py --local_rank=0 --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 --deepspeed ./scripts/zero3.json --model_name_or_path ./checkpoints/vicuna-13b-v1.5 --version v1 --data_path ./playground/data/LLaVA-Instruct-150K/llava_v1_5_mix665k.json --image_folder ./playground/data --vision_tower openai/clip-vit-large-patch14-336 --pretrain_mm_mlp_adapter ./checkpoints/my-llava-v1.5-13b-pretrain/mm_projector.bin --mm_projector_type mlp2x_gelu --mm_vision_select_layer -2 --mm_use_im_start_end False --mm_use_im_patch_token False --image_aspect_ratio pad --group_by_modality_length True --bf16 True --output_dir ./checkpoints/my-llava-v1.5-13b-lora --num_train_epochs 1 --per_device_train_batch_size 8 --per_device_eval_batch_size 4 --gradient_accumulation_steps 2 --evaluation_strategy no --save_strategy steps --save_steps 100 --save_total_limit 1 --learning_rate 2e-4 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 1 --tf32 True --model_max_length 2048 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to wandb`

I used my pre-trained mlp projector. The training log of it seems good:

<img width="636" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/95208297/e9e64588-1374-4313-b7a7-727f675224d1">

Here is the command I used for pre- training:

'/sfs/weka/scratch/mac5vs/LLaVA/llava/train/train_mem.py --local_rank=0 --deepspeed ./scripts/zero3.json --model_name_or_path ./checkpoints/vicuna-13b-v1.5 --version plain --data_path ./playground/data/LLaVA-Pretrain/blip_laion_cc_sbu_558k.json --image_folder ./playground/data/LLaVA-Pretrain/images --vision_tower openai/clip-vit-large-patch14-336 --mm_projector_type mlp2x_gelu --tune_mm_mlp_adapter True --mm_vision_select_layer -2 --mm_use_im_start_end False --mm_use_im_patch_token False --bf16 True --output_dir ./checkpoints/my-llava-v1.5-13b-pretrain --num_train_epochs 1 --per_device_train_batch_size 32 --per_device_eval_batch_size 4 --gradient_accumulation_steps 1 --evaluation_strategy no --save_strategy steps --save_steps 24000 --save_total_limit 1 --learning_rate 1e-3 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type cosine --logging_steps 1 --tf32 True --model_max_length 2048 --gradient_checkpointing True --dataloader_num_workers 4 --lazy_preprocess True --report_to wandb'

I noticed that one difference is, in your provided script for pre-training, you used zero2.json. I am not sure if it will affect the pretraining stage. At least the training log seems normal, thus I assume the projector is fine then used it for fine-tuning.

May I ask if you have any insights about this? Thanks!

**Comment by haotian-liu** [comment]
Hi @daiqing98 

zero3/zero2 difference is fine. I noticed a similar loss divergence yesterday as well. I found two solutions that can help with this:

1. `--group_by_modality_length False`, this may result in a slight 1 or 2 hour additional training time
2. Check `peft` version is 0.4.0 (I encountered this after I upgrade to the latest branch)

**Comment by daiqing98** [comment]
> Hi @daiqing98
> 
> zero3/zero2 difference is fine. I noticed a similar loss divergence yesterday as well. I found two solutions that can help with this:
> 
> 1. `--group_by_modality_length False`, this may result in a slight 1 or 2 hour additional training time
> 2. Check `peft` version is 0.4.0 (I encountered this after I upgrade to the latest branch)

@haotian-liu Thanks for your reply! My peft version is 0.4.0. I tried to set `--group_by_modility_length = False`, but met with another error:

`Traceback (most recent call last):
  File "/sfs/weka/scratch/mac5vs/LLaVA/llava/train/train_mem.py", line 13, in <module>
    train()
  File "/sfs/weka/scratch/mac5vs/LLaVA/llava/train/train.py", line 934, in train
    trainer.train()
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/transformers/trainer.py", line 2665, in training_step
    self.accelerator.backward(loss)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/accelerate/accelerator.py", line 1847, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1861, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 1993, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 132, in backward
    with torch.random.fork_rng(devices=rng_devices, enabled=ctx.preserve_rng_state):
  File "/scratch/mac5vs/envs/llava/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/torch/random.py", line 137, in fork_rng
    torch.cuda.set_rng_state(gpu_rng_state, device)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/torch/cuda/random.py", line 64, in set_rng_state
    _lazy_call(cb)
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/torch/cuda/__init__.py", line 183, in _lazy_call
    callable()
  File "/scratch/mac5vs/envs/llava/lib/python3.10/site-packages/torch/cuda/random.py", line 62, in cb
    default_generator.set_state(new_state_copy)
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

When `--group_by_modility_length = True`, it is fine, which seems weird. Have you had the same issue before, or any insights on this? Thanks!

**Comment by haotian-liu** [comment]
can you confirm if this happens in the first iteration, or it happens after some iterations? This looks like a CUDA OOM issue. Also, what if you try bs4x4?

**Comment by daiqing98** [comment]
> can you confirm if this happens in the first iteration, or it happens after some iterations? This looks like a CUDA OOM issue. Also, what if you try bs4xaccu4?

@haotian-liu The first iteration. I will try 4*4 instead, thanks!

**Comment by daiqing98** [comment]
> can you confirm if this happens in the first iteration, or it happens after some iterations? This looks like a CUDA OOM issue. Also, what if you try bs4xaccu4?

@haotian-liu . Thanks for your help! My lora fine-tuning is finished. I compared my training log with yours and found that our loss never reached to around 0.2 during fluctuating while yours did:

<img width="336" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/95208297/03184219-d904-43ef-88c0-6f52a94e507f">
(Yours)

<img width="604" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/95208297/89cb0e2e-684c-4cda-8d43-031fcc92bb41">
(Ours)

I wonder if it is an issue? And is it cased by my setting `--group_by_modality_length False` of using `bs4xaccu4`

And one more question, I am tring to evaluate my model with GPT-assisted Evaluation. In model_vqa.py, it seems that I cannot directly use `--model-path ./checkpoints/llava-v1.5-13b-lora`, which raised an error: `KeyError: 'LlavaConfig'`. Is is because that the format of saved lora-based chceckpoint is different from your released llava-v1.5-13b ?

Many thanks!

**Comment by haotian-liu** [comment]
Hi @daiqing98 

It should mainly be due to `--group_by_modality_length False`, but it is fine (and it may be better). Should have nothing to do with bs4x4.

When evaluating on many benchmarks, I usually merge LoRA with the base model to a single checkpoint: https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#create-merged-checkpoints

You can also specify --model-base /path/to/vicuna-v1.5, but you will need to load lora every time you run the eval.

**Comment by daiqing98** [comment]
@haotian-liu Thanks for your guidance! I have one minor issue:

I compared the results of your provided model (llava-v1.5-13b), mine (llava-v1.5-13b-lora) and the one in the paper:

<img width="643" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/95208297/5bad560c-123a-4171-b491-c7efd3e34345"> (results from paper)

> all 82.2 81.1 66.7
complex 91.9 80.7 74.2
conv 80.1 83.7 67.0
detail 74.5 79.0 58.8
(your checkpoint llava-v1.5-13b)

> all 81.7 81.6 66.7
complex 90.2 81.3 73.3
conv 83.7 83.7 70.0
detail 71.1 79.7 56.7
(my llava-v1.5-13b-lora)

I find the while the scores for _conv_ and and _detail_ are slightly different from the results, the score for _complex_ is significantly different. May I ask if there are any insights about this? Thanks!

**Comment by haotian-liu** [comment]
Hi, that is the original V0 checkpoint in the original LLaVA paper (Visual Instruction Tuning) and it is LLaVA-Bench-COCO (where LLaVA has seen the images during the training). Probably the drop is due to that LLaVA-1.5 is only trained with 1 epoch and is less overfit to COCO (original checkpoint is trained for 3 epochs on LLaVA-Instruct only).

You can compare with the LLaVA-Bench in this paper: https://arxiv.org/abs/2310.03744

**Comment by daiqing98** [comment]
@haotian-liu May I ask what the LLaVA-Bench-In-the-Wild bechmark refers to? I see that there is only one score for this benchmark.

**Comment by daiqing98** [comment]
> https://arxiv.org/abs/2310.03744

@haotian-liu Thanks for sharing. But may I ask where I can find LLaVA-Bench-In-the-Wild so that I can evaluate on that? In this github repository, it seems that the GPT4-evaluation still uses  LLaVA-Bench-**COCO**. Many thanks!

**Comment by haotian-liu** [comment]
@daiqing98 Please see [here](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md#llava-bench-in-the-wild).

**Comment by terminator123** [comment]
> save_total_limit

i met the same problem when i funetuned with 2*A100  in lora。do u known why the given script set the group_by_modality_length True ?

**Comment by terminator123** [comment]
> Hi @daiqing98
> 
> It should mainly be due to `--group_by_modality_length False`, but it is fine (and it may be better). Should have nothing to do with bs4x4.
> 
> When evaluating on many benchmarks, I usually merge LoRA with the base model to a single checkpoint: https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#create-merged-checkpoints
> 
> You can also specify --model-base /path/to/vicuna-v1.5, but you will need to load lora every time you run the eval.

hi，below is my scrip, the loss is still  converged to around 6 after 2000 steps，do u hown why?
![image](https://github.com/haotian-liu/LLaVA/assets/7448280/93e44f02-b4bc-4fb7-b57c-b966fc62c134)


![image](https://github.com/haotian-liu/LLaVA/assets/7448280/e17a1c85-fe11-4ded-a35a-ca50340056d5)

**Comment by Zzh-tju** [comment]
@haotian-liu Still having the same training issue by setting `--group_by_modality_length False` and downgrading peft to 0.4.0. 

<img width="2152" height="1196" alt="Image" src="https://github.com/user-attachments/assets/d2b686e1-ce92-43a5-a4c1-d76df785d95d" />
