### ISSUE TITLE
[Question] i can eval, but can not pretrain and instruction tuning

### ISSUE THREAD

**Issue by Lucas1347** [haotian-liu/LLaVA#400]
### Question

If i run with deepspeed, got this error:
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500

If i run python with 1 gpu, got this error:
RuntimeError: FlashAttention only support fp16 and bf16 data type

Some of my environmental configurations: 
Ubuntu 
cuda 11.7
flash-attn==2.0.4
deepspeed==0.9.5

gpu:A100

**Comment by Lucas1347** [comment]
I can run pretrain task with 1 gpu.  Just disabled flash_attention and reduced train batch_size. 
The above problem is still not resolved

**Comment by ai1361720220000** [comment]
> I can run pretrain task with 1 gpu. Just disabled flash_attention and reduced train batch_size. The above problem is still not resolved

Hi, have you solved this problem?
