### ISSUE TITLE
[Question] Is it possible to host a LLaVA-2 demo?

### ISSUE THREAD

**Issue by euanong** [haotian-liu/LLaVA#419]
### Question

I'd love to be able to play around with LLaVA-2 on https://llava.hliu.cc/ -- might it be possible to host LLaVA-2 there?

**Comment by haotian-liu** [comment]
Hi, due to the resource limit, we can only host a limited set of the model checkpoints on the web demo.

You may try running it on HF Space or the free Colab : https://github.com/camenduru/LLaVA-colab

Thanks.

**Comment by haotian-liu** [comment]
Oh also, LLaVA-2 is not released yet :)
