### ISSUE TITLE
[Question] On generation hyper-parameters.

### ISSUE THREAD

**Issue by John-Ge** [haotian-liu/LLaVA#422]
### Question

Hello haotian! Thank you for your great work! I recently find that using a pretrained llava to genarate answer and evaluate on some benchmark is a little unstable. Llava generate different answers with same hyper-parameters. 
You mentioned that this may come from do_sample=True. I would like to know what is the hyper-parameters you use in generating answers. Top_k, Top_q, termperature. What is the recommanded hyper-parameters?
And I observed that you use beams search in generation process. Would you like to release the code for beams search?

**Comment by John-Ge** [comment]
I use beam search with temperature = 0.2 in your model_vqa.py. But it returns an error. Maybe the default temperature is too large for beams = 5. Could you please tell us the hyper-parameters you use for evalutaion? Thank you!

**Comment by haotian-liu** [comment]
Hi, when using beam search, we set the temperature to 1.0

**Comment by John-Ge** [comment]
Thank you!
