### ISSUE TITLE
[Question] Can LLava based on LLama 2 LLM be used for commercial purposes?  

### ISSUE THREAD

**Issue by heylamourding** [haotian-liu/LLaVA#427]
### Question

As mentioned in the doc https://github.com/haotian-liu/LLaVA/blob/main/docs/LLaVA_from_LLaMA2.md, 

> 🦙 -Introduction- [Llama 2 is an open-source LLM released by Meta AI](https://about.fb.com/news/2023/07/llama-2/) today (July 18, 2023). Compared with its early version [Llama 1](https://ai.meta.com/blog/large-language-model-llama-meta-ai/), Llama 2 is more favored in stronger language performance, longer context window, and importantly commercially usable!

Can LLava based on LLama2 LLM be used for commercial purposes?

**Comment by haotian-liu** [comment]
They are supported with LLaMA2 community license.
