### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by yichaoshen-MS** [haotian-liu/LLaVA#430]
### Question

How can I get the checkpoint used by the newest demo, whose name is LLaVA-v1-13B-336px?

**Comment by yichaoshen-MS** [comment]
![image](https://github.com/haotian-liu/LLaVA/assets/112837660/ee1b39c5-9d58-48ff-b61c-8d8253e1f751)

**Comment by yichaoshen-MS** [comment]
![image](https://github.com/haotian-liu/LLaVA/assets/112837660/9782ccdf-94f3-4d2a-80ca-72e9e9df3751)

**Comment by r3shma** [comment]
Hi @yichaoshen-MS, also have the same question, did you figure it out?

**Comment by haotian-liu** [comment]
All model checkpoints are released in the MODEL ZOO: https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md

Thanks.
