### ISSUE TITLE
[Usage]  size mismatch for model.mm_projector.weight

### ISSUE THREAD

**Issue by kanxueli** [haotian-liu/LLaVA#433]
### Describe the issue

Issue: when I run the cli.py, I get a err of size mismatch.How can I solve it? I guess maybe it is mismatch model checkpoint. But i config the environment by [reademe.md](https://github.com/haotian-liu/LLaVA/blob/main/README.md) and https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md.    @haotian-liu 
Command:
```
python -m llava.serve.cli  --model-path /model_path/llava-llama-2-7b-chat-lightning-lora-preview  --model-base /model_path/Llama-2-7b-chat-ms  --image-file  "https://llava-vl.github.io/static/images/view.jpg"  --load-4bit
```

Log: 
```
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LlavaLlamaForCausalLM: size mismatch for model.mm_projector.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2097152, 1]).

**Comment by basteran** [comment]
@kanxueli Have you solved the problem?

**Comment by Deaddawn** [comment]
> ### Describe the issue
> Issue: when I run the cli.py, I get a err of size mismatch.How can I solve it? I guess maybe it is mismatch model checkpoint. But i config the environment by [reademe.md](https://github.com/haotian-liu/LLaVA/blob/main/README.md) and https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md. @haotian-liu Command:
> 
> ```
> python -m llava.serve.cli  --model-path /model_path/llava-llama-2-7b-chat-lightning-lora-preview  --model-base /model_path/Llama-2-7b-chat-ms  --image-file  "https://llava-vl.github.io/static/images/view.jpg"  --load-4bit
> ```
> 
> Log:
> 
> ```
> raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for LlavaLlamaForCausalLM: size mismatch for model.mm_projector.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2097152, 1]).
> ```

Hi, there. I met the same problem. how do you solve it？

**Comment by kanxueli** [comment]
> d

remove '--load-4bit' when you run llava.serve.cli

**Comment by kanxueli** [comment]
> > ### Describe the issue
> > Issue: when I run the cli.py, I get a err of size mismatch.How can I solve it? I guess maybe it is mismatch model checkpoint. But i config the environment by [reademe.md](https://github.com/haotian-liu/LLaVA/blob/main/README.md) and https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md. @haotian-liu Command:
> > ```
> > python -m llava.serve.cli  --model-path /model_path/llava-llama-2-7b-chat-lightning-lora-preview  --model-base /model_path/Llama-2-7b-chat-ms  --image-file  "https://llava-vl.github.io/static/images/view.jpg"  --load-4bit
> > ```
> > 
> > 
> > Log:
> > ```
> > raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> > RuntimeError: Error(s) in loading state_dict for LlavaLlamaForCausalLM: size mismatch for model.mm_projector.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2097152, 1]).
> > ```
> 
> Hi, there. I met the same problem. how do you solve it？

remove '--load-4bit' when you run llava.serve.cli

**Comment by He-JYang** [comment]
> > d
> 
> remove '--load-4bit' when you run llava.serve.cli

It works, thank you!
