### ISSUE TITLE
[Discussion] How to run this with a single 3090 GPU?

### ISSUE THREAD

**Issue by lw0210** [haotian-liu/LLaVA#441]
### Discussion

Dear，may I run this with a single 3090 GPU ？ When I run commands python llava/train/train_mem.py it show CUDA out of memory and I have  set up  per_device_train_batch_size=1. Do I have any other ways to lower the GPU requirements？

**Comment by XLionXL** [comment]
What situation is it? Can we train it on 3090?

**Comment by lw0210** [comment]
Yeah，run the sciripts.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月18日(星期一) 下午2:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [haotian-liu/LLaVA] [Discussion] How to run this with a single 3090 GPU? (Issue #441)





 
What situation is it? Can we train it on 3090?
