### ISSUE TITLE
[Question] Why batch of `input_ids` becomes  3 times bigger in the the `forward()` of LlavaLlamaForCausalLM?

### ISSUE THREAD

**Issue by rabiulcste** [haotian-liu/LLaVA#467]
### Question

I was trying to understand why batch inference does not improve inference speed. I was looking at the code here  https://github.com/haotian-liu/LLaVA/blob/a4269fbf014af3cab1f1d172914493fae8b74820/llava/model/llava_arch.py#L86

Here is the input that I feed to `model.generate()`.
```
input_ids.shape: torch.Size([4, 62])
image_tensor.shape: torch.Size([4, 3, 336, 336])
```
I logged output in `LlavaMetaForCausalLM.prepare_inputs_labels_for_multimodal()`
```
prepare:input_ids torch.Size([12, 62])
prepare:attention_mask torch.Size([12, 637])
prepare:inputs_embeds torch.Size([12, 637, 5120])
```
Also, `LlavaLlamaForCausalLM.forward()`
```
forward:attention_mask torch.Size([12, 637])
forward:inputs_embeds torch.Size([12, 637, 5120])
```

I don't understand why `batch_size` is 3 times larger.

**Comment by haotian-liu** [comment]
Hi, thank you, and I am trying to work on an efficient batch inference. Closing this and consolidating the discussion to #754. Thanks.
