### ISSUE TITLE
KeyError: "llava"

### ISSUE THREAD

**Issue by yigu1008** [haotian-liu/LLaVA#469]
### Question

Hi, when I was trying to load llava weights using scripts
 
```
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("liuhaotian/llava-llama-2-7b-chat-lightning-lora-preview")
```
 
I got error:
 
**File "/home/ygu/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 434, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/ygu/miniconda3/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 829, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/ygu/miniconda3/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 536, in __getitem__
    raise KeyError(key)
KeyError: 'llava'**
 
It seems like llava is not configured in the transformers library. I attempted transformers 4.33.3(latest from pip) and 4.25.1 but both got this error. For python version, both 3.10 and 3.8 were tried but neither worked out.  Could you please help me with this? Thanks!

**Comment by dddraxxx** [comment]
same here

**Comment by willkhoza** [comment]
Getting this error as well

**Comment by serenity-innovation** [comment]
Same here, usually updating transformers from source with "pip install git+https://github.com/huggingface/transformers.git" works but not here

**Comment by fei-chang** [comment]
It seems this issue has been raised before and can be solved [here](https://github.com/haotian-liu/LLaVA/issues/386#issuecomment-1689329746).

**Comment by SOISVerieth** [comment]
Am I right at doing things?
I copied code from the post 

`from transformers import AutoConfig, LlamaConfig 
from llava.model.language_model.llava_llama import LlavaLlamaForCausalLM
class LlavaConfig(LlamaConfig):
    model_type = "llava"
AutoConfig.register("llava", LlavaConfig)
model = LlavaLlamaForCausalLM.from_pretrained("liuhaotian/llava-llama-2-13b-chat-lightning-preview")`

Created .py file and run it. Is this all i've had to do to fix problem?
I'm asking because if that's all it take's than i still got this problem. 
If not- can someone provide me with extra steps?

**Comment by willkhoza** [comment]
Yes this should work. 

But you must first follow the installation instructions for the LlaVA project. From the top of my head, download the repository, update the repository to be in the most recent state, remove the transformers package and and reinstall it in its most recent state. Then place your Python script or notebook with the code snippet you provided above in the same directory as the downloaded and updated LlaVA repository. After running that snippet, it will add llava key to your transformers package and at that point you can use the serve/cli.py to make predictions. You will require some 40 gb RAM or VRAM for the 7b model and you will require 80 gb for the 13b model.

**Comment by SOISVerieth** [comment]
Thanks a LOT!

**Comment by haotian-liu** [comment]
Hi, please use the load_pretrained_model function from our repo until we are officially integraed into Huggingface Transformers.

https://github.com/haotian-liu/LLaVA#quick-start-with-huggingface

**Comment by jeeyung** [comment]
When is it going to be integrated officially into Transformers?
