### ISSUE TITLE
Projector weights missing 'model.embed_tokens.weight'

### ISSUE THREAD

**Issue by fishneck** [haotian-liu/LLaVA#470]
### Describe the issue

Issue:

I want to use provided scripts to finetune on my own dataset and run 
```
bash finetune_lora.sh
```
with 
```
--pretrain_mm_mlp_adapter ./checkpoints/liuhaotian/llava-pretrain-vicuna-7b-v1.3/mm_projector.bin
```
It seems the provided projector weights is missing a key

Log: 
```
  File ".../LLaVA/llava/model/llava_arch.py", line 231, in initialize_vision_tokenizer
    embed_tokens_weight = mm_projector_weights['model.embed_tokens.weight']
KeyError: 'model.embed_tokens.weight'
```
Any chance to correct for this issue?

**Comment by haotian-liu** [comment]
You should set `--mm_use_im_start_end False  --mm_use_im_patch_token False` following the scripts here:

https://github.com/haotian-liu/LLaVA/blob/main/scripts/finetune_lora.sh#L27
