### ISSUE TITLE
[Question]  What's the system prompt that is used in the DEMO site? (because it give much better answer than running it locally)

### ISSUE THREAD

**Issue by barshag** [haotian-liu/LLaVA#477]
### Question

The demo here:
https://llava.hliu.cc/

This is the prompt as running it locally: 

system="A chat between a curious user and an artificial intelligence assistant. "
    "The assistant gives helpful, detailed, and polite answers to the user's questions.",

**Comment by rossman22590** [comment]
where do you put the models?

**Comment by barshag** [comment]
in the cloud (instance with gpu -> its work)

is it the same prompt as i wrote?

**Comment by WilTay1** [comment]
i also encounter the same issue.

**Comment by haotian-liu** [comment]
The system prompts in the demo is the same as the one we released :)
