### ISSUE TITLE
[Question] Why the projection layer and the main model are split?

### ISSUE THREAD

**Issue by SxJyJay** [haotian-liu/LLaVA#480]
### Question

Thanks for your great work! I am confused about the reason of independently saving LLava weights applied delta and the vision-to-text projector weights. It seems that the projector (i.e., mm_projector in code) bridges the vision and text worlds, therefore, without this projector the LLava model will fail in multimodal tasks. In a nutshell, the projector and the main model are consistently coupled together, thus I am curious about why do you saving them independently as different huggingface repo.?

**Comment by haotian-liu** [comment]
If you are talking about full model weights like [`llava-v1.5-13b`](https://huggingface.co/liuhaotian/llava-v1.5-13b) and projector weights like [`llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5`](https://huggingface.co/liuhaotian/llava-v1.5-mlp2x-336px-pretrain-vicuna-13b-v1.5), they are independent of each other.

The projector weights are pretrained linear/MLP layers after the first-stage pretraining, and only linear/MLP layers are optimized. The full model weights are after the second-stage visual instruction tuning (full-ft/lora), and includes the linear layers.

You can check out our paper for more details about the two-stage training scheme. Thanks.

**Comment by erjiaxiao** [comment]
Hello @haotian-liu, if I apply the delta weights to llama by following the instructions below, do I get the full llava weights including the projector, or do I still need to download the projector and use it in the code?
![屏幕截图 2024-04-30 201827](https://github.com/haotian-liu/LLaVA/assets/44388426/bf36af2f-7368-40d4-bd93-b0e1a4687c87)
