### ISSUE TITLE
After downloading llava-v1.5-7b locally, then I uploaded it to my cloud server, but it didn't load successfully [Question] 

### ISSUE THREAD

**Issue by nj159** [haotian-liu/LLaVA#484]
### Question

excuse me, I need your help very much, when I load llava-v1.5-7b to the web side in the third terminal, I changed the path, why does it keep showing in the request huggingface connection, I can't connect huggingface, so I download the model to the local and upload it to my cloud server. The directory where the model files in the server are located is: /opt/data/private/models/LLaVA/liuhaotian/llava-v1.5-7b/。Is it problem about model path?

![image](https://github.com/haotian-liu/LLaVA/assets/144583677/b3e12e4c-27b2-4d59-ad32-8eef3fde07d7)

![image](https://github.com/haotian-liu/LLaVA/assets/144583677/49aaa55d-b478-40fd-901e-58e4ae302fa8)

**Comment by haotian-liu** [comment]
Please remove the leading `/` for `--model-path`, like '--model-path liuhaotian/llava-v1.5-7b'

**Comment by nj159** [comment]
Thank you very much, but the result is still the same，Do I need to change the config.json file?
![image](https://github.com/haotian-liu/LLaVA/assets/144583677/05f6baa6-d6bf-4604-a791-c3caedb6b29e)
![image](https://github.com/haotian-liu/LLaVA/assets/144583677/30f85b14-e72c-47f7-9fae-a7fda2c9689e)

**Comment by haotian-liu** [comment]
Is this an offline server?

**Comment by nj159** [comment]
Sorry, I didn't quite understand what you meant, but I opened the global proxy and the proxy test was normal.
![image](https://github.com/haotian-liu/LLaVA/assets/144583677/050f6cae-a432-4330-a4c4-2b2c8836e24e)

**Comment by nj159** [comment]
> Is this an offline server?
Thank you very much, this is online.
![image](https://github.com/haotian-liu/LLaVA/assets/144583677/90d31300-f960-4276-9930-4ddc0486398b)

**Comment by pineking** [comment]
> Thank you very much, but the result is still the same，Do I need to change the config.json file? ![image](https://user-images.githubusercontent.com/144583677/273424161-05f6baa6-d6bf-4604-a791-c3caedb6b29e.png) ![image](https://user-images.githubusercontent.com/144583677/273424167-30f85b14-e72c-47f7-9fae-a7fda2c9689e.png)
The server can't find clip-336 model locally , and can't download it from huggingface.co

**Comment by nj159** [comment]
> > 非常感谢，但是结果还是一样，我需要更改config.json文件吗？![图像](https://user-images.githubusercontent.com/144583677/273424161-05f6baa6-d6bf-4604-a791-c3caedb6b29e.png) ![图像](https://user-images.githubusercontent.com/144583677/273424167-30f85b14-e72c-47f7-9fae-a7fda2c9689e.png)
> 
> 服务器无法在本地找到clip-336型号，也无法从 huggingface.co 下载

Thank you, but may I ask what is the reason for this? Or are there any good solutions? I just can't access the model I've already downloaded.

**Comment by metercai** [comment]
> > > 非常感谢，但是结果还是一样，我需要更改config.json文件吗？![图像](https://user-images.githubusercontent.com/144583677/273424161-05f6baa6-d6bf-4604-a791-c3caedb6b29e.png) ![图像](https://user-images.githubusercontent.com/144583677/273424167-30f85b14-e72c-47f7-9fae-a7fda2c9689e.png)
> > 
> > 
> > 服务器无法在本地找到clip-336型号，也无法从 huggingface.co 下载
> 
> Thank you, but may I ask what is the reason for this? Or are there any good solutions? I just can't access the model I've already downloaded.

缺模型文件，下载复制过来：https://huggingface.co/openai/clip-vit-large-patch14-336

**Comment by White-Friday** [comment]
"2023-10-20 10:52:28 | ERROR | stderr | OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14-336 is not the path to a directory containing a file named config.json.
2023-10-20 10:52:28 | ERROR | stderr | Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'."

I have a similar problem

**Comment by Harry-Deng** [comment]
Dear Haotian, can you sleep well, I can't, cause I have a similar problem 2 :-(
![image](https://github.com/haotian-liu/LLaVA/assets/72896380/2fb614bf-844a-4cff-a2af-3a8d494d2f4b)

**Comment by nj159** [comment]
> “2023-10-20 10：52：28 |错误 |斯特德尔 |OSError：我们无法连接到“https://huggingface.co”来加载此文件，在缓存文件中找不到它，看起来openai/clip-vit-large-patch14-336不是包含名为config.json的文件的目录的路径。 2023-10-20 10：52：28 |错误 |斯特德尔 |在'https://huggingface.co/docs/transformers/installation#offline-mode'查看您的互联网连接或查看如何在离线模式下运行图书馆。
> 
> 我有类似的问题
If you can't find the model clip-vit-large-patch14-336 , you can download this model at the download address: https://huggingface.co/openai/clip-vit-large-patch14，and change the name to clip-vit-large-patch14-336

**Comment by nj159** [comment]
> If you can't find the model clip-vit-large-patch14-336 , you can download this model at the download address: [https://huggingface.co/openai/clip-vit-large-patch14，and](https://huggingface.co/openai/clip-vit-large-patch14%EF%BC%8Cand) change the name to clip-vit-large-patch14-336

download the model  clip-vit-large-patch14-336
