### ISSUE TITLE
[Question] Will the dataset used to train llava-1.5 be public?

### ISSUE THREAD

**Issue by tingxueronghua** [haotian-liu/LLaVA#486]
### Question

It is great to see llava-1.5 achieves such excellent performance. Want to inquire whether the dataset used to train it will be public together with the training and evaluation scripts?

Asking about this because I am interested in adding more new data into the pretraining stage. Lacking the original data might harm the performance.

**Comment by haotian-liu** [comment]
Yes, we will release the training datasets, scripts, and evaluation scripts on benchmarks in this coming week.

**Comment by tingxueronghua** [comment]
Thanks!
