### ISSUE TITLE
[Question] Launching from code.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [haotian-liu/LLaVA#487]
### Question

There are only exmaples of launching this project as gradio service, or launch from cli. Can you provide examples of how to launch this project inside code?

**Comment by rossaai** [comment]
https://github.com/haotian-liu/LLaVA/blob/main/llava/serve/cli.py

This cli script can be use

**Comment by SuperMasterBlasterLaser** [comment]
@rossaai I just started to use `subprocess` to make cli calls from my code.
