### ISSUE TITLE
[Question] The usage of llava_instruct_80k.json? 

### ISSUE THREAD

**Issue by shipengai** [haotian-liu/LLaVA#488]

**Comment by haotian-liu** [comment]
Hi, we construct the 80k instruction data by subsampling the LLaVA-Instruct-150K:
- Find the overlapping and non-overlapping images from the complex reasoning questions and conversation questions.
- Add non-overlapping image-instruction pairs to each category (reason and conv)
- Randomly sample from the overlapping set to make them to have 40K each.
