### ISSUE TITLE
Is the data collection prompt for detailed decription and complex reasoning released?

### ISSUE THREAD

**Issue by REIGN12** [haotian-liu/LLaVA#49]
Many thanks for your great work! I am loving the idea of using text-only-gpt-4 to harness img-based multimodal data. And I am checking your paper on Table 10 about the details of conversation data collection prompt, which is really detailed. And I found the detailed description and complex reasoing prompt is not existing in this repo? 
![image](https://user-images.githubusercontent.com/67776176/233929769-15221018-716f-4f8e-a3f5-81cd94384f66.png)
Many thanks if you can provide this!!

**Comment by haotian-liu** [comment]
Hi thank you for your interest in our work!

We have released these prompts, and please see description [here](https://github.com/haotian-liu/LLaVA#gpt-4-prompts).
