### ISSUE TITLE
关于预训练和微调逻辑，以及基于的模型

### ISSUE THREAD

**Issue by lower01** [haotian-liu/LLaVA#491]
### Question

如果增加自己的部分数据进行增量预训练，到底是算预训练还是算微调？？，，是用预训练脚本还是用微调脚本还是用lora微调脚本呢？？？
然后是直接基于项目中完整版权重的LLaVA1.5版本进行吗？得到对应微调权重然后合并？

**Comment by haotian-liu** [comment]
> If adding our own partial data for incremental pre-training, is it considered as pre-training or fine-tuning?? Which script should be used - the pre-training script, the fine-tuning script, or the Lora fine-tuning script??

If you have image-text pairs for a more specific domains, you should use the pretraining scripts.
If it is instruction-following data, you can go with the finetuning scripts. Using LoRA or full-ft depends on the training budget.

> Also, should it be directly based on the full-weight LLaVA1.5 version from the project? And then obtain the corresponding fine-tuning weights and merge them?

We will release the full training scripts early in the coming week. You can checkout the schedule and findings in [LLaVA-Med](https://arxiv.org/abs/2306.00890), which is training a biomedical assistant based on LLaVA checkpoints. If you use LoRA, you can choose to [merge the weights](https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#create-merged-checkpoints) or inference [on-the-fly with LoRA adapters](https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#launch-a-model-worker). If it is finetuning, and the checkpoint is good to go without any additional processing.

**Comment by Hzj199** [comment]
> > If adding our own partial data for incremental pre-training, is it considered as pre-training or fine-tuning?? Which script should be used - the pre-training script, the fine-tuning script, or the Lora fine-tuning script??
> 
> If you have image-text pairs for a more specific domains, you should use the pretraining scripts. If it is instruction-following data, you can go with the finetuning scripts. Using LoRA or full-ft depends on the training budget.
> 
> > Also, should it be directly based on the full-weight LLaVA1.5 version from the project? And then obtain the corresponding fine-tuning weights and merge them?
> 
> We will release the full training scripts early in the coming week. You can checkout the schedule and findings in [LLaVA-Med](https://arxiv.org/abs/2306.00890), which is training a biomedical assistant based on LLaVA checkpoints. If you use LoRA, you can choose to [merge the weights](https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#create-merged-checkpoints) or inference [on-the-fly with LoRA adapters](https://github.com/haotian-liu/LLaVA/blob/main/docs/LoRA.md#launch-a-model-worker). If it is finetuning, and the checkpoint is good to go without any additional processing.

May I ask if LLaVA-1.5 trained all the parameters of the vision tower, LLM, and MLP? If certain layers were frozen, could you specify which ones?
