### ISSUE TITLE
[Question] How to evaluate the VQA benchmark?

### ISSUE THREAD

**Issue by z5229889frankwht** [haotian-liu/LLaVA#500]
### Question

Dear,

![image](https://github.com/haotian-liu/LLaVA/assets/61502604/cd0db5d5-3e39-43b7-9808-0d6c14198106)

I hope this message finds you in good health. I am writing to request information on the method you used to evaluate your model on the VQA benchmark. I am particularly interested in understanding the specific steps you followed to apply your model to this task, as detailed in your paper.

Could you please provide a step-by-step account of how you implemented your model for VQA benchmark evaluation? What datasets did you use for evaluation?

I would greatly appreciate it if you could share any information that would help me replicate your work. Your approach, as detailed in your paper, achieved an impressive accuracy of 80%, and I am interested in understanding how this was achieved and possibly reproduce the result.

Thank you very much for your time and response. Please let me know if there is any additional information you need from me.

Best Regards,
Frank

**Comment by liyang-7** [comment]
期待LLaVA-1.5中的测评数据集和测评代码
好人一生平安  Thanks♪(･ω･)ﾉ

**Comment by KainingYing** [comment]
我也想要啊

**Comment by z5229889frankwht** [comment]
> 期待LLaVA-1.5中的测评数据集和测评代码 好人一生平安 Thanks♪(･ω･)ﾉ

我看vqav2的annotations都是十个投票的，LLaVA1.0的是跟GPT-4比较的，就有点好奇是怎么比较的

**Comment by z5229889frankwht** [comment]
> All evaluation instructions are released now :)
> 
> https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md

Thank you!
