### ISSUE TITLE
🦒 colab

### ISSUE THREAD

**Issue by camenduru** [haotian-liu/LLaVA#501]
Thanks for the project ❤️ I made a colab. 🥳 I hope you like it. https://github.com/camenduru/LLaVA-colab

**Comment by AmmarFahmy** [comment]
Great work!!! ...
I just ran both Colab files. Works fine. But models are not downloading and not showing in the Gradio drop-down too.

**Comment by camenduru** [comment]
Thanks ❤ @AmmarFahmy please watch this https://www.youtube.com/watch?v=o7zQAa0NPds

**Comment by AmmarFahmy** [comment]
> Thanks ❤ @AmmarFahmy please watch this https://www.youtube.com/watch?v=o7zQAa0NPds

Yes great .. worked fine.

**Comment by haotian-liu** [comment]
Thank you! Wondering if you would like to add 13B with 4bit as well? We made it work with T4 and 15GB CPU RAM on HF Space. So theoretically it should work for Colab as well? 13B-4bit seems to be both faster and more accurate than 7B-8bit. (will get some numbers later)

https://huggingface.co/spaces/badayvedat/LLaVA

**Comment by camenduru** [comment]
Hi @haotian-liu 👋 Colab Free T4 has only 12.7 GB CPU RAM 😭 so I can only fit `llava-v1.5-7b` with a `max_shard_size='5GB' ` model.

```py
from llava.model.builder import load_pretrained_model
model_path = "liuhaotian/llava-v1.5-7b"
tokenizer, model, image_processor, context_len = load_pretrained_model(
    model_path=model_path,
    model_base=None,
    model_name=model_path.split("/")[-1],
    load_8bit=False,
    load_4bit=False
)
```

```py
out_folder = "/content/model8"
model.save_pretrained(out_folder, max_shard_size='5GB', safe_serialization=False)
tokenizer.save_pretrained(out_folder)
```
https://huggingface.co/4bit/llava-v1.5-7b-5GB/tree/main

I will try the same thing with `liuhaotian/llava-v1.5-13b`

**Comment by camenduru** [comment]
Maybe not possible  😐

https://huggingface.co/4bit/llava-v1.5-13b-8bit/tree/main
https://huggingface.co/4bit/llava-v1.5-13b-5GB/tree/main

![Screenshot 2023-10-14 014828fdfd](https://github.com/haotian-liu/LLaVA/assets/54370274/17325a9b-607a-4a34-9da5-edbf925bef58)

**Comment by haotian-liu** [comment]
@camenduru 

Nuh it is possible. Not sure what is different, but I created a new one with 3gb-shard here: [liuhaotian/llava-v1.5-13b-shard3gb](https://huggingface.co/liuhaotian/llava-v1.5-13b-shard3gb).

![image](https://github.com/haotian-liu/LLaVA/assets/6631389/a9f6f056-f4e7-472b-a697-b1b8b40723bc)

**Comment by camenduru** [comment]
🥳 wow cool 🔥 maybe transformers version idk 😋 I will add to the repo thanks ❤

**Comment by haotian-liu** [comment]
@camenduru Thanks! Also featured the link to Colab on our README :)

**Comment by camenduru** [comment]
thanks ❤

**Comment by nickkolok** [comment]
Hi all! Thank you for doing such amazing things!

1. Any chances to get LLaVA 1.6 working on Colab?
2. Is there a possibility to add an "Undo" button, as at https://huggingface.co/spaces/merve/llava-next ? That would be really helpful!
3. How about context extension? Is that really possible?
