### ISSUE TITLE
[Question] projector weights of llava1.5（pretrain model，corresponding to llama2 and clip）

### ISSUE THREAD

**Issue by dongzhiwu** [haotian-liu/LLaVA#505]
sorry, i find the base llm in your tech report of llava-v1.5 is vicuna-13b, there is projector of vicuna-13b and clip 336 in your model zoo

**Comment by dongzhiwu** [comment]
And any plan to release the pretrain script,  instruction script of llava-v1.5?

**Comment by dongzhiwu** [comment]
And any plan to release to instruction training dataset of llava-v1.5? thanks!

**Comment by dongzhiwu** [comment]
sorry, i find the base llm in your tech report of llava-v1.5 is vicuna-13b, there is projector of vicuna-13b and clip 336 in your model zoo

**Comment by haotian-liu** [comment]
Sorry I missed this issue on the data release day. I tried to find all of them but for some reason this was missed.

[10/11] The training data and scripts of LLaVA-1.5 are released [here](https://github.com/haotian-liu/LLaVA#train), and evaluation scripts are released [here](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md)!
