### ISSUE TITLE
[Question] Reproduction Inquiry on TextVQA using llava-v1.5-13b

### ISSUE THREAD

**Issue by Cuiunbo** [haotian-liu/LLaVA#515]
### Question

Thinks for your wonderful work! I‘m currently trying to reproduce the evaluation results of llava-v1.5-13b on TextVQA as outlined in your paper.

Eval part:
I used the provided code from this GitHub repository for model inference, and incorporated the TextVQA-specific instruction mentioned in the paper as follows:
```
text_instructions = 'Answer the question using a single word or phrase.'
if self.model.config.mm_use_im_start_end:
	qs = DEFAULT_IM_START_TOKEN + DEFAULT_IMAGE_TOKEN + DEFAULT_IM_END_TOKEN + '\n' + qs
else:
	qs = DEFAULT_IMAGE_TOKEN + '\n' + qs

qs = qs + ' ' + text_instructions

conv = conv_templates['llava_v1'].copy() 
conv.append_message(conv.roles[0], qs)
conv.append_message(conv.roles[1], None)
prompt = conv.get_prompt()

input_ids = tokenizer_image_token(prompt, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors='pt').unsqueeze(0).cuda()

image_tensor = self.image_processor.preprocess(image, return_tensors='pt')['pixel_values'][0]

stop_str = conv.sep if conv.sep_style != SeparatorStyle.TWO else conv.sep2
keywords = [stop_str]
stopping_criteria = KeywordsStoppingCriteria(keywords, self.tokenizer, input_ids)

with torch.inference_mode():
	output_ids = self.model.generate(
		input_ids,
		images=image_tensor.unsqueeze(0).half().cuda(),
		do_sample=True,
		temperature=0.2,
		max_new_tokens=1024,
		use_cache=True,
		stopping_criteria=[stopping_criteria])
	
input_token_len = input_ids.shape[1]
n_diff_input_output = (input_ids != output_ids[:, :input_token_len]).sum().item()
if n_diff_input_output > 0:
	print(f'[Warning] {n_diff_input_output} output_ids are not the same as the input_ids')
outputs = self.tokenizer.batch_decode(output_ids[:, input_token_len:], skip_special_tokens=True)[0]
outputs = outputs.strip()
if outputs.endswith(stop_str):
	outputs = outputs[:-len(stop_str)]
outputs = outputs.strip()
```

Scoring part:
I employed the VQA-Score method on TextVQA's official website, and obtained a score of 54.2 over 500 cases, which deviates significantly from your paper's reported results. Additionally, I tried another scoring method where ACC=1 if any correct answer exists in GT, and achieved a score of 61.8 over 500 cases, which aligns closer to the results in your paper.

# Questions:
1. Could you help pinpoint any potential missteps in my replication approach? 
2. Is the discrepancy due to incorrect usage of conv_templates during inference, or a misalignment in the metric calculation applied on TextVQA?

Your guidance on these matters would be immensely appreciated. Thank you!

**Comment by haotian-liu** [comment]
All evaluation instructions are now released, and please let me know if you cannot reproduce with the official scripts, thanks!

https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md

**Comment by Cuiunbo** [comment]
Thank you very much! Now, I am able to reproduce your result. 
It seems that for TextVQA evaluation, LLaVA1.5 followed InstructBLIP, and utilizes a format like this:
“{conversation template} {question} {OCR_Token} {answer's instruction}."
is this correct?

**Comment by haotian-liu** [comment]
Yep, your understanding is correct. We'll also add this detail in the revision, thanks.

**Comment by itzsid** [comment]
@haotian-liu I'm not able to find this file for TextVQA eval: `llava_textvqa_val_v051_ocr.jsonl`.

**Comment by yancie-yjr** [comment]
> Yep, your understanding is correct. We'll also add this detail in the revision, thanks.

So, the performance of TextVQA in paper uses the “{conversation template} {question} {OCR_Token} {answer's instruction}." format to eval?

**Comment by haotian-liu** [comment]
@itzsid 

Please follow the instructions [here](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md#scripts) to prepare the data on processed files for evaluation.

> Before preparing task-specific data, download [eval.zip](https://drive.google.com/file/d/1atZSBBrAX54yYpxtVVW33zFvcnaHeFPy/view?usp=sharing). It contains custom annotations, scripts, and the prediction files with LLaVA v1.5. Extract to ./playground/data/eval. This also provides a general structure for all datasets.


@yancie-yjr 

Yes we followed InstructBLIP on the evaluation setting for TextVQA.
