### ISSUE TITLE
Does this project support Windows 11 PCs with an RTX 4090 GPU? I'm still experiencing problems

### ISSUE THREAD

**Issue by onlinerender** [haotian-liu/LLaVA#516]
### Discussion

Can anyone help me with getting this code to work on a Windows 11 PC?

**Comment by haotian-liu** [comment]
Please check the latest doc for Windows. I tested on my Windows 11 PC and it works now for 16-bit inference. Quantization will be supported later.

https://github.com/haotian-liu/LLaVA/blob/main/docs/Windows.md
