### ISSUE TITLE
Does this only work with Linux machines?

### ISSUE THREAD

**Issue by mberman84** [haotian-liu/LLaVA#519]
### Question

I see a fork for Apple machines, but it's broken (missing requirements.txt file).

When I go through this using Windows 11, it seems at least some of the install process requires Linux. 

Can you confirm?

**Comment by haotian-liu** [comment]
Please check the latest doc for Windows. I tested on my Windows 11 PC and it works now for 16-bit inference. Quantization will be supported later.

https://github.com/haotian-liu/LLaVA/blob/main/docs/Windows.md
