### ISSUE TITLE
GGUF/GPTQ models for LLaVA-1.5 

### ISSUE THREAD

**Issue by shahizat** [haotian-liu/LLaVA#526]
### Question

Hello, 

Is anyone aware of the 4-bit quantized models for LLaVA-1.5 available on Hugging Face? 

Thanks in advance!

**Comment by monatis** [comment]
Se ggerganov/llama.cpp#3436 for GGUF (llama.cpp) version

**Comment by barshag** [comment]
what are the system requirement for that? (running solely on CPU?)

**Comment by aiaicode** [comment]
https://huggingface.co/mys/ggml_llava-v1.5-7b
https://huggingface.co/mys/ggml_llava-v1.5-13b 

7b works better than 13b for now.

Use the [llama.cpp](https://github.com/ggerganov/llama.cpp) repo and run the make command and use ./lava

Runs on CPU. More info on this [PR](https://github.com/ggerganov/llama.cpp/pull/3436)

**Comment by haotian-liu** [comment]
The bug seems to be fixed in https://github.com/ggerganov/llama.cpp/pull/3645
Now the quality for both 7b and 13b are improved.

Closing this now.
