### ISSUE TITLE
[Usage] Visual instruction tuning OOM with zero3.json

### ISSUE THREAD

**Issue by hyer** [haotian-liu/LLaVA#528]
### Describe the issue

Issue:
As the README's description:
```
Visual instruction tuning takes around 20 hours for LLaVA-v1.5-13B on 8x A100 (80G), due to the increased resolution to 336px. It takes around 10 hours for LLaVA-v1.5-7B on 8x A100 (40G).

Training script with DeepSpeed ZeRO-3: [finetune.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune.sh).
```

I try the visual instruction tuning with COCO train2017 with the command:
```
#!/bin/bash
deepspeed --num_gpus=1 llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /mnt/data_nas/models/vicuna-7b-v1.5 \
    --version v1 \
    --data_path /mnt/data_nas/datasets/Multimodal/LLaVA-Instruct-150K/llava_instruct_80k.json \
    --image_folder /mnt/data_nas/datasets/Det/COCO/train2017 \
    --vision_tower /mnt/data_nas/models/clip-vit-large-patch14-336 \
    --pretrain_mm_mlp_adapter /mnt/data_nas/models/llava-v1.5-mlp2x-336px-pretrain-vicuna-7b-v1.5/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-7b_coco-train2017 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2500 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to tensorboard
```
and got GPU OOM with the env:
 - A100 (80G)
 - python3.8
 - CUDA11.8
 - flash_attn-2.3.2+cu118torch2.0cxx11abiFALSE-cp38-cp38-linux_x86_64.whl
 - pytorch 2.0.1

I wonder if there is typo in the `scripts/v1_5/finetune.sh` script. May be the parameter `--deepspeed ./scripts/zero3.json` should be `--deepspeed ./scripts/zero3_offload.json` for A100 (80G) ？

**Comment by haotian-liu** [comment]
Hi, do you use 8x A100? I have tested the scripts locally and they work fine.

Also, since you are using Vicuna-7B, it should work even for A100-40G (also tested locally).

**Comment by hyer** [comment]
> Hi, do you use 8x A100? I have tested the scripts locally and they work fine.
> 
> Also, since you are using Vicuna-7B, it should work even for A100-40G (also tested locally).

I use `--num_gpus=1` with only one A100 (80G), does this matter? It works with `--deepspeed ./scripts/zero3_offload.json`.

**Comment by haotian-liu** [comment]
`zero3_offload.json` basically offloads parameters to CPU and your CPU RAM now serves as part of the VRAM that you can use. This would decrease the speed, so that you are aware of this.

Usually 4x A100-80G would be needed to full-finetune 7B and maybe 2x A400-80G would be enough if we finetune 7B with LoRA. Will release LoRA scripts and checkpoints soon.

**Comment by skyz8421** [comment]
I encountered the same issue: I cannot fully finetune the 7B model using zero3.json. However, it works with zero3_offload.json, though at the cost of reduced speed on a single A100-80G GPU. 

Looking forward to the LoRA/QLoRA scripts!

**Comment by haotian-liu** [comment]
Hi, we have released the LoRA ckpt, script, and a brief doc on the new schedule.

https://github.com/haotian-liu/LLaVA/releases/tag/v1.1.3
