### ISSUE TITLE
[Question] Utilizing a Finetuned custom vicuna13b Model in the llava Framework

### ISSUE THREAD

**Issue by hjsg1010** [haotian-liu/LLaVA#535]
### Question

I have a vicuna13b model that has been finetuned with my own text data (only language finetuning, not image-text pair finetuning using your script). Would it be possible to utilize this in your llava framework?

Could I perhaps change the model-base in this command, or modify my custom vicuna config in some way?
```console
python -m llava.serve.cli --model-path ./data-vol-1/model/llava/llava-336px-pretrain-vicuna-13b-v1.3 --model-base ./data-vol-1/model/llava/vicuna_13b_v1.3 --image-file "./llava/view.jpg" 
```

**Comment by mvsoom** [comment]
@hjsg1010 I was thinking of doing the same thing. Did it work in your case? Thanks :)
