### ISSUE TITLE
[Feature request] Q-Bench (LLaVA-v1.5 excels on low-level vision abilities)

### ISSUE THREAD

**Issue by teowu** [haotian-liu/LLaVA#538]
### feature

Hi Haotian,

A great pleasure to ask. Congratulations to this nice and solid work.

We are a team from NTU S-Lab, working on image/video quality assessment and recently propose a benchmark called [Q-Bench](https://github.com/VQAssessment/Q-Bench), aiming to capture **low-level perception and understanding abilities** of MLLMs/VLLMs/LMMs. This is a sibling-like project to MMBench which is also for 4-question choices, while we find out that LLaVA-v1.5 reaches **top-1 performance** on its hot benchmark (at its release date), as shown in https://github.com/VQAssessment/Q-Bench/tree/master/leaderboards. Is that possible for us to write an evaluation script (similar to the existing one for MMBench) and merge into the evaluation scripts of LLaVA?

Best
Haoning

**Comment by haotian-liu** [comment]
Sure, and that would be great! It would be helpful for the community to have more benchmarks to use conveniently in our code base.

**Comment by teowu** [comment]
Hi Haotian,

Thank you for the kind reply. Here is the pull request: https://github.com/haotian-liu/LLaVA/pull/581/commits. We modified four files, (**2 scripts, 1 evaluation code, and added a paragraph on the doc). 

Thank you so much again.

Best,
Haoning

**Comment by haotian-liu** [comment]
Thank you and sorry for the delay. We have merged the PR. Congratulations again on the great benchmark proposed!
