### ISSUE TITLE
RuntimeError: The size of tensor a (32000) must match the size of tensor b (32003) at non-singleton dimension 0

### ISSUE THREAD

**Issue by zxcvbn114514** [haotian-liu/LLaVA#54]
PS A:\vicuna-minigpt\FastChat> python -m fastchat.model.apply_delta --base A:/vicuna-minigpt/vicuna/llama-13b/LLaMA/output/13B  --target A:/llava-minigpt  --delta A:/llava-delta
Loading the base model from A:/vicuna-minigpt/vicuna/llama-13b/LLaMA/output/13B
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [00:28<00:00,  9.37s/it]
Loading the delta from A:/llava-delta
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [00:35<00:00, 11.80s/it]
Some weights of the model checkpoint at A:/llava-delta were not used when initializing LlamaForCausalLM: ['model.mm_projector.weight', 'model.mm_projector.bias']
- This IS expected if you are initializing LlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Applying the delta
Applying delta:   0%|                                                                          | 0/403 [00:00<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Ge Yunxiang\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in                 │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\Ge Yunxiang\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code        │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ A:\vicuna-minigpt\FastChat\fastchat\model\apply_delta.py:165 in <module>                         │
│                                                                                                  │
│   162 │   │   │   args.base_model_path, args.target_model_path, args.delta_path                  │
│   163 │   │   )                                                                                  │
│   164 │   else:                                                                                  │
│ ❱ 165 │   │   apply_delta(args.base_model_path, args.target_model_path, args.delta_path)         │
│   166                                                                                            │
│                                                                                                  │
│ A:\vicuna-minigpt\FastChat\fastchat\model\apply_delta.py:140 in apply_delta                      │
│                                                                                                  │
│   137 │   print("Applying the delta")                                                            │
│   138 │   for name, param in tqdm(base.state_dict().items(), desc="Applying delta"):             │
│   139 │   │   assert name in delta.state_dict()                                                  │
│ ❱ 140 │   │   param.data += delta.state_dict()[name]                                             │
│   141 │                                                                                          │
│   142 │   print(f"Saving the target model to {target_model_path}")                               │
│   143 │   base.save_pretrained(target_model_path)                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (32000) must match the size of tensor b (32003) at non-singleton dimension 0

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our work!

Let's consolidate the issue to #55, and please let me know if there are further issues there.  Thank you!
