### ISSUE TITLE
[Usage] build backend is missing the 'build_editable' hook

### ISSUE THREAD

**Issue by buaachen1993** [haotian-liu/LLaVA#544]
### Describe the issue

I tried to install according to the official installation instructions，but got this error
"ERROR: Project file:///XXXX/XXXX/LLaVA has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660."

I checked the version of pip and setuptools

pip -V
pip 23.2.1 from /usr/local/conda/envs/llava/lib/python3.10/site-packages/pip (python 3.10)

pip list|grep setup
setuptools         68.0.0

anyone knows why?

**Comment by July-zh** [comment]
I have the same question.

**Comment by haotian-liu** [comment]
Hmm. This is strange. It should not have this issue when you use `pip install -U pip`, and from your pip version suggests that you've probably already done this.

**Comment by buaachen1993** [comment]
After changing to a new machine, the problem was resolved, but I still don't know why the problem occurred. I am going to close the issue for now. Thank you.

**Comment by LukeLIN-web** [comment]
Meet this in pip 22.1   
solved by `pip install -U pip `, pip now 25.1
