### ISSUE TITLE
[Usage] The image paths are missing for ~40k instances in instruction finetuning dataset

### ISSUE THREAD

**Issue by somepago** [haotian-liu/LLaVA#546]
### Describe the issue

Hi, thanks again for sharing the datasets! The json file of [instruction tuning mixture](https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/blob/main/llava_v1_5_mix665k.json) does not contain information of image locations for 40688 instances near the tail. 
<img width="906" alt="Screenshot 2023-10-12 at 8 29 28 AM" src="https://github.com/haotian-liu/LLaVA/assets/14878056/0e246b58-5562-4193-971b-f135c96db456">

**Comment by haotian-liu** [comment]
Yes, because they are the ShareGPT data, and they are pure-text samples.
