### ISSUE TITLE
[Question] llava-7b-v1.5usage

### ISSUE THREAD

**Issue by Deaddawn** [haotian-liu/LLaVA#550]
### Question

Hi, I'm trying to use llava-7b-v1.5 in CLI inference, get this hint:
**[2023-10-12 15:27:30,909] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
test1
t2
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████| 2/2 [04:07<00:00, 123.57s/it]
Some weights of the model checkpoint at /root/szd/LLaVA/ckpt/llava-7b-1.5 were not used when initializing LlavaLlamaForCausalLM: ['model.mm_projector.0.weight', 'model.mm_projector.2.weight', 'model.mm_projector.0.bias', 'model.mm_projector.2.bias']
- This IS expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LlavaLlamaForCausalLM were not initialized from the model checkpoint at /root/szd/LLaVA/ckpt/llava-7b-1.5 and are newly initialized: ['model.mm_projector.bias', 'model.mm_projector.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
image shape <PIL.Image.Image image mode=RGB size=1000x667 at 0x7F7678A3E4D0>
image tensor shape torch.Size([1, 3, 224, 224])
Human: hello**

I haven't update my code, not sure if that's the reason

**Comment by haotian-liu** [comment]
You would need to update the code to at least v1.1.0 (and the latest would be the best). Because we use an MLP projector in LLaVA-v1.5, which is not implemented in previous versions.

**Comment by Deaddawn** [comment]
> You would need to update the code to at least v1.1.0 (and the latest would be the best). Because we use an MLP projector in LLaVA-v1.5, which is not implemented in previous versions.

Got it, haotian哥. Nice work!! O(∩_∩)O

**Comment by Deaddawn** [comment]
Solved
