### ISSUE TITLE
[Question] Change to a new vision encoder

### ISSUE THREAD

**Issue by Rickylht** [haotian-liu/LLaVA#559]
### Question

Hello, It`s really a great work.

In llava.model.multimodel_encoder.clip_encoder.py, if I directly change the vision encoder(e.g. to biomedclip) and load original llava-v1.5 model, the performance become worse because the implicit embeddings are not aligned between new vision encoders`output and the projector?

So if I want to change to a new vision encoder, I can only load other llama models and train a new projector first. Am i right?

**Comment by ZiruiSongBest** [comment]
Hi I am a little confused about changing the Vision encoder. Could you show your code after changing the vision encoder? 
Thanks very much.

**Comment by CRH400AF-A** [comment]
I think that you need to train a new projector first, in order to align image and text feature between images and texts.  That means you need to do stage1 pretrain again.
By the way, how do you modify the code so that it can use a new vision encoder? I think only modifying the clip_encoder.py is not enough.

**Comment by Rickylht** [comment]
> stage1

I`m now working on replacing a vision encoder with an open_clip one. I think you need to change the vision outputs into last hidden layers. Other changes, e.g. in train.py, you need to change the corresponding preprocess function. I think it`s enough. Dimension of projectors will automatically get from clip_encoder.py in `def hidden_size(self):` function.

**Comment by gyupro** [comment]
What about finetuning existing openai clip model? Wouldn't it be easier? I want to adjust vision weights and I am wondering if I can achieve this by just sticking finetuned-openai-clip model

**Comment by Rickylht** [comment]
> What about finetuning existing openai clip model? Wouldn't it be easier? I want to adjust vision weights and I am wondering if I can achieve this by just sticking finetuned-openai-clip model

If you use a new vision encoder, you need to train a new projector first and then finetune the whole model. 

I think it depends on your task whether to train a new clip model or not. E.g. in medical or other specific field, a new vision encoder is necessary. If it's a task on natural images, the openai or openclip pretrained weights are enough but focus more on instruction finetuning.

**Comment by gyupro** [comment]
> > What about finetuning existing openai clip model? Wouldn't it be easier? I want to adjust vision weights and I am wondering if I can achieve this by just sticking finetuned-openai-clip model
> 
> If you use a new vision encoder, you need to train a new projector first and then finetune the whole model.
> 
> I think it depends on your task whether to train a new clip model or not. E.g. in medical or other specific field, a new vision encoder is necessary. If it's a task on natural images, the openai or openclip pretrained weights are enough but focus more on instruction finetuning.

Hi. I am working on translating manga. I need to train more images to fit the vision encoder to be accurate. The domain doesn't seem much different since manga is based on human lives but I want it to be more accurate.

your answer helps a lot. thx

**Comment by lucasjinreal** [comment]
How to using openclip?
