### ISSUE TITLE
[Question] web server got error: {"detail":"Not Found"}

### ISSUE THREAD

**Issue by buaachen1993** [haotian-liu/LLaVA#561]
### Question

web server got only {"detail":"Not Found"} shown in the picture below:
![image](https://github.com/haotian-liu/LLaVA/assets/6391783/5231544a-f26c-48f8-8285-9113b2fef99c)

log like this 
<img width="1066" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/6391783/7bc21cb2-0286-44df-8383-ba7c34b6b018">

**Comment by ifshine** [comment]
same issue for me

**Comment by WanFeng123313** [comment]
Hello, I also encountered this problem, may I ask you to solve it?

**Comment by haotian-liu** [comment]
@WanFeng123313 Do you visit the web demo at port 7860 (gradio demo)?

**Comment by WanFeng123313** [comment]
Thank you. I've successfully run it locally

**Comment by buaachen1993** [comment]
Thanks a lot. I've successfully run it locally too.

**Comment by huanranchen** [comment]
> Do you visit the web demo at port 7860 (gradio demo)?

Hi, could we change the port of gradio (because 7860 is already used by minigpt4)

**Comment by ATing0203** [comment]
and the page is blank.
![image](https://github.com/haotian-liu/LLaVA/assets/161042646/551e5b53-2ed5-44e1-b9e4-2d3cd4351a4e)
