### ISSUE TITLE
[Question] Why model_vqa_loader.py batch_size must be 1

### ISSUE THREAD

**Issue by liuheng0111** [haotian-liu/LLaVA#562]
### Question

I try set batch_size not be 1, and use pad_sequence to pad the input_ids to the same length, but the output text is confused. Can you tell me how to use batch inference in evaluation?

`input_ids = torch.nn.utils.rnn.pad_sequence(
  input_ids,
  batch_first=True,
  padding_value=self.tokenizer.pad_token_id)
batch = dict(
            input_ids=input_ids,
            attention_mask=input_ids.ne(self.tokenizer.pad_token_id),
        )`

**Comment by haotian-liu** [comment]
Hi, thank you, and I am trying to work on an efficient batch inference. Closing this and consolidating the discussion to https://github.com/haotian-liu/LLaVA/issues/754. Thanks.
