### ISSUE TITLE
[Question] Training/Fine tuning on custom dataset

### ISSUE THREAD

**Issue by anonymous-atom** [haotian-liu/LLaVA#564]
### Question

We want to train LLaVa-1.5 13B Model on some custom dataset, can someone refer me or help me how can I fine-tune it on custom dataset, also the dataset format required and other details.

**Comment by aiaicode** [comment]
Fine tune procedure looks something like this :

This is the script to fine-tune v1.5 : [v1.5](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune.sh)
This is the script that trains the model : [train.py](https://github.com/haotian-liu/LLaVA/blob/main/llava/train/train.py#L754)

1. : Create dataset. Your dataset is supposed to be a json file in this format : 
{
    "id": "000000243307",
    "image": "000000243307.jpg",
    "conversations": [
      {
        "from": "human",
        "value": "Can you describe the main features of this image for me?\n<image>"
      },
      {
        "from": "gpt",
        "value": "The image features a man sitting in a chair by himself, looking at a small flat-screen TV or monitor. He appears to be playing a game, as a keyboard and a mouse can be seen in front of him. ."
      }
    ]
  },
2. Keep the images ready with matching id. 

 --data_path ./playground/data/llava_v1_5_mix665k.json \
 --image_folder ./playground/data \
 
In the script, replace the json file and put the images folder in ./playground/data ( I assume that the script looks for the filename recursively so probably keep the ids unique )

Again, I haven't done fine-tuning but this is what training looks like.

Please correct me if i am wrong @haotian-liu

**Comment by clima-ai** [comment]
How do we join the classes in our data to the classes already existing in the model? Should our directory (data) be organized in some special way, for example each class in a sub-directory?

**Comment by anonymous-atom** [comment]
@aiaicode mentioned the steps, though I still didn't proceed with it, I will start training in a week.
In the meantime I would appreciate help from someone who trained/fine-tuned this model.

**Comment by ashhadulislam** [comment]
How much CPU/GPU is needed for fine tuning?
Is there a way of sharing between RAM and GPU?

**Comment by nj159** [comment]
> 提到了步骤，虽然我还是没有继续，但我将在一周内开始训练。与此同时，我将感谢训练/微调此模型的人的帮助。

I am a novice. Do you know the difference between the pre training dataset and fine-tuning dataset of llava? If we customize a dataset in a certain field, do we only need to prepare the fine-tuning dataset?Thank you very much！

**Comment by aa221** [comment]
Can I finetune with a CPU and No GPU... I don't see why I need that much compute power

**Comment by Hemachandirant** [comment]
Hi, can anyone help with how the image should be named? For eg. 000000506095.jpg

**Comment by JAYESH1304** [comment]
please help me to know about how should i use model checkpoints for Fine-tuning LLaVa.

**Comment by AI-Aether** [comment]
> Can I finetune with a CPU and No GPU... I don't see why I need that much compute power

I think probably not because vision models is involved as well.

**Comment by thebealfarisi** [comment]
how to fine tuning llava for non image dataset?

using this format:
[
    {
        "id": "unique_id",
        "image": "",
        "conversations": [
            {
                "from": "human",
                "value": "{question}"
            },
            {
                "from": "gpt",
                "value": "{answer}"
            }
        ]
    }
]

or this format
<s>[INST] <<SYS>> {prompt} <</SYS>> {question} [/INST] {answer}
