### ISSUE TITLE
[Question] Could you please share the extracted video frames in SEED-Bench by extract_video_frames.py

### ISSUE THREAD

**Issue by yix-chen** [haotian-liu/LLaVA#573]
### Question

The raw videos are too large to download

**Comment by haotian-liu** [comment]
I guess there are some restrictions in terms of the dataset license? It may be better to consult the authors of SEED-Bench: https://github.com/AILab-CVC/SEED-Bench

And please let me know if there are convenient ways of downloading provided by the dataset authors and I am more than happy to include in the README. Thanks.

**Comment by dsn01** [comment]
@yix-chen Hi! Have you solved your problem? Could you share me a link to download the extracted video frames in SEED-Bench by extract_video_frames.py? Thank you

**Comment by CnFaker** [comment]
@yix-chen Hi! Have you solved your problem? Could you share me a link to download the extracted video frames in SEED-Bench by extract_video_frames.py? Thank you

**Comment by kinredon** [comment]
@yix-chen @dsn01 @CnFaker Have you solved your problem? Could you share me a link to download the extracted video frames in SEED-Bench by extract_video_frames.py? Thank you. 

I found the official seed-bench team gives a seed video zip file in hugging face https://huggingface.co/datasets/AILab-CVC/SEED-Bench/tree/main, where the extracted frames are present. For each video, there are 8 frames like this:

![Image](https://github.com/user-attachments/assets/6e66f25a-8515-47ed-af17-7c23d5b43b77)

However, I do not know how to correspond them to the results of using the file `extract_video_frames.py`. Any ideas or suggestions?

**Comment by HuangChiEn** [comment]
nop, llava author suppose you download the video, instead of rely on official released video frame.
So, this https://github.com/haotian-liu/LLaVA/issues/1207#issuecomment-2782150112 you may take as reference.

Otherwise, you can still follow Evaluation.md instruction to download the video, and run `extract_video_frames.py`.

**Comment by Liam-L2** [comment]
@kinredon May I ask if you have solved this problem?
