### ISSUE TITLE
The template used to generate input sequence in the codes is different from the one in the paper

### ISSUE THREAD

**Issue by NormXU** [haotian-liu/LLaVA#58]
Thank you very much for your awesome work.

I try to run the code and noticed the template used to generate conversation between humans and gpt is different from the one mentioned in the paper.

According to the paper:
![template](https://user-images.githubusercontent.com/33339685/234197326-db4e04ec-eb59-4cb2-96d0-2ee52261eabb.jpeg)
where `<STOP>` in Vicuna v1.0 is `###`

However, according to the code,
```python
def _add_speaker_and_signal(header, source, get_conversation=True):
    """Add speaker and start/end signal on each round."""
    BEGIN_SIGNAL = "### "
    END_SIGNAL = "\n"
    conversation = header
    for sentence in source:
        from_str = sentence["from"]
        if from_str.lower() == "human":
            from_str = conversation_lib.default_conversation.roles[0]
        elif from_str.lower() == "gpt":
            from_str = conversation_lib.default_conversation.roles[1]
        else:
            from_str = 'unknown'
        sentence["value"] = (BEGIN_SIGNAL + from_str + ": " +
                             sentence["value"] + END_SIGNAL)
        if get_conversation:
            conversation += sentence["value"]
    conversation += BEGIN_SIGNAL
    return conversation
```
If we follow this function, we end up with an input sequence as
```
system-message\n\n### Human: .... \n ### Assistant: .... \n
```

and according to 
```python
def _mask_targets(target, tokenized_lens, speakers):
    # cur_idx = 0
    cur_idx = tokenized_lens[0]
    tokenized_lens = tokenized_lens[1:]
    target[:cur_idx] = IGNORE_INDEX
    for tokenized_len, speaker in zip(tokenized_lens, speakers):
        if speaker == "human":
            target[cur_idx + 2:cur_idx + tokenized_len] = IGNORE_INDEX
        cur_idx += tokenized_len
```
only human message and system message is masked, which means after tokenizing the conversation, we get
```
system-message \n\n ### Human: … \n ### Assistant: … \n
```
and only tokens in 【】 are masked
```
【system-message \n】\n ### 【Human: … 】\n ### Assistant: … \n
```

Is this a bug or just a trick where the implemented template works better than the one mentioned in the paper?

**Comment by haotian-liu** [comment]
Hi @NormXU, thank you for your interest in our work!

Do you mean that `Assistant` and `STOP` token is not masked?

The key difference between our masking strategy and Vicuna's may be that I am not masking the `STOP` token (which is `###` for vicuna-v0).  This was due to that I cloned Vicuna's library on their release date, and pulled again some time later.  At that time, there was strange masking behavior I noticed.  Besides, when I was developing in the early stage, I noticed that not masking `STOP` token seems to allow model know how to stop better, so I made that change.

Also there is slight inconsistency in the writing on the relative position between `\n` and `STOP`, and I will fix this disparity in the future revision.

**Comment by NormXU** [comment]
@haotian-liu Thank you for your quick reply.

Exactly. According to the paper, the `Assistant:` should be masked as well.

From my understanding of the paper, we should process our conversation like this (Let's first ignore the \n and only use ### as our STOP token)
```
system-message### Human: .... ### Assistant: ....
```
and masked sequence should be

```
【system-message】###【 Human: .... 】### 【Assistant:】 ....
```
tokens in 【】 are masked.

Current codes add `\n\n` after system prompt as shown in function preprocess, 

```python
def preprocess(
    sources: Sequence[str],
    tokenizer: transformers.PreTrainedTokenizer,
) -> Dict:
    """
    Given a list of sources, each is a conversation list. This transform:
    1. Add signal '### ' at the beginning each sentence, with end signal '\n';
    2. Concatenate conversations together;
    3. Tokenize the concatenated conversation;
    4. Make a deepcopy as the target. Mask human words with IGNORE_INDEX.
    """
    # add end signal and concatenate together
    conversations = []
    for source in sources:
        header = f"{conversation_lib.default_conversation.system}\n\n"
        conversation = _add_speaker_and_signal(header, source)
        conversations.append(conversation)
    # tokenize conversations
    conversations_tokenized = _tokenize_fn(conversations, tokenizer)
    input_ids = conversations_tokenized["input_ids"]
    targets = copy.deepcopy(input_ids)
    for target, source in zip(targets, sources):
        tokenized_lens = _tokenize_fn([header] + [s["value"] for s in source],
                                      tokenizer)["input_ids_lens"]
        speakers = [sentence["from"] for sentence in source]
        _mask_targets(target, tokenized_lens, speakers)

    return dict(input_ids=input_ids, labels=targets)
```

what we can end up with this preprocess function is a sequence like

```
system-message\n\n### Human: .... \n ### Assistant: .... \n
```

After tokenizing the sequence, we mask the sequence as
```
【 system-message \n\n 】【### Human: … \n】 ### Assistant: … \n <s>
```
tokens in 【】 are masked.

A masked version following the paper should be like
```
【system-message \n\n】 ### 【Human: … \n】 ### 【Assistant:】 … \n <s>
```

**Comment by haotian-liu** [comment]
Hi, thank you for pointing this out, and there is indeed a disparity between the code and the paper that we would definitely fix. I do not find the issues with the current implementation, and let me try to clarify the design choices here.

1. At the point I cloned Vicuna code base, the conversation is constructed in this way:
```
<system_message>
<human_part>
<gpt_part>
```

`human_part` and `gpt_part` are constructed following
```
### {Human/GPT}: {content}\n
```

During training, `<system_message>` and `<human_part>` are masked.

In my preliminary experiments, I noticed that some times the agent does not know when to stop, and I suspect the reason being that there are single Q-A pair in our dataset (for example, complex reasoning and detail question, not exactly the same in our preliminary experiments, but it's a sense of why there are single Q-A pairs). The model is not trained with adding `###` to the end of GPT's response, when there are only single Q-A pairs.

As a fix, I appended `###` to the end of the conversation (despite single-turn or multiple turn), and make them unmasked.

Therefore, you will see that comparing with the original Vicuna's implementation, I have two un-masked components: (1) `###`s in human conversations, (2) a single `###` at the end of the *whole* conversation.

Please let me know if this clarifies the doubts, and if the design choices make sense to you.  Please let me know if you have suggestions in potential improvements to the design.

Thank you!

**Comment by NormXU** [comment]
@haotian-liu I understand. One more question: Do you suggest masking `Assistant:` ?

**Comment by haotian-liu** [comment]
To me, correctly predicting `Assistant` after `###` seems pretty easy, especially for a LLM with 7B parameters or even more.  So masking it or not probably would not make a big difference?  Therefore, I simply follow Vicuna on keeping it unmasked.
