### ISSUE TITLE
Could you please provide a simple script to use your multimodel like huggingface or other multimodels? [Feature request] 

### ISSUE THREAD

**Issue by xinsir6** [haotian-liu/LLaVA#582]
### feature

![image](https://github.com/haotian-liu/LLaVA/assets/128811208/5a736785-67b6-4a24-b622-f6b4986c4668)
like blip2 or other  huggingface models，many people want to use your model for their domain applications,  we want an easy to use method, amazing at your result to be better than gpt4. If you can provide a simple scripts to run your llava1.5 model, I will be very appreciate for it.

**Comment by XenioxYT** [comment]
Same here

**Comment by jiyounglee-0523** [comment]
Same here

**Comment by Niez-Gharbi** [comment]
Have you found a solution yet ?

**Comment by DragosDima96** [comment]
You can already instantiate the model using Hugginface ? (from model the builder.py()). And then I belive you can follow instructions from https://github.com/camenduru/LLaVA-colab/blob/main/LLaVA_13b_8bit_colab.ipynb to apply the model for text/embeddings). Right or am I missing something?

**Comment by Niez-Gharbi** [comment]
@DragosDima96 You're right, it works. The only problem is that LLaVA 1.5 13b is very large on colab, so I have worked with llava-v1.5-7b-5GB.

**Comment by haotian-liu** [comment]
We added the get started section in README, contributed by the community. We are also working on the integration to HF transformers. Thanks!

https://github.com/haotian-liu/LLaVA#quick-start-with-huggingface
