### ISSUE TITLE
[Usage] Error in evaluating GQA

### ISSUE THREAD

**Issue by DietDietDiet** [haotian-liu/LLaVA#584]
### Describe the issue

Issue:
Hi haotian, I met with the following issue when evaluating GQA.
Exception: Can't find testdev_balanced_sceneGraphs.json
Could u kindly help how this file is generated? @haotian-liu 
Thanks!
Command:
```
PASTE THE COMMANDS HERE.
```

Log: 
```
PASTE THE LOGS HERE.
```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by haotian-liu** [comment]
Hi, GQA team does not provide the scene graph for the latest split. However, you can simply comment out that line, as it is not used in evaluation.

**Comment by DietDietDiet** [comment]
@haotian-liu Thanks for your kind reply.
I commented out some redundant files and found that some question ids are not in the prediction file, and I ignored them and get the following result for llava-1.5-13b. Is this a reasonable result?

Loading scene graphs...
Loading questions...
Loading choices...
Loading predictions...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12578/12578 [00:00<00:00, 88322.13it/s]

Binary: 80.56%
Open: 48.68%
Accuracy: 63.32%
Validity: 0.00%
Plausibility: 0.00%
Distribution: 1.81 (lower is better)

Accuracy / structural type:
  choose: 85.21% (1129 questions)
  compare: 65.37% (589 questions)
  logical: 79.26% (1803 questions)
  query: 48.68% (6805 questions)
  verify: 83.26% (2252 questions)

Accuracy / semantic type:
  attr: 70.15% (5186 questions)
  cat: 54.22% (1149 questions)
  global: 64.33% (157 questions)
  obj: 89.59% (778 questions)
  rel: 54.73% (5308 questions)

Accuracy / steps number:
  1: 81.43% (237 questions)
  2: 57.42% (6395 questions)
  3: 66.34% (4266 questions)
  4: 72.01% (793 questions)
  5: 77.37% (822 questions)
  6: 95.12% (41 questions)
  7: 95.00% (20 questions)
  8: 100.00% (3 questions)
  9: 100.00% (1 questions)

Accuracy / words number:
  3: 45.03% (151 questions)
  4: 57.30% (630 questions)
  5: 50.31% (1290 questions)
  6: 59.64% (2074 questions)
  7: 64.49% (1642 questions)
  8: 63.38% (1185 questions)
  9: 68.46% (1281 questions)
  10: 67.57% (1249 questions)
  11: 65.09% (994 questions)
  12: 69.59% (638 questions)
  13: 65.80% (462 questions)
  14: 72.75% (345 questions)
  15: 70.89% (237 questions)
  16: 76.92% (117 questions)
  17: 71.28% (94 questions)
  18: 84.21% (76 questions)
  19: 79.07% (43 questions)
  20: 68.75% (32 questions)
  21: 73.68% (19 questions)
  22: 75.00% (12 questions)
  23: 25.00% (4 questions)
  24: 100.00% (2 questions)
  25: 100.00% (1 questions)

**Comment by haotian-liu** [comment]
> Accuracy: 63.32%

This is exactly the same as ours: https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md#llava-v15

**Comment by liuheng0111** [comment]
Exception: Can't find testdev_balanced_choices.json

**Comment by DietDietDiet** [comment]
> len(a)

the number is the same, so there are some redundant ids in predictions file??

**Comment by DietDietDiet** [comment]
> Exception: Can't find testdev_balanced_choices.json Where can i download it?

just comment it out

**Comment by Darren-greenhand** [comment]
> Exception: Can't find testdev_balanced_choices.json Where can i download it?

I have the same question，and I don't think the choice can be commented out，I tried val_choice and it raises key error，where is the testdev_balanced_choices?

**Comment by liuheng0111** [comment]
> > Exception: Can't find testdev_balanced_choices.json Where can i download it?
> 
> just comment it out

Can you provide the eval.py script?

**Comment by liuheng0111** [comment]
> @haotian-liu Thanks for your kind reply. I commented out some redundant files and found that some question ids are not in the prediction file, and I ignored them and get the following result for llava-1.5-13b. Is this a reasonable result?
> 
> Loading scene graphs... Loading questions... Loading choices... Loading predictions... 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12578/12578 [00:00<00:00, 88322.13it/s]
> 
> Binary: 80.56% Open: 48.68% Accuracy: 63.32% Validity: 0.00% Plausibility: 0.00% Distribution: 1.81 (lower is better)
> 
> Accuracy / structural type: choose: 85.21% (1129 questions) compare: 65.37% (589 questions) logical: 79.26% (1803 questions) query: 48.68% (6805 questions) verify: 83.26% (2252 questions)
> 
> Accuracy / semantic type: attr: 70.15% (5186 questions) cat: 54.22% (1149 questions) global: 64.33% (157 questions) obj: 89.59% (778 questions) rel: 54.73% (5308 questions)
> 
> Accuracy / steps number: 1: 81.43% (237 questions) 2: 57.42% (6395 questions) 3: 66.34% (4266 questions) 4: 72.01% (793 questions) 5: 77.37% (822 questions) 6: 95.12% (41 questions) 7: 95.00% (20 questions) 8: 100.00% (3 questions) 9: 100.00% (1 questions)
> 
> Accuracy / words number: 3: 45.03% (151 questions) 4: 57.30% (630 questions) 5: 50.31% (1290 questions) 6: 59.64% (2074 questions) 7: 64.49% (1642 questions) 8: 63.38% (1185 questions) 9: 68.46% (1281 questions) 10: 67.57% (1249 questions) 11: 65.09% (994 questions) 12: 69.59% (638 questions) 13: 65.80% (462 questions) 14: 72.75% (345 questions) 15: 70.89% (237 questions) 16: 76.92% (117 questions) 17: 71.28% (94 questions) 18: 84.21% (76 questions) 19: 79.07% (43 questions) 20: 68.75% (32 questions) 21: 73.68% (19 questions) 22: 75.00% (12 questions) 23: 25.00% (4 questions) 24: 100.00% (2 questions) 25: 100.00% (1 questions)

The evaluate of GQA is very bad, because of the question did't add "\nAnswer the question using a single word or phrase.". Do you know where can i get the llava_gqa_testdev_balanced.jsonl ?

**Comment by shaojin-zhu** [comment]
I too eval the result of llava1.5 7b and 13b but got different numbers:
7b: Accuracy: 61.02%
13b: Accuracy: 62.00%

I wonder if there are some sampling rules for model generation so the outputs would not be consistent?

**Comment by LostXine** [comment]
Just a quick summary of how to fix `eval.py` based on the comments above, please correct me if I'm wrong:

1. At Line 77, change `default="{tier}_all_questions.json"` to `default="{tier}_questions.json"`
2. Comment out the following lines:
a. Line 120 `scenes = ...`
b. Line 128 `choices = ...`
c. Line 370-375 `valid = ...` - `scores["plausibility"].append(toScore(plausible))`
d. Line 390 `updateConsistency(qid, question, questions)`

Hope it helps.

**Comment by haotian-liu** [comment]
Sorry for the confusion, and thank you all for helping clarifying the evaluation process.

I have updated the docs and include the modified eval.py in GitHub Gist.

> Download the [data](https://cs.stanford.edu/people/dorarad/gqa/download.html) and [evaluation scripts](https://cs.stanford.edu/people/dorarad/gqa/evaluate.html) following the official instructions and put under `./playground/data/eval/gqa/data`. You may need to modify `eval.py` as [this](https://gist.github.com/haotian-liu/db6eddc2a984b4cbcc8a7f26fd523187) due to the missing assets in the GQA v1.2 release.

Please let me know if you still encounter any issues in terms of GQA eval. Thanks.
