### ISSUE TITLE
[Usage] MME eval issue

### ISSUE THREAD

**Issue by aprilehannibal** [haotian-liu/LLaVA#585]
### Describe the issue

Issue:
Did not find the following files in mme.sh.  Could you please help to upload these files? Thanks a lot! @haotian-liu 

```
./playground/data/eval/MME/llava_mme.jsonl

convert_answer_to_mme.py
```

**Comment by haotian-liu** [comment]
https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md#scripts

Please follow the instructions here to download `eval.zip` first, thanks.
