### ISSUE TITLE
[Usage] KeyError when trying to run cli.py using llava-pretrain-llama-2-13b-chat

### ISSUE THREAD

**Issue by shere-khan** [haotian-liu/LLaVA#586]
### Describe the issue

Issue:
I want to run the code from the CLI not the gradio server.

I can run the CLI calling `python -m llava.serve.cli` with "llava-v1.5-13b" just fine, but when I try to use "llava-pretrain-llama-2-13b-chat", I get a KeyError when the line `tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)` is executed.

I've tried fixing this in multiple ways, but it looks like the code is expecting there to be a config file in the cache where huggingface files are downloaded, but it's not there.

What am I doing wrong?

Command:
The following works
```
python -m llava.serve.cli     --model-path liuhaotian/llava-v1.5-7b     --image-file "https://llava-vl.github.io/static/images/view.jpg"     --load-4bit
```
The following throws a KeyError
```
python -m llava.serve.cli     --model-path liuhaotian/llava-pretrain-llama-2-13b-chat     --image-file "https://llava-vl.github.io/static/images/view.jpg"     --load-4bit
```

Log: 
```
~/temp/LLaVA# python -m llava.serve.cli     --model-path liuhaotian/llava-pretrain-llama-2-13b-chat     --image-file "https://llava-vl.github.io/static/images/view.jpg"     --load-4bit
[2023-10-16 05:55:41,257] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/opt/conda/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/temp/LLaVA/llava/serve/cli.py", line 125, in <module>
    main(args)
  File "/root/temp/LLaVA/llava/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/root/temp/LLaVA/llava/model/builder.py", line 102, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 663, in __getitem__
    model_type = self._reverse_config_mapping[key.__name__]
KeyError: 'LlavaConfig'
```

Screenshots:
You may attach screenshots if it better explains the issue.

**Comment by haotian-liu** [comment]
Hi, as mentioned in MODEL ZOO, the checkpoint you used are only pretrained and are not fully instruction tuned. Please use the full-finetuned checkpoint instead. Thanks.

> These are projector weights we have pretrained. You can use these projector weights for visual instruction tuning. They are just pretrained on image-text pairs, and are NOT instruction tuned, which means they do NOT follow instructions as good as our official models, and can output repetitive, lengthy, and garbled outputs. If you want to have nice conversations with LLaVA, use the checkpoints above (LLaVA v1.5).
