### ISSUE TITLE
[Usage] The download dataset file in the eval MMBench-CN is still in English

### ISSUE THREAD

**Issue by liyang-7** [haotian-liu/LLaVA#589]
### Describe the issue

Although the link to the Chinese data set is marked in the eval MMBench-CN , the download result is in English (mmbench_dev_en_20231003.tsv).
<img width="1240" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/28669941/2b03b89b-577a-4e9a-a668-54a40e6c2f5e">

**Comment by haotian-liu** [comment]
Thanks for pointing this out. The link has been updated.
