### ISSUE TITLE
[Question] Is image padding necessary for inference?

### ISSUE THREAD

**Issue by linzhiqiu** [haotian-liu/LLaVA#591]
### Question

I noticed that LLaVA-1.5 changed the default image transform to a padding mode for images instead of cropping. I can see that it helps with training --  is it however required for inference?

**Comment by hill2hill** [comment]
In my case, when padding mode, LLaVA-1.5 seems to output more better text.

**Comment by haotian-liu** [comment]
Your observation is correct.

For both training and evaluation, we used the padding to prevent the loss of the potentially useful information in the image. In training, it also alleviates hallucination to some extent.

However, there is always a trade-off, as padding-and-resize will result in the image being down-scaled, which is another form of information loss. According to our eval, they are similar, but it could be helpful for tasks like OCR and a prior exists that the most information are in the center-area of the image.
