### ISSUE TITLE
[Question] GIF files in OCR_VQA dataset

### ISSUE THREAD

**Issue by July-zh** [haotian-liu/LLaVA#593]
### Question

I noticed during the fine-tuning phase that in the OCR_VQA dataset, there are many GIF files, but they have all been changed to JPG in the JSON. Can these files be directly modified by changing the file extension without any further processing?

**Comment by CRH400AF-A** [comment]
I changed the fille extension, and it works.

**Comment by Carol-lyh** [comment]
> I changed the fille extension, and it works.

Excuse me, should I change the extension in **json** or directly change the **image files**' extension from '.gif' to '.jpg'?

**Comment by CRH400AF-A** [comment]
> > I changed the fille extension, and it works.
> 
> Excuse me, should I change the extension in **json** or directly change the **image files**' extension from '.gif' to '.jpg'?

I changed the **image files**' extension from '.gif' to '.jpg'.  I think this is relatively easy.

**Comment by Carol-lyh** [comment]
Thank you very much! 
Also, I have another question, about 170 images in Visual Genome dataset I downloaded, specifically, the VG_100K_2, is empty. The others are fairly good. And I CAN'T open those 170 images. I've tried to download it several times, actually it's successfully downloaded and unzipped. 
I DON'T know where the problem lying? Have you ever come across this problem?

**Comment by CRH400AF-A** [comment]
> Thank you very much! Also, I have another question, about 170 images in Visual Genome dataset I downloaded, specifically, the VG_100K_2, is empty. The others are fairly good. And I CAN'T open those 170 images. I've tried to download it several times, actually it's successfully downloaded and unzipped. I DON'T know where the problem lying? Have you ever come across this problem?

I didn't come across this problem. I previously downloaded this dataset, so I didn't download it this time.
