### ISSUE TITLE
vision_tower how to insert LLama？

### ISSUE THREAD

**Issue by paulpaul91** [haotian-liu/LLaVA#6]
https://github.com/haotian-liu/LLaVA/blob/main/llava/train/train.py#L427
origin LLama not include vision tower, you may change the transformer code, but not public?

**Comment by WooKimm** [comment]
I just had this question, maybe we just ignored the notice mentioned in the readme:
```
NOTE: In this research preview, we used a modified version of huggingface/transformers library to support multimodal models and the LLaMA tokenizer. 
Make sure that you are using the correct transformers library from https://github.com/haotian-liu/transformers_llava.
```

**Comment by paulpaul91** [comment]
> I just had this question, maybe we just ignored the notice mentioned in the readme:
> 
> ```
> NOTE: In this research preview, we used a modified version of huggingface/transformers library to support multimodal models and the LLaMA tokenizer. 
> Make sure that you are using the correct transformers library from https://github.com/haotian-liu/transformers_llava.
> ```

thx

**Comment by haotian-liu** [comment]
@WooKimm Thanks for sharing this!

Yes, please make sure to install the correct transformers library from https://github.com/haotian-liu/transformers_llava.
