### ISSUE TITLE
[Question] Is the response format "Answer the question using a single word or phrase. " used during training?

### ISSUE THREAD

**Issue by linzhiqiu** [haotian-liu/LLaVA#602]
### Question

I tried to search for this response formatting prompt, but I only see it in playground/data/eval/MME/convert_answer_to_mme.py. How is this used during training?

**Comment by hill2hill** [comment]
grep Answer the question using a single word or phrase. path_to_llava_v1_5_mix665k.json. And you can find relative conversations. [https://huggingface.co/datasets/liuhaotian/LLaVA-Instruct-150K/tree/main](url)

**Comment by haotian-liu** [comment]
@hill2hill Thanks for providing the link.

You may also refer to Table 7 in the response format prompt used.

**Comment by haotian-liu** [comment]
@linzhiqiu Anywhere you want, as long as the correct path is provided `--data_path ./playground/data/llava_v1_5_mix665k.json`

It does not need to be under the same path as your image folder.
