### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by forthelostthings** [haotian-liu/LLaVA#609]
### Describe the issue

Hi,
I have been trying to finetune llava-13b with my own dataset, and I used the latest version of the code. But when I was using the llava, I got the following instructions:

lang_indices, lang_lengths = zip(*[(i, -l) for i, l in enumerate(lengths) if l < 0])
ValueError: not enough values to unpack (expected 2, got 0)

I found that all the items in length are larger than zero

Here's my command:

deepspeed  llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path liuhaotian/llava-llama-2-13b-chat-lightning-preview \
    --version llava_llama_2 \
    --data_path path/to/dataset \
    --image_folder path/to/imagefolder \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter path/to/llava-336px-pretrain-llama-2-13b-chat/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-13b \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True

Is there a way of solving the problem?

**Comment by Deaddawn** [comment]
got the same problem

**Comment by unmo** [comment]
got the same problem

**Comment by unmo** [comment]
The following command option, I solved the problem.
Here's command line option.

**_--group_by_modality_length False_**

**Comment by dydxdt** [comment]
> The following command option, I solved the problem. Here's command line option.
> 
> **_--group_by_modality_length False_**

@unmo so this change won't change the results, right?
I see in README.md:
`--group_by_modality_length True`: this should only be used when your instruction tuning dataset contains both language (e.g. ShareGPT) and multimodal (e.g. LLaVA-Instruct). It makes the training sampler only sample a single modality (either image or language) during training, which we observe to speed up training by ~25%, and does not affect the final outcome.

**Comment by haotian-liu** [comment]
If your test data does not contain pure language data, you do not need this option. We may make this error more graceful.

**Comment by unmo** [comment]
@dydxdt 
Sorry, I have not checked this change does not change the results.

![image](https://github.com/haotian-liu/LLaVA/assets/9719347/e85a3991-28f1-4895-add1-f3687e5a4ef9)

Does this mean that setting is necessary when training both image and language data, as in the training data above?
If so, I get the error too.

**Comment by haotian-liu** [comment]
@unmo 

For pure language data, I mean that conversations have no "image" at all, e.g. ShareGPT. I am a bit confused by the screenshot you shared.

**Comment by unmo** [comment]
@haotian-liu 
I'm sorry.
Screenshot contain the image path. If train dataset includes an image path and conversations data like this, isn't it pure language data?
Is script argument 'group_by_modality_length' is True?

**Comment by haotian-liu** [comment]
If **all** your training data is like this, your training data is pure **multimodal,** so you should set this option to `False`.

If your training data contains both multimodal and pure-text (Q/A does not contain image at all, a pure language chat), you should set the option to `True`.

**Comment by unmo** [comment]
I can understand it. I was a little bit confuse. Thank you.
