### ISSUE TITLE
[Question] Why are image tokens always prepended at start?

### ISSUE THREAD

**Issue by linzhiqiu** [haotian-liu/LLaVA#615]
### Question

In [train.py](llava/train/train.py), there is a preprocess_multimodal() function that will be executed for every sample. However, this function seems to place the image tokens at the start of every sequence. This doesn't align with the paper description where it says the image token will be placed at start or end of the sequence for 50% of the time:

```
def preprocess_multimodal(
    sources: Sequence[str],
    data_args: DataArguments
) -> Dict:
    is_multimodal = data_args.is_multimodal
    if not is_multimodal:
        return sources

    for source in sources:
        for sentence in source:
            if DEFAULT_IMAGE_TOKEN in sentence['value']:
                sentence['value'] = sentence['value'].replace(DEFAULT_IMAGE_TOKEN, '').strip()
                sentence['value'] = DEFAULT_IMAGE_TOKEN + '\n' + sentence['value']
                sentence['value'] = sentence['value'].strip()
                if "mmtag" in conversation_lib.default_conversation.version:
                    sentence['value'] = sentence['value'].replace(DEFAULT_IMAGE_TOKEN, '<Image>' + DEFAULT_IMAGE_TOKEN + '</Image>')
            replace_token = DEFAULT_IMAGE_TOKEN
            if data_args.mm_use_im_start_end:
                replace_token = DEFAULT_IM_START_TOKEN + replace_token + DEFAULT_IM_END_TOKEN
            sentence["value"] = sentence["value"].replace(DEFAULT_IMAGE_TOKEN, replace_token)

    return sources
```

**Comment by linzhiqiu** [comment]
Also I want to confirm -- it seems for 1st stage pre-training, the USER message is removed in preprocess_plain() function? Therefore, the 1st pretraining is now done with sequences like: '<image>floor plan of cottage type house, 1 bedroom\n'

```
def preprocess_plain(
    sources: Sequence[str],
    tokenizer: transformers.PreTrainedTokenizer,
) -> Dict:
    # add end signal and concatenate together
    conversations = []
    for source in sources:
        assert len(source) == 2
        assert DEFAULT_IMAGE_TOKEN in source[0]['value']
        source[0]['value'] = DEFAULT_IMAGE_TOKEN
        conversation = source[0]['value'] + source[1]['value'] + conversation_lib.default_conversation.sep
        conversations.append(conversation)
    # tokenize conversations
    input_ids = [tokenizer_image_token(prompt, tokenizer, return_tensors='pt') for prompt in conversations]
    targets = copy.deepcopy(input_ids)
    for target, source in zip(targets, sources):
        tokenized_len = len(tokenizer_image_token(source[0]['value'], tokenizer))
        target[:tokenized_len] = IGNORE_INDEX

    return dict(input_ids=input_ids, labels=targets)
 ```

**Comment by linzhiqiu** [comment]
@haotian-liu Would be very helpful if you could help confirm my above two observations :-)

1 - \<image\> token is currently always prepended at the start of USER message for stage-2 training
2 - The instruction for image description is removed for stage-1 training.

**Comment by haotian-liu** [comment]
Hi @linzhiqiu 

Thank you for your careful observation and they are both correct.

We iteratively removed some components that ultimately does not much affect the model's performance, over time to make the approach simpler. The change regarding the tokenization is documented [here](https://github.com/haotian-liu/LLaVA/releases/tag/v1.0.1).

We will also document these changes in the revision, thanks.

**Comment by linzhiqiu** [comment]
Thank you Haotian!
