### ISSUE TITLE
Great work! Is it possible for the model to receive only query/text without input image? 

### ISSUE THREAD

**Issue by WilTay1** [haotian-liu/LLaVA#617]
### Question

In your demo, it seems that it is possible for the model to receive only query, and it works like a normal LLM. How to achieve that in the script? Thanks!

**Comment by ninjacode01** [comment]
@WilTay1 Did you find any solution to this? I want to further fine-tune the text only part of the model without utilizing its multimodal ability. Also, the data is comparatively smaller and educational in nature, so finetuning on vicuna might not give better results.
Thanks!

**Comment by lzy37ld** [comment]
@WilTay1 I am also interested in this question! Any insight there?

**Comment by copperwiring** [comment]
I think it might work as per discussion here: https://github.com/haotian-liu/LLaVA/issues/840 and used is science qa evals here: https://github.com/haotian-liu/LLaVA/blob/main/llava/eval/model_vqa_science.py#L58

**Comment by Tree-Shu-Zhao** [comment]
@ninjacode01 Hi! May I ask if the performance dropped after fine-tuning on a text-only dataset? I have multimodal/text mixed samples. After fine-tuning, the performance of text-only queries significantly dropped. I'd like to know if you got similar results.

**Comment by zhanghuiecho** [comment]
> [@ninjacode01](https://github.com/ninjacode01) Hi! May I ask if the performance dropped after fine-tuning on a text-only dataset? I have multimodal/text mixed samples. After fine-tuning, the performance of text-only queries significantly dropped. I'd like to know if you got similar results.

hi @Tree-Shu-Zhao ，i want  to know how do you complete text-only finetune, i want to do it, but i have no idea about it.

**Comment by Tree-Shu-Zhao** [comment]
@zhanghuiecho I was working on instruction tuning with mixed data (image-question - > response and question -> response). If you would like to fine-tune with text-only data, follow [this document](https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md) to prepare your data, and set the `image` field to `None` or simply remove it.

Hope this helps
