### ISSUE TITLE
[Question] License question for LLaVA 1.5

### ISSUE THREAD

**Issue by SetoKaiba** [haotian-liu/LLaVA#621]
### Question

The previous one is not available for commercial use due to the Vicuna license. But the 1.5 is based on llama2. Is LLaVA 1.5 available for commercial use? Thank you.

**Comment by haotian-liu** [comment]
They are released under the llama2 community license.

**Comment by papasanimohansrinivas** [comment]
Just a quick question @haotian-liu are weights for llava 1.5 are open to commercial use and any of the datasets especially for training are all permitted for commercial use ?
