### ISSUE TITLE
[Question] region changed after expand2square

### ISSUE THREAD

**Issue by liuheng0111** [haotian-liu/LLaVA#623]
### Question

I find the region of box has changed when image after expand2square, for example:
quesiton: Please provide the bounding box coordinate of the region this sentence describes: a man bent over behind the cigarette.
image: coco/train2017/000000314530.jpg
bbox = [0.61, 0.36, 0.92, 0.83]
the origin image: 
![image](https://github.com/haotian-liu/LLaVA/assets/18352727/b70e07ed-572d-4a0f-bd05-d59a37a7ea90)

after expand2square, the image with bbox: 
![image](https://github.com/haotian-liu/LLaVA/assets/18352727/2407b495-4666-4ca0-8c39-2576df6916c9)

After expand2square, the region box is not the correct answer for the question. Does this have a big impact on the training effect?

**Comment by Deaddawn** [comment]
> ### Question
> I find the region of box has changed when image after expand2square, for example: quesiton: Please provide the bounding box coordinate of the region this sentence describes: a man bent over behind the cigarette. image: coco/train2017/000000314530.jpg bbox = [0.61, 0.36, 0.92, 0.83] the origin image: ![image](https://user-images.githubusercontent.com/18352727/276577750-b70e07ed-572d-4a0f-bd05-d59a37a7ea90.png)
> 
> after expand2square, the image with bbox: ![image](https://user-images.githubusercontent.com/18352727/276577989-2407b495-4666-4ca0-8c39-2576df6916c9.png)
> 
> After expand2square, the region box is not the correct answer for the question. Does this have a big impact on the training effect?

Hi, I have encountered the same problem, do you know what normalization this '[0.61, 0.36, 0.92, 0.83]' has made? say the original picture is 336*336?

**Comment by liuheng0111** [comment]
the '[0.61, 0.36, 0.92, 0.83]' made by the original image shape, this case is (640 427)

**Comment by Deaddawn** [comment]
> the '[0.61, 0.36, 0.92, 0.83]' made by the original image shape, this case is (640 427)

Oh, got it, so how does the (640 427) norm to the '[0.61, 0.36, 0.92, 0.83]'?

**Comment by egmaminta** [comment]
Hi! Same experience here. The bounding box regions changed/shifted when padding is used. Any tips on how to correct the bounding box after padding?

**Comment by haotian-liu** [comment]
Hi regarding the bounding box coordinates, please see the visualizations in https://github.com/haotian-liu/LLaVA/issues/606#issuecomment-1774076879

We'll add further clarifications of how we define the relative bounding box coordinates in the revision, thank you.
