### ISSUE TITLE
[Usage] Error when evaluate POPE

### ISSUE THREAD

**Issue by Carol-lyh** [haotian-liu/LLaVA#626]
### Describe the issue

The error came out when evaluate on pope dataset:

Category: adversarial, # samples: 3000
label_list = [json.loads(q)['label'] for q in open(label_file, 'r')]
KeyError: 'label'

Actually, there are three categories, adversarial, popular, random, should I CHOOSE ONE or evaluate on all these three?

**Comment by Maxlinn** [comment]
i reproduced the evaluation of POPE, POPE should be organized like
```
playground/
  data/
     pope/
        answers/
        coco/
        llava_pope_test.jsonl
```
coco is fetched from official pope: https://github.com/AoiDragon/POPE/tree/e3e39262c85a6a83f26cf5094022a782cb0df58d/output/coco

note that llava-v1.5 seems to have used a older version of pope(checkout: e3e39262c85a6a83f26cf5094022a782cb0df58d), whose [coco_pope_random.json](https://github.com/AoiDragon/POPE/blob/e3e39262c85a6a83f26cf5094022a782cb0df58d/output/coco/coco_pope_random.json) have 2910 lines, but the latest pope has 3000 lines.

the final value of pope on llava paper seems to be averaged among `f1` of three categories. which is (0.8717759764185703 + 0.8628738147337709 + 0.8450000000000001) / 3 = 0.859883263717447
 
```
Category: random, # samples: 2910 TP      FP      TN      FN 1183    31      1379    317 Accuracy: 0.8804123711340206 Precision: 0.9744645799011532 Recall: 0.7886666666666666 F1 score: 0.8717759764185703 Yes ratio: 0.41718213058419246 0.872, 0.880, 0.974, 0.789, 0.417 ==================================== 
Category: popular, # samples: 3000 TP      FP      TN      FN 1183    59      1441    317 Accuracy: 0.8746666666666667 Precision: 0.9524959742351047 Recall: 0.7886666666666666 F1 score: 0.8628738147337709 Yes ratio: 0.414 0.863, 0.875, 0.952, 0.789, 0.414 ==================================== 
Category: adversarial, # samples: 3000 TP      FP      TN      FN 1183    117     1383    317 Accuracy: 0.8553333333333333 Precision: 0.91 Recall: 0.7886666666666666 F1 score: 0.8450000000000001 Yes ratio: 0.43333333333333335 0.845, 0.855, 0.910, 0.789, 0.433 ====================================
```

**Comment by Carol-lyh** [comment]
lots of thanks!!!

**Comment by wanghao-cst** [comment]
The latest POPE one(3000 lines) random result(0.5017) does not match the previous one.
![Uploading 截屏2023-11-02 14.39.39.png…]()

**Comment by darkpromise98** [comment]
> > The latest POPE one(3000 lines) random result(0.5017) does not match the previous one. <img alt="截屏2023-11-02 14 39 39" width="337" src="https://private-user-images.githubusercontent.com/55015183/279888188-531c6eab-7a65-45dc-bc2c-7f739b14bda8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NjkxNDAsIm5iZiI6MTcwMDk2ODg0MCwicGF0aCI6Ii81NTAxNTE4My8yNzk4ODgxODgtNTMxYzZlYWItN2E2NS00NWRjLWJjMmMtN2Y3MzliMTRiZGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDAzMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OGJkMGVmMzY5YjZmYjhmYjUwNzIzMTA2NTAyNWE5NGY4M2M2NTA0YjJkZTFlMTMyZTg1Yzc1ZWNiNDMwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S8iadzqDTYwrmu1wsGoYHCmkJgHfp-gE4TK2FEZYLhk">
> 
> I get the exact same result

I also find the problem. the random-set (3000 lines) results of latest POPE will get wrong (50% accuracy). Because the latest random-set from [https://github.com/AoiDragon/POPE/blob/main/output/coco/coco_pope_random.json](url) has the different question_id orders with `llava_pope_test.jsonl`.

**Comment by yuezih** [comment]
Hi @Maxlinn, thanks for your sharing! 

Could you tell me where `llava_pope_test.jsonl` is obtained from? It seems that there is no `pope` directory in `playground/data` in the latest LLaVA repo, and I also checked several previous releases and couldn't find it either.

Thanks!

btw I just followed you on Zhihu yesterday, what a coincidence :)

**Comment by Maxlinn** [comment]
> Hi @Maxlinn, thanks for your sharing!
> 
> Could you tell me where `llava_pope_test.jsonl` is obtained from? It seems that there is no `pope` directory in `playground/data` in the latest LLaVA repo, and I also checked several previous releases and couldn't find it either.
> 
> Thanks!
> 
> btw I just followed you on Zhihu yesterday, what a coincidence :)

thanks for your interest and sorry for the late reply for the former asks.

for `llava_pope_test.jsonl` , according to [the doc of llava v1.5 evaluation](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md#scripts). The team has managed to convert all evaluation datasets into same format and then packed into [eval.zip](https://drive.google.com/file/d/1atZSBBrAX54yYpxtVVW33zFvcnaHeFPy/view?usp=sharing). `llava_pope_test.jsonl` was inside.

for pope, it should be noticed that llava 1.5 used [an older version of pope](https://github.com/AoiDragon/POPE/tree/e3e39262c85a6a83f26cf5094022a782cb0df58d/output/coco) (found here https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md#pope). it has around 2990 items in `random` subset while the latest version has 3000. i verified the pope scores in the paper using given version.

**Comment by cookiesupers22** [comment]
Hey @Maxlinn,
Just to ask a quick follow up. I'm getting the same 0.5017 accuracy as the person above me did on the random subset. So to fix this what do you think I should do? I used the random subset from the old version of Pope with exactly 2910 samples. I got this:
Category: random, # samples: 2910
TP	FP	TN	FN	
609	604	851	846
Accuracy: 0.5017182130584192

Any help would be seriously appreciated 🙏🙏🙏

**Comment by eziohzy** [comment]
> > Hi [@Maxlinn](https://github.com/Maxlinn), thanks for your sharing!
> > Could you tell me where `llava_pope_test.jsonl` is obtained from? It seems that there is no `pope` directory in `playground/data` in the latest LLaVA repo, and I also checked several previous releases and couldn't find it either.
> > Thanks!
> > btw I just followed you on Zhihu yesterday, what a coincidence :)
> 
> thanks for your interest and sorry for the late reply for the former asks.
> 
> for `llava_pope_test.jsonl` , according to [the doc of llava v1.5 evaluation](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md#scripts). The team has managed to convert all evaluation datasets into same format and then packed into [eval.zip](https://drive.google.com/file/d/1atZSBBrAX54yYpxtVVW33zFvcnaHeFPy/view?usp=sharing). `llava_pope_test.jsonl` was inside.
> 
> for pope, it should be noticed that llava 1.5 used [an older version of pope](https://github.com/AoiDragon/POPE/tree/e3e39262c85a6a83f26cf5094022a782cb0df58d/output/coco) (found here https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md#pope). it has around 2990 items in `random` subset while the latest version has 3000. i verified the pope scores in the paper using given version.

Your comments should be put in the official readme; by the way, I also need to download the val2014.zip dataset, right?
