### ISSUE TITLE
[Question] GPT-4 Sample Prompts

### ISSUE THREAD

**Issue by ATaylorAerospace** [haotian-liu/LLaVA#628]
### Question

I was looking for a few sample GPT-4 prompts for detail description and complex reasoning questions but the link to the prompts folder @ https://github.com/haotian-liu/LLaVA/blob/main/docs/playground/data/prompts is not valid.

Can someone point me to another location on Github or HF for sample prompts?

Thanks

**Comment by haotian-liu** [comment]
They are here: https://github.com/haotian-liu/LLaVA/tree/main/playground/data/prompts

Can you share which docs point you to that link, so that I can fix it? Thanks.

**Comment by ATaylorAerospace** [comment]
Thanks so much for the update.

Here is the doc that needs to be fixed

**LLaVA/docs/Data.md**

![datamd](https://github.com/haotian-liu/LLaVA/assets/112668339/5559c5e7-db22-47f2-934c-a9854c1e39aa)

**Comment by ATaylorAerospace** [comment]
Thanks so much for the update.

Here is the doc that needs to be fixed

**LLaVA/docs/Data.md**

![datamd](https://github.com/haotian-liu/LLaVA/assets/112668339/2eaaa1cf-19db-4edb-9561-20f5da20bd43)
