### ISSUE TITLE
[Question] About the results on ScienceQA in LLaVA1.5

### ISSUE THREAD

**Issue by jiangsongtao** [haotian-liu/LLaVA#629]
### Question

Hello,sorry to disturbe
I tried to conduct the scienceQA test on llava1.5 and found that the accuracy rate on minitest.jasol was 71.58%, which was consistent with the accuracy in the paper, but the result on test.jasonl was 70.25%. I don’t know if the 71.6% in the paper refers to minitest. result, thank you!

**Comment by jameszhou-gl** [comment]
> ### Question
> Hello,sorry to disturbe I tried to conduct the scienceQA test on llava1.5 and found that the accuracy rate on minitest.jasol was 71.58%, which was consistent with the accuracy in the paper, but the result on test.jasonl was 70.25%. I don’t know if the 71.6% in the paper refers to minitest. result, thank you!

The results I reproduced: IMG-Accurarcy of 70.85% on the test set, with A100 GPUs.

**Comment by jiangsongtao** [comment]
你好，邮件我已收到，我会尽快回复哒！

**Comment by yzbx** [comment]
The results for llava-v1.5-7b I reproduced:

- total 4241, Correct: 2780, Accuracy: 65.55%, Img-Accuracy: 63.91%
- question-file: llava_test_CQM-A.json

63.91% is less than 66.8% in paper for llava-v1.5-7b

**Comment by haotian-liu** [comment]
I just tried and I am able to reproduce the ScienceQA results from scratch:
- Clone the repo on GitHub
- Create a completely new conda environment
- `pip install -e .`
- Download `eval.zip` from Google Drive and unzip
- Clone ScienceQA repo, and download images
- run bash scripts/v1_5/eval/sqa.sh

First, the split is test and not minitest, as you can see from the annotation file length.

<img width="328" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/6631389/7cc02bf7-deab-4fad-b452-01880fd4a1c9">

Second, comment out the first part of the `sqa.sh` and use the provided results, do you reproduce the number below?

> bash scripts/v1_5/eval/sqa.sh
> Total: 4241, Correct: 3155, Accuracy: 74.39%, IMG-Accuracy: 71.64%

Third, uncomment, download the answers/results, and run `sqa.sh`
<img width="1115" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/6631389/648b0e8e-a60c-43d9-8eed-9132821896a1">

Note that when I uploaded `eval.zip` results, I generated the predictions using A100, and tonight I evaluated using A6000, and the numbers are exactly the same, so I am pretty confident that the numbers are correct.

@jiangsongtao @jameszhou-gl @yzbx 
Can you please check and let me know in what steps that may be different from the steps above?

**Comment by yzbx** [comment]
for llava-v1.5-13b, I reproduce the result of @jameszhou-gl
total = 4241, Correct: 2982, Accuracy: 70.31%, Img-Accuracy: 70.85%, lower than 71.6% in paper.
note I use temperature=0 in `llava/eval/model_vqa_science.py`

--model-path: liuhaotian/llava-v1.5-13b
--question-file: llava_test_CQM-A.json,
with A800 GPUs.

**Comment by haotian-liu** [comment]
@yzbx Can you provide the full script you used?

**Comment by yzbx** [comment]
@haotian-liu I use the follow scripts.  

```
for split in test
do
    export TRANSFORMERS_OFFLINE=1
    export PATH=/opt/conda/bin:$PATH
    export PYTHONPATH=.
    cd /mydata/git/LLaVA-main
    prompt="CQM-A"
    model=13b
    torchrun --nnodes 1 --nproc-per-node 8 --master-port 12356 llava/eval/model_vqa_science.py \
    --model-path /mydata/open_vlm/llava-v1.5-${model}/ \
    --question-file /mydata/dataset/ScienceQA/llava_${split}_${prompt}.json \
    --image-folder /mydata/dataset/ScienceQA/${split} \
    --answers-file results/ScienceQA/${split}_${prompt}_llava-${model}.jsonl \
    --single-pred-prompt \
    --temperature 0 \
    --conv-mode vicuna_v1 \
    --tmp-dir tmp/${split}
    
    python llava/eval/eval_science_qa.py \
        --base-dir /mydata/dataset/ScienceQA/ \
        --result-file results/ScienceQA/${split}_${prompt}_llava-${model}.jsonl \
        --output-file results/ScienceQA/${split}_${prompt}_llava-${model}_output.json \
        --output-result results/ScienceQA/${split}_${prompt}_llava-${model}_result.json \
        --split ${split}
done
```

Note: the source data `llava_test_CQM-A.json` is from [docs/ScienceQA.md](https://github.com/haotian-liu/LLaVA/blob/main/docs/ScienceQA.md), not from [eval.zip](https://drive.google.com/file/d/1atZSBBrAX54yYpxtVVW33zFvcnaHeFPy/view?usp=sharing)
```
python scripts/convert_sqa_to_llava.py \
    convert_to_llava \
    --base-dir /path/to/ScienceQA/data/scienceqa \
    --prompt-format "CQM-A" \
    --split test
```

**Comment by haotian-liu** [comment]
Can you try using the file from the eval.zip?

**Comment by yzbx** [comment]
@haotian-liu I found the problem

```
b54d1eca943503d24bbed807b78f3d15  scienceqa/llava_test_CQM-A.json  # from eval.zip 
9776345f346d6082a5a31c0b291e6e21  data/scienceqa/llava_test_CQM-A.json  # from git
9776345f346d6082a5a31c0b291e6e21  /data/BD/dataset/ScienceQA/llava_test_CQM-A.json  # generate with docs/ScienceQA.md
```

use the source data from [eval.zip](https://drive.google.com/file/d/1atZSBBrAX54yYpxtVVW33zFvcnaHeFPy/view?usp=sharing)
I reproduce the result in paper
Total: 4241, Correct: 3155, Accuracy: 74.39%, IMG-Accuracy: 71.64%

**Comment by jiangsongtao** [comment]
Thanks for all your reply,i will close this issue
