### ISSUE TITLE
Should I use the projector weights when evaluating pretrained model?

### ISSUE THREAD

**Issue by hengyuan-hu** [haotian-liu/LLaVA#63]
Thanks for this great repo.

I was able to load the model and run eval following this command
```
python -m llava.eval.run_llava \
    --model-name llava_models/13b \
    --image-file "https://llava-vl.github.io/static/images/view.jpg" \
    --query "What are the things I should be cautious about when I visit here?"
```

However, I notice that the weights for the projector layers in this model is different from the projector weights (as well as embedding weights) downloaded here `https://github.com/haotian-liu/LLaVA#llava-pretrained-projector-weights`. Are the separate projection weights needed for this model? Why are they different from the weights currently in the model?

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our work.

You do not need to load the pretrained MLP layer for running our chat model.  The current released checkpoint uses full-model finetuning (except for CLIP visual encoder), thus the projection layer is also updated -- this accounts for the weight difference.

We are also trying with ablation on freezing the linear projection layer or not, and will update the comparison and analysis in our paper. Thanks.
