### ISSUE TITLE
[Question] How can I edit system message of LLaVA?

### ISSUE THREAD

**Issue by jianzongwu** [haotian-liu/LLaVA#633]
### Question

How can I edit the system message of LLaVA like ChatGPT?

In `conversation.py`, there is a system message recorded as "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions." But I did not find a place to input the system message into the model

**Comment by Road2Redemption** [comment]
I think you can find "from llava.conversation import default_conversation" llava/eval/model_qa.py, it is used for evaluation maybe?

**Comment by jianzongwu** [comment]
I tried to edit the system prompt in `llava.conversation.default_conversation` and load the edited conversation in the gradio app (by changing the template name).
However, the model seems not influenced by the edited system prompt.
Specifically, I told the model to produce output in a given format, but it still just describes the image as usual.

**Comment by wisdomikezogwo** [comment]
try doing this: `pip install -e .` after changing the system prompt for your change to take effect if you haven't before.

**Comment by jianzongwu** [comment]
Fixed, thanks. I finally know that the system prompt is inserted to the chat contents
