### ISSUE TITLE
[Usage] Error named symbol not found at line 529 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu

### ISSUE THREAD

**Issue by TousakaNagio** [haotian-liu/LLaVA#634]
### Describe the issue

Issue: Error named symbol not found at line 529 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu

Command:
python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-v1.5-7b --load-8bit

Log: 
[2023-10-20 20:10:50,697] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-10-20 20:10:51 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=40000, worker_address='http://localhost:40000', controller_address='http://localhost:10000', model_path='liuhaotian/llava-v1.5-7b', model_base=None, model_name=None, device='cuda', multi_modal=False, limit_model_concurrency=5, stream_interval=1, no_register=False, load_8bit=True, load_4bit=False)
2023-10-20 20:10:51 | INFO | model_worker | Loading the model llava-v1.5-7b on worker 32ce76 ...
Loading checkpoint shards:   0%|                                                                                                                                                     | 0/2 [00:00<?, ?it/s]
Error named symbol not found at line 529 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu

Screenshots:
![image](https://github.com/haotian-liu/LLaVA/assets/66267981/28b3740b-f4c6-4755-81b8-c23e36607208)
My device settinig.
I can run the gradio locally without loading by 8 or 4 bits.

**Comment by youliangtan** [comment]
I dont think this is solved. For cases that you would wish to more than 1 CPU e.g. `export CUDA_VISIBLE_DEVICES=0,1,2` quantization still breaks.

This is a known issue in `bitsandbytes` and iam not too sure with the fix
https://github.com/TimDettmers/bitsandbytes/issues/566

**Comment by Lareina2441** [comment]
same problem

**Comment by dongdk** [comment]
same problem, any idea to solve it?

**Comment by ScottDillman** [comment]
This worked for me: 

```bash
uv pip install --force-reinstall bitsandbytes --index-url https://pypi.jetson-ai-lab.io/jp6/cu126
uv pip install --force-reinstall torch torchvision torchaudio --index-url https://pypi.jetson-ai-lab.io/jp6/cu126

ython -m bitsandbytes
================ bitsandbytes v0.48.0.dev0 =================
Platform: Linux-5.15.148-tegra-aarch64-with-glibc2.35
  libc: glibc-2.35
Python: 3.10.18
PyTorch: 2.8.0
  CUDA: 12.6
  HIP: N/A
  XPU: N/A
Related packages:
  accelerate: 0.33.0
  diffusers: 0.31.0
  numpy: 2.2.6
  pip: 25.2
  peft: 0.13.2
  safetensors: 0.6.2
  transformers: 4.37.2
  triton: not found
  trl: not found
============================================================
PyTorch settings found: CUDA_VERSION=126, Highest Compute Capability: (8, 7).
Checking that the library is importable and CUDA is callable...
SUCCESS!
```
I have most of this wrapped in a makefile and set `export PIP_INDEX_URL := https://pypi.jetson-ai-lab.io/jp6/cu126` to avoid the mix and match problems, that way torch,torch-vision and torch-audio don't get stepped on constantly by other installs.
