### ISSUE TITLE
[Usage] Eval Function For Batch Predictiom

### ISSUE THREAD

**Issue by DragosDima96** [haotian-liu/LLaVA#635]
### Describe the issue

The current eval function from llava eval provides example of inference for a bs of 1 (given one input image and one piece of text) and there is a TO DO in code.

Has anyone succeded in modifying the code to allow batch inference?

**Comment by ngc6302h** [comment]
Following this issue. I'm also interested in batch prediction.

**Comment by rabiulcste** [comment]
You'd need a data processor like this https://github.com/rabiulcste/vqazero/blob/13afb6f79648a4efc1184ba4f179b6fd07eacef1/dataset_zoo/custom_processor.py#L73

**Comment by haotian-liu** [comment]
Hi, thank you, and I am trying to work on an efficient batch inference. Closing this and consolidating the discussion to https://github.com/haotian-liu/LLaVA/issues/754.

@rabiulcste If you have prior experience in the batch inference, it is very much appreciated if you could help share some insights on why the batch inference I implemented were not efficient. Thanks.
