### ISSUE TITLE
abnormal generation after pretraining

### ISSUE THREAD

**Issue by lzw-lzw** [haotian-liu/LLaVA#651]
Hi, thank you for your excellent work. When I tried to reproduce your work, I found that when using the first-stage pre-trained model for inference, the model output did not match the picture, and even output some repetitive and meaningless words and symbols like "4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k - 4k -" or "4k happy to be the\n###".
I want to know if this is normal or if there is something wrong with my pretraining stage. Thanks!

**Comment by haotian-liu** [comment]
Hi, please provide your command and which checkpoint are you using?

**Comment by lzw-lzw** [comment]
I used the vicuna-7b-v1.5 model for pre-training, and the architecture and dataset I used are not the newest.
deepspeed llava/train/train.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --version plain \
    --data_path path/data/LLaVA-Pretrain/LLaVA-CC3M-Pretrain-595K/chat.json \
    --image_folder path/data/LLaVA-CC3M-Pretrain-595K/image \
    --vision_tower openai/clip-vit-large-patch14 \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --mm_use_im_patch_token True \
    --bf16 False \
    --fp16 True  \
    --output_dir ./checkpoints/llava-v1.5-7b-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

**Comment by haotian-liu** [comment]
The command seems fine. Do you obtain the generated text using gradio demo? Can you share the command you used to launch the model worker?

**Comment by lzw-lzw** [comment]
Hi, I have solved the problem, it seems that my image folder was broken for some reason, after I re-downloaded the data, everything worked fine. However, I still have a question. Why do you no longer use image start and end token in llava1.5 version? Is it just for convenience or are there any disadvantages to using these tokens?

**Comment by haotian-liu** [comment]
Hi, these changes are mainly for simplicity and do not affect performance, and was introduced back in July for LLaVA-v1 models. You can check it out here: https://github.com/haotian-liu/LLaVA/releases/tag/v1.0.1

We'll include some clarifications in the revised papse, thanks.

**Comment by lzw-lzw** [comment]
Thanks so much!
