### ISSUE TITLE
[Question] A simple inquiry on the statistics of llava_v1_5_mix665k.json

### ISSUE THREAD

**Issue by HenryHZY** [haotian-liu/LLaVA#657]
### Question

Hi @haotian-liu, thanks for your great project.

As mentioned in the paper, the statistics of llava_v1_5_mix665k.json is shown as Table 7:
<img width="500" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/43438692/690e5145-7007-4042-9899-55afc2dcad5e">

That is, 158+40+83+72+9+80+50+22+30+86=630K. There seems to be a missing 35K dataset. Did I miss something? 

To make it more clear, here is the statistics of llava_v1_5_mix665k.json using the key 'image':
```
'coco': 364100
'vg': 86417
'gqa': 72140
'ocr_vqa': 80000
'textvqa': 21953
'text-only': 40688 (without key 'image')
total: 665298
```

For datasets in Table 7 using 'coco' images: 
```
llava: 158K
vqav2: 83K
ok-vqa: 9K
a-ok-vqa: 50K
refcoco: 30K
```

It seems that there is a missing 35K dataset in the 'coco'.

**Comment by Victorwz** [comment]
Hi Ziyuan,

> ### Question
> Hi @haotian-liu, thanks for your great project.
> 
> As mentioned in the paper, the statistics of llava_v1_5_mix665k.json is shown as Table 7: <img alt="image" width="500" src="https://user-images.githubusercontent.com/43438692/277809774-690e5145-7007-4042-9899-55afc2dcad5e.png">
> 
> That is, 158+40+83+72+9+80+50+22+30+86=630K. There seems to be a missing 35K dataset. Did I miss something?
> 
> To make it more clear, here is the statistics of llava_v1_5_mix665k.json using the key 'image':
> 
> ```
> 'coco': 364100
> 'vg': 86417
> 'gqa': 72140
> 'ocr_vqa': 80000
> 'textvqa': 21953
> 'text-only': 40688 (without key 'image')
> total: 665298
> ```
> 
> For datasets in Table 7 using 'coco' images:
> 
> ```
> llava: 158K
> vqav2: 83K
> ok-vqa: 9K
> a-ok-vqa: 50K
> refcoco: 30K
> ```
> 
> It seems that there is a missing 35K dataset in the 'coco'.

Hi Ziyuan, I also have the same question with you. I try to split all the subset based on the prompting formats.

Here is what I get:

``a_okvqa_66k.json 
gqa_72k.json  
ocr_vqa_80k.json  
refcoco_48k.json  
ShareGPT_40k.json  
textvqa_21k.json  
vg_86k.json  
vqav2_okvqa_91k.json``

I think the major difference to the original paper is that the a_okvqa and refcoco subset are much larger than the number claimed in the paper. The a_okvqa is actually 66k, bringing another 16k. The refcoco is actually 48k, birnging another 18k. Therefore, there is about 34k additional data in the 665k mixture.

Additionally, I am also working on a project regarding high-quality data filtering on the 665k instruction tuning data for LLaVA. If you are also working on the same topic, we can discuss and work togerther.

**Comment by simplelifetime** [comment]
> Hi Ziyuan,
> 
> > ### Question
> > Hi @haotian-liu, thanks for your great project.
> > As mentioned in the paper, the statistics of llava_v1_5_mix665k.json is shown as Table 7: <img alt="image" width="500" src="https://user-images.githubusercontent.com/43438692/277809774-690e5145-7007-4042-9899-55afc2dcad5e.png">
> > That is, 158+40+83+72+9+80+50+22+30+86=630K. There seems to be a missing 35K dataset. Did I miss something?
> > To make it more clear, here is the statistics of llava_v1_5_mix665k.json using the key 'image':
> > ```
> > 'coco': 364100
> > 'vg': 86417
> > 'gqa': 72140
> > 'ocr_vqa': 80000
> > 'textvqa': 21953
> > 'text-only': 40688 (without key 'image')
> > total: 665298
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For datasets in Table 7 using 'coco' images:
> > ```
> > llava: 158K
> > vqav2: 83K
> > ok-vqa: 9K
> > a-ok-vqa: 50K
> > refcoco: 30K
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems that there is a missing 35K dataset in the 'coco'.
> 
> Hi Ziyuan, I also have the same question with you. I try to split all the subset based on the prompting formats.
> 
> Here is what I get:
> 
> `a_okvqa_66k.json gqa_72k.json ocr_vqa_80k.json refcoco_48k.json ShareGPT_40k.json textvqa_21k.json vg_86k.json vqav2_okvqa_91k.json`
> 
> I think the major difference to the original paper is that the a_okvqa and refcoco subset are much larger than the number claimed in the paper. The a_okvqa is actually 66k, bringing another 16k. The refcoco is actually 48k, birnging another 18k. Therefore, there is about 34k additional data in the 665k mixture.
> 
> Additionally, I am also working on a project regarding high-quality data filtering on the 665k instruction tuning data for LLaVA. If you are also working on the same topic, we can discuss and work togerther.

Hello Victorwz, thanks for your work. Can you share your index list which splits the datasets apart?

**Comment by haotian-liu** [comment]
Apologies for the confusion. I just re-calculated the exact samples in the dataset mixture, and we will update the paper to correct the sample count for RefCOCO and A-OKVQA. Note that the released dataset is correct, only the number reported in the table is off for these two datasets.

| Dataset       | Actual  | Paper |
|---------------|--------:|------:|
| LLaVA |  157712 |  158K |
| SG40k         |   40688 |   40K |
| VQA-v2        |   82783 |   83K |
| GQA           |   72140 |   72K |
| OKVQA         |    8998 |    9K |
| OCRVQA       |   80000 |   80K |
| A-OKVQA       |   **66160** |   ~~50K~~ **66K** |
| TextCaps      |   21953 |   22K |
| RefCOCO       |   **48447** |   ~~30K~~ **48K** |
| VG            |   86417 |   86K |
| **Total**     | **665298** | **665K** |

**Comment by HenryHZY** [comment]
> Apologies for the confusion. I just re-calculated the exact samples in the dataset mixture, and we will update the paper to correct the sample count for RefCOCO and A-OKVQA. Note that the released dataset is correct, only the number reported in the table is off for these two datasets.
> 
> Dataset	Actual	Paper
> LLaVA	157712	158K
> SG40k	40688	40K
> VQA-v2	82783	83K
> GQA	72140	72K
> OKVQA	8998	9K
> OCRVQA	80000	80K
> A-OKVQA	**66160**	~50K~ **66K**
> TextCaps	21953	22K
> RefCOCO	**48447**	~30K~ **48K**
> VG	86417	86K
> **Total**	**665298**	**665K**

Thanks for your reply! These specific numbers also facilitate a better understanding of the composition of the dataset.

**Comment by HenryHZY** [comment]
@Victorwz Hi, Weizhi. Sorry for the late reply as I haven't been following the github issue recently. 
Conduct high-quality data filtering on the instruction tuning data is a great idea. Although I am not working on this topic, I think instruction tuning is really significant. 
I have reproduced both the pretraining and finetuning stages, LLaVA1.5 without instruction tuning performs poorly in traditional downstream tasks. 
I think we can also have a discussion about it when available:)

**Comment by wzy14284** [comment]
Thank you for your issue it helped me a lot, but I'm still a little confused, how to distinguish between vqav2_83k and okvqa_9k, what they have in common is that there is 'coco' in the image path, and use a single word or phrase to answer the question, but I don't know the difference between them:)

**Comment by ppalantir** [comment]
> ### Question
> Hi @haotian-liu, thanks for your great project.
> 
> As mentioned in the paper, the statistics of llava_v1_5_mix665k.json is shown as Table 7: <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/43438692/277809774-690e5145-7007-4042-9899-55afc2dcad5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODk0NzIsIm5iZiI6MTcyMzY4OTE3MiwicGF0aCI6Ii80MzQzODY5Mi8yNzc4MDk3NzQtNjkwZTUxNDUtNzAwNy00MDQyLTk4OTktNTVhZmMyZGNhZDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAyMzI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1M2UxODZhNmYxOWE3NWVlNDM5MDc1MDcxZTYyODViY2Y2ODljOWMxMDNkNDBkZDIwZDdjZDk2YzhhZWY1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TRCAyciuORUDyyqTc59XFZwA3SkUTxXy8ugJj__VBMc">
> 
> That is, 158+40+83+72+9+80+50+22+30+86=630K. There seems to be a missing 35K dataset. Did I miss something?
> 
> To make it more clear, here is the statistics of llava_v1_5_mix665k.json using the key 'image':
> 
> ```
> 'coco': 364100
> 'vg': 86417
> 'gqa': 72140
> 'ocr_vqa': 80000
> 'textvqa': 21953
> 'text-only': 40688 (without key 'image')
> total: 665298
> ```
> 
> For datasets in Table 7 using 'coco' images:
> 
> ```
> llava: 158K
> vqav2: 83K
> ok-vqa: 9K
> a-ok-vqa: 50K
> refcoco: 30K
> ```
> 
> It seems that there is a missing 35K dataset in the 'coco'.

@haotian-liu it's strange that there are only 608081 images (not 665K, not 630K) in total following dataset  preparation in readme.

<img width="449" alt="image" src="https://github.com/user-attachments/assets/8a233d79-7be3-4c9d-9191-e0dd931652f3">

**Comment by hunarbatra** [comment]
> @haotian-liu it's strange that there are only 608081 images (not 665K, not 630K) in total following dataset preparation in readme.

I'm getting the same counts as @ppalantir (608k and not 665k) for the instruction tuning dataset following the dataset preparation steps in the readme file. @haotian-liu can you please check on this? Thanks!

Update: 40,688 are text only from ShareGPT, which makes the total count 648k now. I'm guessing the rest is just some repeated images likely.
