### ISSUE TITLE
[Question] What is llava_instruct_80k data?

### ISSUE THREAD

**Issue by Victorwz** [haotian-liu/LLaVA#658]
### Question

Hi Haotian,

Thanks for the great work! I found in the ```scripts/fine_tune.sh``` file, your input parameter for for "data_path" is "./playground/data/llava_instruct_80k.json". I also found that you release such 80k data on your huggingface datasets repo. 

However, I did not found how you get such 80k samples from your 150k sample pool in your paper or other documents.

Can you help clarify how you downsample and get such 80k data? Thank you!

**Comment by haotian-liu** [comment]
Hi, we construct the 80k instruction data by subsampling the LLaVA-Instruct-150K:
- Find the overlapping and non-overlapping images from the complex reasoning questions and conversation questions.
- Add non-overlapping image-instruction pairs to each category (reason and conv)
- Randomly sample from the overlapping set to make them to have 40K each.
