### ISSUE TITLE
[Question]  LLaVA1.5 model license

### ISSUE THREAD

**Issue by unmo** [haotian-liu/LLaVA#659]
### Question

The readme contains the following information

_**Usage and License Notices: The data and checkpoint is intended and licensed for research use only. They are also restricted to uses that follow the license agreement of LLaMA, Vicuna and GPT-4. The dataset is CC BY NC 4.0 (allowing only non-commercial use) and models trained using the dataset should not be used outside of research purposes.**_

Is this model not commercially available? Or is this explanation wrong?
I  think this model conform to the llama2 license.

**Comment by papasanimohansrinivas** [comment]
Looking for the same ,.we also @unmo

**Comment by haotian-liu** [comment]
LLaVA-1.5 (Vicuna-1.5 based) and LLaVA (LLaMA-2 based) are both licensed under LLaMA-2 community license, as indicated in the specific MODEL CARD on HF. Thanks.

**Comment by papasanimohansrinivas** [comment]
hi @haotian-liu you are referring to models of LLaVA-1.5 (Vicuna-1.5 based) and LLaVA (LLaMA-2 based)  as llama2 license right to be specific and by that logic they are commercial applicable under llama2 terms

**Comment by ChintanShahDS** [comment]
@haotian-liu Sorry Can you confirm if LLaVA-1.5 (Vicuna-1.5 based) and LLaVA (LLaMA-2 based) can be used commercially or not.

**Comment by huvers** [comment]
The dataset stack, which includes COCO, contains many non-commercial licensed images, even if the annotations are labeled as MIT/Apache 2.0. 

No serious legal team would look at the underlying training set and say this is commercially usable.

**Comment by PaulFidika** [comment]
https://github.com/haotian-liu/LLaVA/commit/ba72f82cc610b01dc27764b483dfe982948b0633

The terms in the README were updated on December 22nd, and, in my opinion, now permit commercial usage. The previous releases of this dataset had a non-commercial CC license imposed by the creators, but this revision removed that restriction.

So the remaining stipulations would be around (1) LLama 2 community license, which allows for commercial usage, (2) Vicuna v1.5 allows for commercial usage (previous iterations did not), (3) OpenAI's nonsensical non-competitive-usage clause for GPT-4 (i.e., GPT-4 outputs supposed cannot be used to train competing models, although OpenAI uses your inputs and the entire internet to train their models?), could be problematic. I believe CLIP and ViT-L14 are MIT licensed (anything goes), from back when OpenAI was open (pre-2023).

As to the question of ownership of the images themselves; idk.
