### ISSUE TITLE
[Question] The training logs of LLaVA-1.5 7B model

### ISSUE THREAD

**Issue by yuyq96** [haotian-liu/LLaVA#660]
### Question

#613 Thank you for making the training logs of the 13B model publicly available. We are trying to reproduce the results of the 7B model on V100 GPUs, so it would be helpful if you could also make the training logs of the 7B model publicly available.

**Comment by haotian-liu** [comment]
Hi, the logs are updated. By default it still shows the 13B, and please toggle the experiment of your interest to view the logs.
