### ISSUE TITLE
[Usage] AttributeError: 'NoneType' object has no attribute 'image_mean'

### ISSUE THREAD

**Issue by unmo** [haotian-liu/LLaVA#664]
### Describe the issue

Issue: 
I have tried this $ python -m llava.serve.cli  --model-path /app/LLaVA/checkpoints/vicuna1.5-7b_clip-vit-l-patch14 --image-file https://llava-vl.github.io/static/images/view.jpg
But it doesn't work

Command:
```
python -m llava.serve.cli \
    --model-path /app/LLaVA/checkpoints/vicuna1.5-7b_clip-vit-l-patch14 \
    --image-file "https://llava-vl.github.io/static/images/view.jpg"
```

Log: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/LLaVA/llava/serve/cli.py", line 125, in <module>
    main(args)
  File "/app/LLaVA/llava/serve/cli.py", line 56, in main
    image_tensor = process_images([image], image_processor, args)
  File "/app/LLaVA/llava/mm_utils.py", line 33, in process_images
    image = expand2square(image, tuple(int(x*255) for x in image_processor.image_mean))
AttributeError: 'NoneType' object has no attribute 'image_mean'```

Screenshots:
![image](https://github.com/haotian-liu/LLaVA/assets/9719347/d19fe062-8859-44be-98f1-2d4d946ad6b3)

**Comment by Adrian-1234** [comment]
Me too on the above error...

**Comment by skyz8421** [comment]
+1, I just met the same problem

**Comment by haotian-liu** [comment]
Hi, currently the code recognizes the multimodal by identifying the "llava" in the model path. Try renaming it to llava-vicuna-xxxx.

**Comment by unmo** [comment]
@haotian-liu 
It worked. Thank you for your work.

**Comment by unmo** [comment]
closed

**Comment by Adrian-1234** [comment]
Works for me also - many thanks !

**Comment by CynthiaChuang** [comment]
> Hi, currently the code recognizes the multimodal by identifying the "llava" in the model path. Try renaming it to llava-vicuna-xxxx.

It works for me. Thx.

**Comment by yesgvinayak** [comment]
@haotian-liu  
I am also facing the same issue. But  I am using my fine-tuned model after running merge_lora_weights.py .

getting the below error:

 File "/home/skadmin/cx-research/core/Llava/llava/eval/run_llava.py", line 117, in eval_model
    images_tensor = process_images(
  File "/home/skadmin/cx-research/core/Llava/llava/mm_utils.py", line 171, in process_images
    image = expand2square(image, tuple(int(x*255) for x in image_processor.image_mean))
AttributeError: 'NoneType' object has no attribute 'image_mean'


the code :

model_path = "./saved_model"
model_name = get_model_name_from_path(model_path)
tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, None, model_name)

**Comment by AliMekky** [comment]
> @haotian-liu I am also facing the same issue. But I am using my fine-tuned model after running merge_lora_weights.py .
> 
> getting the below error:
> 
> File "/home/skadmin/cx-research/core/Llava/llava/eval/run_llava.py", line 117, in eval_model images_tensor = process_images( File "/home/skadmin/cx-research/core/Llava/llava/mm_utils.py", line 171, in process_images image = expand2square(image, tuple(int(x*255) for x in image_processor.image_mean)) AttributeError: 'NoneType' object has no attribute 'image_mean'
> 
> the code :
> 
> model_path = "./saved_model" model_name = get_model_name_from_path(model_path) tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, None, model_name)

+1

**Comment by AliMekky** [comment]
> @haotian-liu I am also facing the same issue. But I am using my fine-tuned model after running merge_lora_weights.py .
> 
> getting the below error:
> 
> File "/home/skadmin/cx-research/core/Llava/llava/eval/run_llava.py", line 117, in eval_model images_tensor = process_images( File "/home/skadmin/cx-research/core/Llava/llava/mm_utils.py", line 171, in process_images image = expand2square(image, tuple(int(x*255) for x in image_processor.image_mean)) AttributeError: 'NoneType' object has no attribute 'image_mean'
> 
> the code :
> 
> model_path = "./saved_model" model_name = get_model_name_from_path(model_path) tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, None, model_name)

The model path was "saved_model" I changed it to "llava-v1.5-7b-quilt-merged_new" and it worked
