### ISSUE TITLE
[Usage] RuntimeError: Error(s) in loading state_dict for Sequential:

### ISSUE THREAD

**Issue by unmo** [haotian-liu/LLaVA#665]
### Describe the issue

Issue:
I tried pretraining with the parameters specified in the following command.
```
deepspeed ./llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path liuhaotian/llava-v1.5-7b \
    --version plain \
    --data_path ./playground/data/LLaVA-Pretrain/testdata.json \
    --image_folder ./playground/data/LLaVA-Pretrain/images \
    --vision_tower liuhaotian/llava-v1.5-7b \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava1.5_finetune \
    --num_train_epochs 10 \
    --per_device_train_batch_size 6 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```
after that I tried finetuning describe under the command.
But it doesn't work.

Command:
```
deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path liuhaotian/llava-v1.5-7b \
    --version v1 \
    --data_path ./playground/data/LLaVA-Finetune/testdata.json \
    --image_folder ./playground/data/LLaVA-Finetune/images \
    --vision_tower liuhaotian/llava-v1.5-7b \
    --pretrain_mm_mlp_adapter ./checkpoints/llava1.5_finetune/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length False \
    --bf16 True \
    --output_dir ./checkpoints/llava1.5_finetune \
    --num_train_epochs 10 \
    --per_device_train_batch_size 6 \
    --per_device_eval_batch_size 6 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

Log: 
```
Traceback (most recent call last):
  File "/app/LLaVA/llava/train/train_mem.py", line 18, in <module>
    train()
  File "/app/LLaVA/llava/train/train.py", line 874, in train
    model.get_model().initialize_vision_modules(
  File "/app/LLaVA/llava/model/llava_arch.py", line 78, in initialize_vision_modules
    self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Sequential:
        size mismatch for 0.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for 0.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for 2.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for 2.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).
```

**Comment by unmo** [comment]
I want to finetune with the liuhaotian/llava-v1.5-7b model as a starting point with my custom data.

**Comment by haotian-liu** [comment]
Hi, please check out the latest code, and the docs for custom data finetuning. Thanks.

https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md

**Comment by unmo** [comment]
Thank you a lot your work. I have worked it. 
It seems that argument "pretrain_mm_mlp_adapter" does not contain in [finetune_task.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task.sh).
Does the task tuning train only LLM? And do images in the training dataset affect LLM training?

**Comment by unmo** [comment]
@haotian-liu 
I want to know how to learn my new image and text data and get new output.

Is that feasible with [finetune_task.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task.sh) or [finetune_task_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh)?

**Comment by haotian-liu** [comment]
> It seems that argument "pretrain_mm_mlp_adapter" does not contain in [finetune_task.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task.sh).
> Does the task tuning train only LLM? And do images in the training dataset affect LLM training?

Pretrain_mm_mlp_adapter name was a bit confusing due to the historic reasons. It actually means "pretrain**ed**_mm_mlp_adapter". Because LLaVA-1.5 already has the projector, we do not need that.

> I want to know how to learn my new image and text data and get new output. Can this be accomplished through LLM learn only?
> Is that feasible with [finetune_task.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task.sh) or [finetune_task_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh)?

You can freeze the projector if you want, by setting `--mm_projector_lr 0.` Note that the result may not be ideal as we find that finetuning projector is beneficial for a better performance.

**Comment by unmo** [comment]
Thank you. 
In the [finetune_task.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task.sh) and [finetune_task_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh), if I set --mm_projector_lr 0, mm_projector is not learned, and if I set it to a value greater than 0, mm_projector is learned.

**Comment by Jiushanhuadao** [comment]
> Thank you a lot your work. I have worked it. It seems that argument "pretrain_mm_mlp_adapter" does not contain in [finetune_task.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task.sh). Does the task tuning train only LLM? And do images in the training dataset affect LLM training?

Hi, I get the same question, like this:
`File "/llava/train/train_mem.py", line 13, in <module>
train()
File "/llava/train/train.py", line 1155, in train
model.get_model().initialize_vision_modules(
File "/llava/model/llava_arch.py", line 82, in initialize_vision_modules
self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'))
File "/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Sequential:
size mismatch for 0.weight: copying a param with shape torch.Size([5120, 1024]) from checkpoint, the shape in current model is torch.Size([0]).
size mismatch for 0.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([0]).
size mismatch for 2.weight: copying a param with shape torch.Size([5120, 5120]) from checkpoint, the shape in current model is torch.Size([0]).
size mismatch for 2.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([0]).`

I simulation the mm_projector, its shape like:
`
modules = [nn.Linear(1024, 5120)]
for _ in range(1, 2):
    modules.append(nn.GELU())
    modules.append(nn.Linear(5120, 1024))
mm_projector = nn.Sequential(*modules)

Sequential(
  (0): Linear(in_features=1024, out_features=5120, bias=True)
  (1): GELU(approximate='none')
  (2): Linear(in_features=5120, out_features=1024, bias=True)
)
`

but the shape of the weights "mm_projector.bin" is :
`
The shape of tensor model.mm_projector.0.weight is: torch.Size([5120, 1024])
The shape of tensor model.mm_projector.0.bias is: torch.Size([5120])
The shape of tensor model.mm_projector.2.weight is: torch.Size([5120, 5120])
The shape of tensor model.mm_projector.2.bias is: torch.Size([5120])
`
so do I need to edit the code in llava/model/multimodal_projector/builder.py? 
`
def build_vision_projector(config, delay_load=False, **kwargs):
    projector_type = getattr(config, 'mm_projector_type', 'linear')

    if projector_type == 'linear':
        return nn.Linear(config.mm_hidden_size, config.hidden_size)

    mlp_gelu_match = re.match(r'^mlp(\d+)x_gelu$', projector_type)
    if mlp_gelu_match:
        mlp_depth = int(mlp_gelu_match.group(1))
        modules = [nn.Linear(config.mm_hidden_size, config.hidden_size)]
        for _ in range(1, mlp_depth):
            modules.append(nn.GELU())
            modules.append(nn.Linear(config.hidden_size, config.hidden_size))
        return nn.Sequential(*modules)

    if projector_type == 'identity':
        return IdentityMap()

    raise ValueError(f'Unknown projector type: {projector_type}')
`

**Comment by Jiushanhuadao** [comment]
> Thank you a lot your work. I have worked it. It seems that argument "pretrain_mm_mlp_adapter" does not contain in [finetune_task.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task.sh). Does the task tuning train only LLM? And do images in the training dataset affect LLM training?

Hi, I get the same question, like this:
File "/llava/train/train_mem.py", line 13, in <module> train() File "/llava/train/train.py", line 1155, in train model.get_model().initialize_vision_modules( File "/llava/model/llava_arch.py", line 82, in initialize_vision_modules self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector')) File "/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for Sequential: size mismatch for 0.weight: copying a param with shape torch.Size([5120, 1024]) from checkpoint, the shape in current model is torch.Size([0]). size mismatch for 0.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([0]). size mismatch for 2.weight: copying a param with shape torch.Size([5120, 5120]) from checkpoint, the shape in current model is torch.Size([0]). size mismatch for 2.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([0]).

I simulation the mm_projector, its shape like:
`
modules = [nn.Linear(1024, 5120)]
for _ in range(1, 2):
modules.append(nn.GELU())
modules.append(nn.Linear(5120, 5120))
mm_projector = nn.Sequential(*modules)

Sequential(
(0): Linear(in_features=1024, out_features=5120, bias=True)
(1): GELU(approximate='none')
(2): Linear(in_features=5120, out_features=5120, bias=True)
)
`

and the shape of the weights "mm_projector.bin" is :
The shape of tensor model.mm_projector.0.weight is: torch.Size([5120, 1024]) The shape of tensor model.mm_projector.0.bias is: torch.Size([5120]) The shape of tensor model.mm_projector.2.weight is: torch.Size([5120, 5120]) The shape of tensor model.mm_projector.2.bias is: torch.Size([5120])

but it runs as an error, how do you fix it?

`def build_vision_projector(config, delay_load=False, **kwargs):
projector_type = getattr(config, 'mm_projector_type', 'linear')

if projector_type == 'linear':
    return nn.Linear(config.mm_hidden_size, config.hidden_size)

mlp_gelu_match = re.match(r'^mlp(\d+)x_gelu$', projector_type)
if mlp_gelu_match:
    mlp_depth = int(mlp_gelu_match.group(1))
    modules = [nn.Linear(config.mm_hidden_size, config.hidden_size)]
    for _ in range(1, mlp_depth):
        modules.append(nn.GELU())
        modules.append(nn.Linear(config.hidden_size, config.hidden_size))
    return nn.Sequential(*modules)

if projector_type == 'identity':
    return IdentityMap()

raise ValueError(f'Unknown projector type: {projector_type}')

**Comment by unmo** [comment]
Please share your scripts on thread.  This may be useful information.

**Comment by Byte-Coder2020** [comment]
thanks

**Comment by yhyang123** [comment]
> Hi, please check out the latest code, and the docs for custom data finetuning. Thanks.
> 
> https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md

I meet the same problem when I try to set my _pretrain_mm_mlp_adapter_ in the finetune step. How can I do if I want to finetune the model from the pretrained checkpoint?

**Comment by Ryoo72** [comment]
> > Hi, please check out the latest code, and the docs for custom data finetuning. Thanks.
> > https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md
> 
> I meet the same problem when I try to set my _pretrain_mm_mlp_adapter_ in the finetune step. How can I do if I want to finetune the model from the pretrained checkpoint?

did you happen to solve the problem?

**Comment by fangxin2github** [comment]
> > Hi, please check out the latest code, and the docs for custom data finetuning. Thanks.
> > https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md
> 
> I meet the same problem when I try to set my _pretrain_mm_mlp_adapter_ in the finetune step. How can I do if I want to finetune the model from the pretrained checkpoint?

did you happen to solve the problem?

**Comment by nassarofficial** [comment]
I know it's a bit late, but here's a solution to this problem since I've struggled a long time with this issue. The problem has to do with the order of loading weights. If you load the model using Deepseed and it's wrapped, the size would be 0. I found this function which is from hugging face api apparently, that gathers the parameters from deepspeed and allows you to load your state_dict in there.

https://github.com/alibaba/Pai-Megatron-Patch/blob/daf5c824104261730989e6338b851c8889b9605e/rlhf/deepspeed-chat/utils.py#L134

**Comment by HAOYON-666** [comment]
I have the same error,can you tell me how to deal it? thanks!!!
![Uploading error.png…]()

**Comment by HAOYON-666** [comment]
I have the same error,please tell me how to deal it,thanks!!!

**Comment by HAOYON-666** [comment]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/workspace/zhaoyong/tools/LLaVA/llava/train/train_xformers.py", line 13, in <module>
[rank0]:     train()
[rank0]:   File "/data/workspace/zhaoyong/tools/LLaVA/llava/train/train.py", line 914, in train
[rank0]:     model.get_model().initialize_vision_modules(
[rank0]:   File "/data/workspace/zhaoyong/tools/LLaVA/llava/model/llava_arch.py", line 97, in initialize_vision_modules
[rank0]:     self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector'))
[rank0]:   File "/home/user/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
[rank0]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank0]: RuntimeError: Error(s) in loading state_dict for Sequential:
[rank0]:        size mismatch for 0.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([0]).
[rank0]:        size mismatch for 0.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).
[rank0]:        size mismatch for 2.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([0]).
[rank0]:        size mismatch for 2.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).

**Comment by Ryoo72** [comment]
> [rank0]: Traceback (most recent call last): [rank0]: File "/data/workspace/zhaoyong/tools/LLaVA/llava/train/train_xformers.py", line 13, in [rank0]: train() [rank0]: File "/data/workspace/zhaoyong/tools/LLaVA/llava/train/train.py", line 914, in train [rank0]: model.get_model().initialize_vision_modules( [rank0]: File "/data/workspace/zhaoyong/tools/LLaVA/llava/model/llava_arch.py", line 97, in initialize_vision_modules [rank0]: self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector')) [rank0]: File "/home/user/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict [rank0]: raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( [rank0]: RuntimeError: Error(s) in loading state_dict for Sequential: [rank0]: size mismatch for 0.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([0]). [rank0]: size mismatch for 0.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]). [rank0]: size mismatch for 2.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([0]). [rank0]: size mismatch for 2.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).

don't use `from_pretrained` !

**Comment by HAOYON-666** [comment]
I am a beginner，can you tell me how to detailed deal it？thanks!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haotian-liu/LLaVA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月15日(星期二) 下午3:11
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [haotian-liu/LLaVA] [Usage] RuntimeError: Error(s) in loading state_dict for Sequential: (Issue #665)





  
[rank0]: Traceback (most recent call last): [rank0]: File "/data/workspace/zhaoyong/tools/LLaVA/llava/train/train_xformers.py", line 13, in [rank0]: train() [rank0]: File "/data/workspace/zhaoyong/tools/LLaVA/llava/train/train.py", line 914, in train [rank0]: model.get_model().initialize_vision_modules( [rank0]: File "/data/workspace/zhaoyong/tools/LLaVA/llava/model/llava_arch.py", line 97, in initialize_vision_modules [rank0]: self.mm_projector.load_state_dict(get_w(mm_projector_weights, 'mm_projector')) [rank0]: File "/home/user/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict [rank0]: raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( [rank0]: RuntimeError: Error(s) in loading state_dict for Sequential: [rank0]: size mismatch for 0.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([0]). [rank0]: size mismatch for 0.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]). [rank0]: size mismatch for 2.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([0]). [rank0]: size mismatch for 2.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([0]).
  
don't use from_pretrained !

**Comment by KaKa-101** [comment]
Does anybody know how to deal with this problem?
