### ISSUE TITLE
[Question] Unexpected low performance when evaluate LLaVA 1.0 on MME

### ISSUE THREAD

**Issue by henrycjh** [haotian-liu/LLaVA#669]
### Question
@haotian-liu 
Hi, thanks for your great work. I have encountered several questions that I cannot understand when I evaluate LLaVA 1.0 on MME. Hope you can help me figure it out. 

1. I evaluate the official checkpoint of LLaMA-2-13B-Chat, the result is 754. This is not expected because I finetune LLaMA-2-7B-Chat on LLaVA-Instruct-80K and get 1000.
2. Still the offical checkpoint of LLaMA-2-13B-Chat, but change the mm_projecter to the pretrained one, the result is 748, is that means in the finetuning process, the mm_projector has little impact?
3. I select around 600 images from the original dataset as a new dataset, and finetune LLaMA-2-7B-Chat on it (3 epoch, global batchsize is 32), and get around 1100 on MME, which is higher than the one that is finetuned on LLaVA-Instruct-80K(1 epoch, global batchsize is 128), is this normal ?

**Comment by haotian-liu** [comment]
Hi, this is mainly due to the v1.0 variants are not finetuned with VQA data, and the data distribution is biased towards Yes. Please try our latest v1.5 data mixture. Thanks.
