### ISSUE TITLE
evaluation on SQA very slow

### ISSUE THREAD

**Issue by JulioZhao97** [haotian-liu/LLaVA#67]
when I follow instructions run eval on SQA, the inference is very slow, however I find that web broswer demo is very fast.

**Comment by JulioZhao97** [comment]
![image](https://user-images.githubusercontent.com/40555727/234807055-aaae71fe-18b1-4c1f-a707-c27908d4eaf5.png)
I eval on 8 gpus and it cost nearly one hour to inference on ~5K

**Comment by mary-0830** [comment]
How can I use multiple cards for reasoning? @JulioZhao97

**Comment by haotian-liu** [comment]
Hi @mary-0830 
You can use our scripts for write yours for multiple GPU (batch inference): https://github.com/haotian-liu/LLaVA#evaluation-1

**Comment by mary-0830** [comment]
> Hi @mary-0830 You can use our scripts for write yours for multiple GPU (batch inference): https://github.com/haotian-liu/LLaVA#evaluation-1

ths!!
