### ISSUE TITLE
Inconsistent Special Token in Tokenizer

### ISSUE THREAD

**Issue by mingshanhee** [haotian-liu/LLaVA#70]
Hi, thanks for the great work in releasing the pre-trained model checkpoints. I tried using the provided model checkpoints (i.e. downloading and applying delta weights) and found some peculiar tokenizer settings regarding the special tokens. Here is a screenshot of the findings.

![image](https://user-images.githubusercontent.com/4586211/235049523-e019e859-3e6f-4d73-8a84-57dc513c035d.png)

As you can see from the screenshot, the unk_token in pretrained LLaVA model and finetuned LLaVA (for ScienceQA) model is actually different. From my understanding, the unk_token should be mapped to "<unk>", which is correctly reflected in the pretrained LLaVA model. However, the finetuned LLaVA (for ScienceQA) model is actually mapped to "</s>".

I am just wondering whether this inconsistency was intended and/or would it affect the model's performance?

**Comment by haotian-liu** [comment]
Hi @mingshanhee, thank you for your interest in our work.

Our SQA checkpoint was developed at an earlier stage, so it has some minor difference with the latest tokenizer configurations (e.g. `unk_token`, and it does not have `<im_start>` and `<im_end>`).

However, these shall not cause issues in evaluating the models, and we'll release the new checkpoints in a later release to fix all these issues.

Please let me know if this clarifies the doubts, and if there are other inference-related issues, please also let me know.  Thank you!

**Comment by haotian-liu** [comment]
Closing this as all tokenization related issues are fixed with [v1.0.0 release](https://github.com/haotian-liu/LLaVA/blob/main/docs/Release_Notes.md#7192023).
