### ISSUE TITLE
The composition of the visual instruction tuning datasets

### ISSUE THREAD

**Issue by Caizifen** [haotian-liu/LLaVA#702]
### Question

```
├── coco
│   └── train2017
├── gqa
│   └── images
├── ocr_vqa
│   └── images
├── textvqa
│   └── train_images
└── vg
    ├── VG_100K
    └── VG_100K_2
```
The above is the structure of the fine-tuning dataset provided. After I downloaded the data according to the README, the total number is not 665k, only 608k. Did I miss anything?

| coco | gqa | ocr_vqa | textvqa | VG_100K | VG_100K_2 | Total |
| --- | ---: | ---: | ---: | ---: | ---: | ---: |
| 118287 | 148854 | 207572 | 25119 | 64346 | 43903 | 608081 |

**Comment by jiaxiangc** [comment]
How to download ocr_vqa? what is pdb?

**Comment by haotian-liu** [comment]
Apologies for the confusion. I just re-calculated the exact samples in the dataset mixture, and we will update the paper to correct the sample count for RefCOCO and A-OKVQA. Note that the released dataset is correct, only the number reported in the table is off for these two datasets.

| Dataset       | Actual  | Paper |
|---------------|--------:|------:|
| LLaVA |  157712 |  158K |
| SG40k         |   40688 |   40K |
| VQA-v2        |   82783 |   83K |
| GQA           |   72140 |   72K |
| OKVQA         |    8998 |    9K |
| OCRVQA       |   80000 |   80K |
| A-OKVQA       |   **66160** |   ~~50K~~ **66K** |
| TextCaps      |   21953 |   22K |
| RefCOCO       |   **48447** |   ~~30K~~ **48K** |
| VG            |   86417 |   86K |
| **Total**     | **665298** | **665K** |

**Comment by Cooperx521** [comment]
@Caizifen Hello, I'm also confused about the difference between README and the table mentioned by @haotian-liu. Have you clarified it? And does the data mentioned in the README have contained ShareGPT?

**Comment by 421zuoduan** [comment]
> How to download ocr_vqa? what is pdb?

Hi, I want to know if you have solved this problem? i have encountered the same problem

**Comment by zxdscsfm** [comment]
@421zuoduan Hi, I want to know if you have solved this problem? i have encountered the same problem

**Comment by 421zuoduan** [comment]
@zxdscsfm Hi, you can find the solution [here](https://github.com/haotian-liu/LLaVA/issues/593). From my notes, I think I downloaded OCR_VQA_200K and revised `gif` file extensions to `jpg` manually, then it worked.

**Comment by zxdscsfm** [comment]
@421zuoduan Thanks! I successfully solved this problem
