### ISSUE TITLE
[Question] Issue with get_modality_length_grouped_indices when using only multimodal input

### ISSUE THREAD

**Issue by mjkmain** [haotian-liu/LLaVA#715]
### Question

Hello @haotian-liu , 
I've been working on visual instruction tuning using image-text pair data and came across the following error:

```bash
  File "/LLaVA/llava/train/llava_trainer.py", line 127, in __iter__
    indices = get_modality_length_grouped_indices(self.lengths, self.batch_size, self.world_size, generator=self.generator)
  File "/LLaVA/llava/train/llava_trainer.py", line 64, in get_modality_length_grouped_indices
    lang_indices, lang_lengths = zip(*[(i, -l) for i, l in enumerate(lengths) if l < 0])
ValueError: not enough values to unpack (expected 2, got 0)
```

Upon inspecting the code, I believe the issue arises from the function get_modality_length_grouped_indices:

```python
def get_modality_length_grouped_indices(lengths, batch_size, world_size, generator=None):
    mm_indices, mm_lengths = zip(*[(i, l) for i, l in enumerate(lengths) if l > 0])
    lang_indices, lang_lengths = zip(*[(i, -l) for i, l in enumerate(lengths) if l < 0])

    assert len(mm_indices) > 0, "Should have at least one multimodal sample."
    assert len(lang_indices) > 0, "Should have at least one language sample."
```

It seems that the implementation requires at least one text-to-text data sample, leading to the error when only using multimodal data. Is there a particular reason for this design choice? I'm specifically interested in multimodal data (image, text) to text tasks, and I'm wondering how to proceed. One solution I considered was adding at least one text-to-text data sample. Would this be the best approach, or is there a more optimal solution?

Thank you for your time and guidance.

**Comment by haotian-liu** [comment]
Hi, you can simply set that option to `False`. Or you can pull the latest repo, as I have just updated the repo in https://github.com/haotian-liu/LLaVA/commit/a546269905945b732289c19c764fec34f4338989 so that this is handled more gracefully. Thanks.

**Comment by mjkmain** [comment]
Thank you !
