### ISSUE TITLE
[Question] Can you clarify the intended behavior of `lora_enable` and `freeze_backbone`?

### ISSUE THREAD

**Issue by ahmedhshahin** [haotian-liu/LLaVA#723]
### Question

I am finding these two flags a bit confusing. Specifically, what will happen if `lora_enable=True` and `freeze_backbone=False`? Is that full fine-tuning or LoRA fine-tuning? If it is the latter, then what will happen if we set `freeze_backbone=True` and `lora_enable=True`? 

Thanks

**Comment by haotian-liu** [comment]
Hi @ahmedhshahin 

The flag `freeze_backbone` is not for training purposes, it is just for saving the memory for debugging the code on a single GPU.

If there is a particular reason for using this flag to train the model, please let me know, thanks.

**Comment by ahmedhshahin** [comment]
@haotian-liu 
Thanks for the clarification. I imagine you can use it when you are training the projector network only, so you are freezing the LLM and the visual encoder, right?

**Comment by haotian-liu** [comment]
For that, you should use `--tune_mm_mlp_adapter True`. The name may be a bit confusing, but it will freeze the language model / vision encoder and unfreeze the projector. It does not freeze the lora weights.

https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/pretrain.sh#L11C5-L11C5

**Comment by haotian-liu** [comment]
By default the vision encoder is always frozen. So you can just use the LoRA scripts.

https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh
https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh

**Comment by ahmedhshahin** [comment]
Great, Thanks! That's very helpful.

**Comment by St3p99** [comment]
> By default the vision encoder is always frozen. So you can just use the LoRA scripts.
> 
> https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh

You're right! the vision encoder is always frozen, but the projector/adapter is not.

So, if you use the following FT script you're training both projector and LLM. However, since tune_mm_mlp_adapter is False the mm_projector.bin will not be saved! 

[https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh)

**Comment by SFaegheh** [comment]
What if we want to finetune both the Vision encode and projector?

**Comment by YoungLer** [comment]
> What if we want to finetune both the Vision encode and projector?

I have the same question. Maybe we can refer to:  [LLaMA-Factory/issues/2046](https://github.com/hiyouga/LLaMA-Factory/issues/2046) ,setting the parameter `--lora_target`  if you want to use lora, setting `--additional_target` if you want to use full parameter fine-tuning.
I am not sure if it is correct. If you have any ideas, please feel free to discuss. Thanks.
