### ISSUE TITLE
[Question] How to load finetuned LoRA and projector model parts  from a checkpoint?

### ISSUE THREAD

**Issue by ahmedhshahinn** [haotian-liu/LLaVA#733]
### Question
After finetuning the LLM (using LoRA) and the `mm_projector`, how to load these weights for inference?
My understanding is that this is done by the function[`load_pretrained_model`](https://github.com/haotian-liu/LLaVA/blob/785f766fcddc86ffeaa62cd51cf7834a11c04e6d/llava/model/builder.py#L26), specifically[`this if condition`](https://github.com/haotian-liu/LLaVA/blob/785f766fcddc86ffeaa62cd51cf7834a11c04e6d/llava/model/builder.py#L49). However, this doesn't load the `mm_projector_weights`, right?

Happy to submit a PR fix if my understanding is correct.

**Comment by haotian-liu** [comment]
Hi. The projector weights are included in `non_lora_trainables.bin` and are loaded here: https://github.com/haotian-liu/LLaVA/blob/785f766fcddc86ffeaa62cd51cf7834a11c04e6d/llava/model/builder.py#L72-L75
