### ISSUE TITLE
We know that 7b is coming soon but is there a estimation of when?

### ISSUE THREAD

**Issue by gordonhu608** [haotian-liu/LLaVA#74]
As title. Since 7b is more memory friendly for researchers to play and study with.

**Comment by vateye** [comment]
Hi, I find mPLUG-Owl is actually a 7B model which is shown to perform better than LLaVA 13B with more emergent abilities. Maybe you can try that.

**Comment by haotian-liu** [comment]
@gordonhu608 What about now? :)

Please checkout the instruction [here](https://github.com/haotian-liu/LLaVA#llava-7b).

**Comment by gordonhu608** [comment]
> @gordonhu608 What about now? :)
> 
> Please checkout the instruction [here](https://github.com/haotian-liu/LLaVA#llava-7b).

Thank you!

**Comment by gordonhu608** [comment]
> Hi, I find mPLUG-Owl is actually a 7B model which is shown to perform better than LLaVA 13B with more emergent abilities. Maybe you can try that.

This is very helpful, thank you, btw we find us both from UCSD
