### ISSUE TITLE
Hello, I would like to ask, if you want to use LLaVA-1.5 for inference without training, do you need to download the corresponding Projector weights after downloading checkpoints?

### ISSUE THREAD

**Issue by test16553** [haotian-liu/LLaVA#752]
### Describe the issue

Hello, I would like to ask, if you want to use LLaVA-1.5 for inference without training, do you need to download the corresponding Projector weights after downloading checkpoints?

**Comment by haotian-liu** [comment]
Hi, you do not need to download the projectors. They should NOT be used in any case, unless you want to *reproduce* LLaVA-1.5. Thanks.
