### ISSUE TITLE
[Feature request] Use LLaVA to recognise one specific person. 

### ISSUE THREAD

**Issue by pbenaim** [haotian-liu/LLaVA#753]
### feature

LLaVA is very accurate to analyse one picture 👌

I love it, because we can ask, any questions, in an other language than English, like me in French 😍

So, I think is it possible to recognise one specific person after some trainings. 

So me question is, because I haven't any idea, how to do that?

Any suggestions? Or is it impossible in the actual state of LLaVA... 😭

**Comment by haotian-liu** [comment]
That's totally possible, and you can do that by creating a custom dataset for that and finetuning LLaVA-1.5 on that dataset.

https://github.com/haotian-liu/LLaVA/blob/main/docs/Finetune_Custom_Data.md
