### ISSUE TITLE
What does this `sep` do in your code?

### ISSUE THREAD

**Issue by LetsGoFir** [haotian-liu/LLaVA#762]
Thanks for your wonderful work!
Could you please tell me what does it do? I have no idea at all.
https://github.com/haotian-liu/LLaVA/blob/eabb7102ea4c3c7dca5d34988eea6bf441920b6f/llava/train/train.py#L566

**Comment by haotian-liu** [comment]
You can imagine that this leverages the model's raw text completion capability on the large scale pretraining:

Given: <IMAGE>
The model predicts: <DESCRIPTION>

By doing this, we align <IMAGE> to the language model's distribution.

**Comment by LetsGoFir** [comment]
@haotian-liu Got it! I have this confusion because I have many long data and want to truncate them.
Then I should add it first and truncate, I think
