### ISSUE TITLE
Rreasonable loss of pre-training (Stage-1) loss.

### ISSUE THREAD

**Issue by zhengsipeng** [haotian-liu/LLaVA#764]
### Question

Thank you for your wonderful work, 
May I know the reasonble loss of LLaVA during the 1-st stage of pre-training?

**Comment by haotian-liu** [comment]
Hi, we have provided all training logs in MODEL ZOO for LLaVA-1.5. You can check out the figure.

https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md#llava-v15
Training logs: [wandb](https://api.wandb.ai/links/lht/6orh56wc).

**Comment by zhengsipeng** [comment]
Thanks!
