### ISSUE TITLE
[Question] Enhance LLaVA by new GPT-4V API

### ISSUE THREAD

**Issue by alfredplpl** [haotian-liu/LLaVA#766]
### Question

Hello,

Can we enhance this model by GPT-4V API?

For example, I got the result of the image captioning:
```txt
Descrive this image in very highly detail.
```
![14CF3AC8-FDB6-479D-9A3B-C6DEA84AA7DC_4_5005_c](https://github.com/haotian-liu/LLaVA/assets/3625196/aaccb97d-39b0-4970-9e0f-7bc0514ea968)
```txt
This image depicts a cartoon-style female character with distinct anthropomorphic features, primarily reminiscent of a rabbit. She has a vibrant design with a color scheme dominated by shades of green. Here are the detailed features:\n\n- **Head**: The character has large, expressive eyes with orange and yellow irises, and her face has a happy and friendly expression. There are two large green rabbit ears with a lighter green interior sticking up from her head. She has short green hair with lighter green highlights, suggesting a stylized bob haircut. The character sports a small green bow on her collar.\n\n- **Outfit**: She is wearing a short-sleeved white blouse with puffed sleeves accented with frills at the edges. Over the blouse, she wears green overalls with short pants. The overalls have pink buttons at the front and a purple hem around the leg openings. Underneath the collar of the blouse, a green ribbon with a bow is visible, providing a complementary accent to the overalls.\n\n- **Tail**: Protruding from her lower back is a long, bushy tail, colored in the same green shades as her hair and ears, suggesting a rabbit's tail that matches her character design.\n\n- **Legs and Footwear**: The character has bare legs, with simple skin shading that includes a barely noticeable blush of the knees and ankles, suggesting a softness. On her feet, she wears a pair of boots that match her overall color scheme — predominantly green, with pink-purple accents around the soles and a pink button on the side of each boot where a spiky leaf-like design protrudes, echoing a plant or rabbit-ear motif.\n\nThe character is standing in a frontal position with her arms relaxed at her sides, giving off a cheerful vibe. The background of the image is blank and white, drawing focus entirely to the character. The art style appears to be inspired by Japanese animation and could likely be associated with a character from manga, anime, or a video game.
```

Thanks in advance.

**Comment by tingxueronghua** [comment]
Do you mean distilling GPT-4V? I guess it is definitely beneficial to LLaVA. 

LLaVA's OCR ability is still weak. But I am not sure whether this is due to the vision tower or the training data.

**Comment by alfredplpl** [comment]
Yes, I am considering doing something similar to distillation. It might be good to do fine-tuning on my own, but I thought it might be better to have it done officially, given the opportunity.

**Comment by alfredplpl** [comment]
For example, the dataset is here:
https://huggingface.co/datasets/alfredplpl/anime-with-gpt4v-caption-for-lora

**Comment by tingxueronghua** [comment]
oh, that is an interesting dataset. I think you can just design a series of prompts to instruct the GPT-4V to generate captions, and train the llava on such visual instruction following dataset.

**Comment by alfredplpl** [comment]
I could create a lora adaptor with A6000x2.
Then, I inference this image with the lora.

![cute195](https://github.com/haotian-liu/LLaVA/assets/3625196/48153a11-1c04-4ed0-8a24-4f844900a61c)

"The image features a young girl with a cute and playful appearance. She is wearing a white and pink outfit, which includes a pink jacket and a pink bow in her hair. The girl is also wearing a backpack, which is visible on her back.  Additionally, there is a stuffed bunny, possibly a stuffed animal, sitting on her shoulder. The scene has a whimsical and charming vibe, with the girl's attire and the presence of the stuffed bunny creating a sense of innocence and youthfulness."

I wanna use GPT-4V more.

**Comment by haotian-liu** [comment]
Thank you for the suggestions. We are working on planning such a dataset / model release. Unfortunately the GPT-4V API access is still capped at 100 requests, so we are preparing for a release after we are able to create a properly designed dataset with a broad knowledge coverage.

**Comment by haotian-liu** [comment]
@alfredplpl 

How would you like this one?

> This is a beautifully illustrated anime-style image featuring a young girl with a cute and whimsical aesthetic. The girl has pale skin and short, wavy blonde hair that falls just past her shoulders. Her hair is adorned with two large, circular pink accessories that resemble bows, one on the left side and the other on the right. She has large, expressive purple eyes with multiple shades, giving her a wide-eyed and innocent appearance. Her cheeks are adorned with two small, pink blush marks, and her small, straight nose is centered between her two eyes. The girl is wearing a loose-fitting, cream-colored jacket with a floral pattern that includes pink, orange, and green hues, along with small, white hearts scattered throughout. The jacket has a slightly ruffled hem and appears soft and comfortable. On her head, the girl is wearing a small, white animal-like hat that resembles a bunny or a small bear, with a pink inner lining and a black pompom at the top. In her arms, the girl is holding a small, white creature that resembles a chubby, pink bunny or a white, animal-like plushie with pink ears and a small, black nose. The creature has a content expression and is gazing up at the girl with a small, black dot representing an eye. The background is minimal, with a plain white rectangle that has a few simple, cute illustrations scattered around, including small, white flowers and a small, yellow star. The overall color palette is soft and warm, with a dominant use of pastel colors that gives the image a gentle and soothing feel.

**Comment by alfredplpl** [comment]
@haotian-liu It seems nice. It can annotate more accurately than before fine-tuning. For example, it used to make more mistakes with the colors of clothes and eyes, but now it does so less frequently.

**Comment by gyupro** [comment]
@alfredplpl  I was just wondering, I am doing similar kind of work to this, don't you think training vision tower would help to enhance these kind of tasks? Vision tower has been trained on a real world image, feeding these images to LLAVA would be more improved by doing so

**Comment by alfredplpl** [comment]
@gyupro I agree. It seems that photographs are predominantly used for learning, with fewer paintings being utilized. This pink image is a generated one and does not have copyright issues. It appears to be suitable for learning purposes.

**Comment by HenryHZY** [comment]
Great idea. I think there is a lot of researchers working on it. Just wait for something like ShareGPT-Vision.

**Comment by gyupro** [comment]
@alfredplpl , I've been pondering over this labor-intensive issue and recently discovered the image quality from DALLE-3 provided by [GPT4](https://huggingface.co/datasets/laion/dalle-3-dataset). If we gather these images and prompts related to manga or anime, we could save considerable time and cut costs effectively. Does anyone have an estimate on how many images might influence the weight of the VIT encoder?

**Comment by alfredplpl** [comment]
ShareGPT4V is released. So, The goal is achieved. I will close this issue.
