### ISSUE TITLE
Clarification on pretrain_mm_mlp_adapter

### ISSUE THREAD

**Issue by csvlrs-lak** [haotian-liu/LLaVA#773]
### Question

I've come across this argument called pretrain_mm_mlp_adapter in finetuning script,  I'd like to better understand its purpose and why it's being used.

**Comment by devaansh100** [comment]
This flag is used to give the path to the .bin file for the weights mm_mlp_adapter trained on image-text pairs in the first stage. This is loaded and fine-tuned in the second stage

**Comment by csvlrs-lak** [comment]
Thanks @devaansh100 for you response, I have a question regarding the fine-tuning of the LLaVA-13B model with custom data. I have made the following changes to the provided script [finetune_lora](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh) 

1. Changed the **model_name_or_path** from lmsys/vicuna-13b-v1.5 to liuhaotian/llava-v1.5-13b.
2. Adjusted the values of **data_path** and **image_folder** to point to my custom data.

However, I'm uncertain about which mm_projector.bin(**pretrain_mm_mlp_adapter** argument) file should be used in this fine-tuning process. Do I need to download it separately, and if so, from where?"

**Comment by devaansh100** [comment]
Maybe [this thread](https://github.com/haotian-liu/LLaVA/issues/767) might help you

> download it separately

I think this model has not used lora(please check!), in which case the `mm_projector.bin` can be downloaded separately from [here](https://huggingface.co/liuhaotian/llava-v1.5-13b/tree/main).

**Comment by csvlrs-lak** [comment]
Thank you @devaansh100

**Comment by aneet-javis** [comment]
@csvlrs-lak So for finetuning on our own custom data, should the model_path be set to lmsys/vicuna-13b-v1.5 or liuhaotian/llava-v1.5-13b? And what is the difference in terms of training/memory between the two? Thanks
