### ISSUE TITLE
[Question] Where is the function body for model.generate()?

### ISSUE THREAD

**Issue by jameszhou-gl** [haotian-liu/LLaVA#782]
### Question

Hi authors, 
Thanks for your great work.

When I'm delving into the code implementation, I'm really curious where I can find the model.generate()?
For example, in [#L76](https://github.com/haotian-liu/LLaVA/blob/8467850a63aa0d6f47aa150c53aca4751f0d3d14/llava/eval/model_vqa_science.py#L76)
```python
 with torch.inference_mode():
      output_ids = model.generate(
          input_ids,
          images=images,
          do_sample=True if args.temperature > 0 else False,
          temperature=args.temperature,
          max_new_tokens=1024,
          use_cache=True,
          stopping_criteria=stopping_criteria,
      )
```
and such model is an instance from class [LlavaLlamaForCausalLM](https://github.com/haotian-liu/LLaVA/blob/8467850a63aa0d6f47aa150c53aca4751f0d3d14/llava/model/language_model/llava_llama.py#L40).

Couldn't find the corresponding generate() function.

**Comment by haotian-liu** [comment]
Please check out the official documentation from transformers. It's a subclass of GenerationMixin. Thanks.

https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationMixin

**Comment by DnkNju** [comment]
very grateful :)
I searched the Chinese community for this question for months with no results until I tried google...
