### ISSUE TITLE
[Question] extract_video_frames.py missing for SEED dataset

### ISSUE THREAD

**Issue by chae-won-kim** [haotian-liu/LLaVA#795]
### Question

Hi,

You guys mentioned in [evaluation.md](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md#seed-bench) that you provide the code `extract_video_frames.py` to extract from videos, but the file is nowhere to be found. Can you please provide the code? Thanks!

**Comment by chae-won-kim** [comment]
I found in under the eval.zip file the authors provided for those who need it

**Comment by ge-bin-hui** [comment]
@chae-won-kim Hey bro! I still can not find the eval.zip, could you offer me the url?

**Comment by haiduo** [comment]
Here [extract_video_frames.py](https://drive.google.com/file/d/1atZSBBrAX54yYpxtVVW33zFvcnaHeFPy/view)
