### ISSUE TITLE
[Question] Will randomly shuffling the data sample order in llava_v1_5_mix665k.json affect the final model's performance when fine-tuning?

### ISSUE THREAD

**Issue by uyo9ko** [haotian-liu/LLaVA#803]
### Question

Will randomly shuffling the data sample order in llava_v1_5_mix665k.json affect the final model's performance when fine-tuning?
Is the data order in llava_v1_5_mix665k.json intentionally set?

**Comment by uyo9ko** [comment]
sorry, i find it is random shuffled

**Comment by jiazhen-code** [comment]
They don't seem to have been randomly shuffled.

```python
# data is read from that json.
for s, d in enumerate(data):
    if 'ocr' in d['image']:
        print(s)
```

Result:
![image](https://github.com/user-attachments/assets/b161b07b-bd2b-44d5-bd26-91cfac019aa0)
