### ISSUE TITLE
error when loading "CLIP"vision encoder

### ISSUE THREAD

**Issue by zht8506** [haotian-liu/LLaVA#807]
![image](https://github.com/haotian-liu/LLaVA/assets/81303574/8af401f4-f4dd-47da-8fb5-d11333621893)
I use these code to load the weight, "LLaVA-main/liuhaotian/llava-v1.5-7b" and "LLaVA-main/openai/clip-vit-large-patch14-336". But i meet errors, as follow:
![image](https://github.com/haotian-liu/LLaVA/assets/81303574/ba5eaa2b-cc24-458b-b968-7b91d7efed89)
how to solve this issue? thank you.

**Comment by Norrrrrrr-lyn** [comment]
How did you solve the issue? I've encountered the same issue.
