### ISSUE TITLE
[Question] The processing method on bounding box of VG and RefCOCO are different?

### ISSUE THREAD

**Issue by Richar-Du** [haotian-liu/LLaVA#822]
### Question

I have seen the issue in https://github.com/haotian-liu/LLaVA/issues/606, and I agree that the processing method of VG is the same as stated in https://github.com/haotian-liu/LLaVA/issues/606#issuecomment-1774076879. However, this processing method does not work for RefCOCO, following is an image in RefCOCO processed by expand2square:
<img width="452" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/55051961/b366bcff-f4c3-4f4a-92df-3893511ef9a5">

And the following is the same image without processing by expand2square:
<img width="544" alt="image" src="https://github.com/haotian-liu/LLaVA/assets/55051961/433c0e81-9e21-46f4-b7e3-93bb94772da8">
It seems that the second one is correct.

So I wonder if the processing methods used in RefCOCO and VG are different.

**Comment by Richar-Du** [comment]
I misunderstand it, sorry for the interrupt.

**Comment by NorthSummer** [comment]
Hi, I still haven't got it; the normalized [xa, ya, xb, yb] seems correct for VG data after padding, but is not correct for coco data after padding, right?

**Comment by boyugou** [comment]
> Hi, I still haven't got it; the normalized [xa, ya, xb, yb] seems correct for VG data after padding, but is not correct for coco data after padding, right?

Is it true? I also haven't got whether the normalized coordinates in llava665k are adjusted for padding or not

**Comment by lzy37ld** [comment]
Same

**Comment by MonolithFoundation** [comment]
It's totally messed up with the coordinates. we need better do no resize no padding and keeping the ratio

**Comment by boyugou** [comment]
> It's totally messed up with the coordinates. we need better do no resize no padding and keeping the ratio

I remember the author clarified the question somewhere. So I did understand the process later then.

**Comment by MonolithFoundation** [comment]
Can u explain on how: the cooridnates processed in text ? (normalized into 0-1? according to what?)  The image actually being resized and padded.

For reference, qwen2 vl simply uses original x1y1x2y2 format without scaling, and original WH of raw image. Make sense more.

**Comment by boyugou** [comment]
> Can u explain on how: the cooridnates processed in text ? (normalized into 0-1? according to what?) The image actually being resized and padded.
> 
> For reference, qwen2 vl simply uses original x1y1x2y2 format without scaling, and original WH of raw image. Make sense more.

I figured it out once and did the reversion for the data. But unfortunately I find I've deleted the related code. I'm sure Haotian clarified the image resizing somewhere in an issue, where I get to know how to deal with it.

**Comment by MonolithFoundation** [comment]
Did u real understand how does it actually processed?

**Comment by boyugou** [comment]
> Did u real understand how does it actually processed?

ofc? Otherwise why did I say 'I figured it out once and did the reversion for the data'

**Comment by MonolithFoundation** [comment]
I mean, did u know how does LLava treated the input with resized and padding
