### ISSUE TITLE
[Usage] I cannot load the finetuned model with my own language model

### ISSUE THREAD

**Issue by Eric-is-good** [haotian-liu/LLaVA#850]
### Describe the issue

I use a llama2 ( Different sizes from yours ) as the language model, after finetuning , i cannot load the finetuned model , i use the  cli,py ,get this:
![image](https://github.com/haotian-liu/LLaVA/assets/73528862/54bc612f-2ea5-4a67-9b7e-c8a923f4f3f9)

tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)

function load_pretrained_model failed
image_processor is none makes NoneType error

**Comment by YiDa858** [comment]
Hi @Eric-is-good, I'm new in this field. I now have a dataset for fine-tuning the llava, but I don't sure if I need to pre-train as [this](https://github.com/haotian-liu/LLaVA#pretrain-feature-alignment), or I just need to run the [finetune script](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune.sh). Looking forward to your reply!

**Comment by Eric-is-good** [comment]
> Hi @Eric-is-good, I'm new in this field. I now have a dataset for fine-tuning the llava, but I don't sure if I need to pre-train as [this](https://github.com/haotian-liu/LLaVA#pretrain-feature-alignment), or I just need to run the [finetune script](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune.sh). Looking forward to your reply!

you need pre-train and finetune both

**Comment by YiDa858** [comment]
Thank you for your reply! I also want to know what the difference is between pre-trained and fine-tuned datasets? It looks like they have the same structure.

**Comment by Eric-is-good** [comment]
> Thank you for your reply! I also want to know what the difference is between pre-trained and fine-tuned datasets? It looks like they have the same structure.

pre-trained is picture and caption, finetune is picture and dialogue with tasks. the structures of them are the same.

**Comment by YiDa858** [comment]
You made me understand at once. Thank you!

**Comment by yiyiwwang** [comment]
> ### Describe the issue
> I use a llama2 ( Different sizes from yours ) as the language model, after finetuning , i cannot load the finetuned model , i use the cli,py ,get this: ![image](https://private-user-images.githubusercontent.com/73528862/285347389-54bc612f-2ea5-4a67-9b7e-c8a923f4f3f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDY1ODUsIm5iZiI6MTcxNjk0NjI4NSwicGF0aCI6Ii83MzUyODg2Mi8yODUzNDczODktNTRiYzYxMmYtMmVhNS00YTY3LTliN2UtYzhhOTIzZjRmM2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAxMzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZjNkNGQ3NDEzN2Y1Mzc5NWE0YTg2MGU1MGJjZWNhMWNhZGIwZGNhYmY3OWZhOGZiNzQ4YzY0NTZkYTQ0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.muCpk5HfUWc055XirY59DsEk5uwB-q5j7gLI7xQ3_4g)
> 
> tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
> 
> function load_pretrained_model failed image_processor is none makes NoneType error

Hello, have you solved this problem? Could you please give me some advice? Thank you very much.
