### ISSUE TITLE
[Question] finetune stage freeze the linear layer? Not consistent with what the paper stated. 

### ISSUE THREAD

**Issue by fredshentu** [haotian-liu/LLaVA#856]
### Question

On the paper it seems the linear layer will be fine-tuned e2d during the instructed finetune phase 
https://arxiv.org/pdf/2304.08485.pdf (see the section4.2 Stage 2: Fine-tuning End-to-End....)
However, on the code it seems the linear layer is always frozen except at the pre-training phase. https://github.com/haotian-liu/LLaVA/blob/2ca20de1ca76d7d121be5a53f8a46c6bef47a9cb/llava/train/train.py#L53

Does anyone know why there is such a discrepancy? Why the code is not aligned with the paper? Will freezing the linear layer after the projection improve the model's final performance?

**Comment by zackschen** [comment]
I was wondering about this too, may I ask how you ended up understanding it?
