### ISSUE TITLE
[BUG] 'group_by_modality_length' argument ineffective

### ISSUE THREAD

**Issue by MengLcool** [haotian-liu/LLaVA#857]
Thanks for your great work.

It seems a bug in https://github.com/haotian-liu/LLaVA/blob/2ca20de1ca76d7d121be5a53f8a46c6bef47a9cb/llava/train/train.py#L656

This will lead to the 'group_by_modality_length' argument becoming ineffective, as 'images' is never appears in the *raw* JSON file (self.list_data_dict).

We found that this will lead to some performance drop.

Looking forward to your response!

**Comment by haotian-liu** [comment]
Thanks, this was introduced in PR #694, which is just reverted in #866. Thanks!
