### ISSUE TITLE
What is Lighting V1.1?

### ISSUE THREAD

**Issue by CyberTimon** [haotian-liu/LLaVA#86]
I didn't saw any informations on it how it differs from llava 7b v0. 
Can anyone please explain this?

**Comment by haotian-liu** [comment]
Hi @CyberTimon, LLaVA-Lightning V1.1 has three differences with LLaVA-7B-v0 (mainly in training):

1. Data.  We create a 558K concept-balanced subset from LAION/SBU/CC, which is a much larger concept converage than the original CC data, while the amount samples are roughly the same (558K / 595K), ensuring a similar cost of pretraining. Similarly, we filtered 80K instruction tuning data, composed of 40K conversation and 40K reasoning from our LLaVA-Instruct-158K.
2. Training.  Instruction tuning stage is only performed for one epoch for Lightning, and given the smaller dataset, it is 4x faster training than LLaVA-7B-v0.
3. Base model.  We use Vicuna-1.1 as the base model for Lightning, and we will use Vicuna V1 series for future releases.  The prompt templates are slightly modified to a more standard format.
With more concept coverage, smaller data, and fewer training epochs, our Lightning model achieves a similar performance to LLaVA-7B-v0, while keeping the cost down to as few as 3 hours training with $40.

Hope this clarifies the question.  We are also working on a MODEL_ZOO page to clarify these differences in training data/schedule/cost, and will also add to our paper in the revision.  Thank you, and please let me know if you have further questions.

**Comment by CyberTimon** [comment]
Thank you for the great answer! This answers my question.

**Comment by Tongcheng** [comment]
Question for Lightning 7B, in apply_delta, should we use LLaMA-7B as base or Vicuna-7B (with Vicuna Delta already applied) as base? Thank you.

**Comment by haotian-liu** [comment]
Please use the LLaMA-7B as the base. We train based on Vicuna-7B, but release the delta from LLaMA, so that people do not need to convert the Vicuna first in order to use our checkpoint. Thanks.
