### ISSUE TITLE
[Usage] Poor/Random ouput after training and finetuning

### ISSUE THREAD

**Issue by anonymous-atom** [haotian-liu/LLaVA#867]
Issue:
My custom trained and fintuned LLaVA is producing very random and poor ouput.
I tried to first train the LLaVA model on custom data using [pretrain.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/pretrain.sh) script and then finetuned it using this script [finetune_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh). Then I used the trained lora weights using the command below:
`python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-v1-0719-336px-lora-vicuna-13b-v1.3 --model-base lmsys/vicuna-13b-v1.3`

Also sometime the model is not producing any output even.

I had 6000 entries in my custom dataset.
Command:
```
python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path liuhaotian/llava-v1-0719-336px-lora-vicuna-13b-v1.3 --model-base lmsys/vicuna-13b-v1.3
```

Screenshots:
![image](https://github.com/haotian-liu/LLaVA/assets/74659873/a47ba1ad-747c-4beb-ab3a-51498b044bb4)

**Comment by anonymous-atom** [comment]
@haotian-liu can you look into this once ?

**Comment by anonymous-atom** [comment]
Sorry for mentioning your usernames like this but could you let me know what could have gone wrong ? I still can't figure out this ?
@henrycjh @FHL1998

**Comment by FHL1998** [comment]
> Sorry for mentioning your usernames like this but could you let me know what could have gone wrong ? I still can't figure out this ? @henrycjh @FHL1998

I highly doubt that 6000 samples are enough for the pertaining process, you may try to fine-tune your own dataset based on the released pre-trained checkpoints.

**Comment by anonymous-atom** [comment]
Oh cool, so I should just finetune on my custom dataset right ? that's what you mean ? @FHL1998

**Comment by CrazyBrick** [comment]
> > Sorry for mentioning your usernames like this but could you let me know what could have gone wrong ? I still can't figure out this ? @henrycjh @FHL1998
> 
> I highly doubt that 6000 samples are enough for the pertaining process, you may try to fine-tune your own dataset based on the released pre-trained checkpoints.

@FHL1998 Hi,I have 6k samples for finetuning.I also get poor results.Do you have any idea?
![Screenshot from 2023-12-01 16-40-26](https://github.com/haotian-liu/LLaVA/assets/61942251/a02efe54-7fd6-4375-a758-f44bf0a68a6d)

**Comment by rohitpanjwani03** [comment]
Hi guys, I am on colab running it on A100 and trying to fine-tuned using the below code, facing error like ./checkpoint or train_men.py and other train.py files  

My code
```%cd /content
!git clone https://github.com/haotian-liu/LLaVA.git
%cd /content/LLaVA
!pip install -q gradio .

!bash /content/LLaVA/scripts/v1_5/finetune.sh```


Can you guys help me with the correct way to fine-tune it?

**Comment by CrazyBrick** [comment]
> Hi guys, I am on colab running it on A100 and trying to fine-tuned using the below code, facing error like ./checkpoint or train_men.py and other train.py files
> 
> My code
> 
> ```
> !git clone https://github.com/haotian-liu/LLaVA.git
> %cd /content/LLaVA
> !pip install -q gradio .
> 
> !bash /content/LLaVA/scripts/v1_5/finetune.sh```
> 
> 
> Can you guys help me with the correct way to fine-tune it?
> ```

Have you downloaded the model and changed the file location in script?

**Comment by rohitpanjwani03** [comment]
No I haven't and didn't made any changes to the file location in the script. 
Thank you so much; I will try to make it work and run as suggested.

**Comment by ggcr** [comment]
Just in case someone is having problems during inferece; if you have a script that uses `/llava/eval/run_llava.py` as baseline for inference, you should be careful with the args. In my case I noticed that the `run_llava.py` file will merge the LoRA weights if you specify a `model-base`, and they were already merged, hence the poor performance on inference.

If the weights are merged:
- `model-path` should include the path to your fine-tuned model.
- `model-base` should be `None`.

If the weights are not merged, you should also specify a `model-base` to merge them.
- `model-path` should include the path to your fine-tuned model.
- `model-base` should be your base model e.g. `'liuhaotian/llava-v1.5-7b'`.
