### ISSUE TITLE
Can the code for generating instruction data using GPT-4 be made public?

### ISSUE THREAD

**Issue by gray311** [haotian-liu/LLaVA#87]
Can the code for generating instruction data using GPT-4 be made public?
Because I have two related questions:
1. I would like to know if you use bounding boxes when generating all three types of data? Because table 11 and table 12 in your paper do not contain bounding boxes.
2. I see that all the queries in the data (llava_instruct_150k.json) are marked as from human, how did you collect these queries? Is the self-instrut method used?

I would appreciate it if you could answer my question!

**Comment by haotian-liu** [comment]
Hi @gray311, the conversation data was generated without the bounding boxes, while the detailed description and reasoning data is generated with bounding boxes.

We generate the data by querying text-only GPT-4 following a similar pipeline as self-instruct, except that we are using fewer few-shot samples.  And marking them as `Human: ` and `GPT` is simply complying with the format in `Vicuna` code base that we build with.

All system messages, prompts, and few-shot samples are released [here](https://github.com/haotian-liu/LLaVA/tree/main/playground/data/prompts).  You may refer to them on detailed format and content that we used to generate these data.

Please let me know if you have further concerns.

**Comment by gray311** [comment]
> o

Thank you for your reply!

I have one more question, where did you guys get this query from in the process of generating the conversations?
![屏幕截图 2023-05-04 211052](https://user-images.githubusercontent.com/64787301/236215074-21e7ca2d-a79f-49db-935c-9cf9e23441b8.png)

**Comment by haotian-liu** [comment]
@hjjpku Your understanding is correct :)  And for complex reasoning and detailed description, we also add bounding boxes.  You may refer to [here](https://github.com/haotian-liu/LLaVA/tree/main/playground/data/prompts) for each prompt that we use.

**Comment by haotian-liu** [comment]
@gray311 Regarding `query` please see my response above.  And no-instruction tuning means that we only perform the first stage training, and do the evaluation.

**Comment by gray311** [comment]
@haotian-liu Thanks for your reply!

**Comment by gray311** [comment]
@hjjpku Thanks for your reply!

**Comment by gray311** [comment]
@RyanHuangNLP I think you are right.

**Comment by rex-yue-wu** [comment]
@haotian-liu Great work. I have a follow-up question -- after you create instruction-following samples, how do you reject a bad generated sample? I didn't see it anywhere in the paper, but I am curious about it, as I probably need to follow your work and generate more samples.

**Comment by YoojLee** [comment]
@haotian-liu hi, thanks for such a great work. I have one follow-up question, why did you decide to not include bounding boxes into the context for the conversation type? I think, given the object information as a context, GPT-4 can generate more accurate answers for the questions regarding object location or object counts! Your reply would help me a lot, thanks!
