### ISSUE TITLE
The actual training sequence

### ISSUE THREAD

**Issue by jxy** [haotian-liu/LLaVA#9]
I found the conversation here https://github.com/haotian-liu/LLaVA/blob/6520ad9067e0484000ba4fb20dbe9eaa5a80aa84/llava/conversation.py#L165-L194

Given the code here https://github.com/haotian-liu/LLaVA/blob/6520ad9067e0484000ba4fb20dbe9eaa5a80aa84/llava/conversation.py#L26-L35

This seems to tell me that the actual training sequence is rather

```
f'{system}###Human: {instruct}###Assistant: {completion}###'
```

There doesn't seem to be any additional `\n` as mentioned in Table 2 of the paper.

**Comment by haotian-liu** [comment]
Thank you for your interest in our work, and for pointing this out.

We will fix this discrepancy in the future release.
