### ISSUE TITLE
the lightning training script

### ISSUE THREAD

**Issue by StrangeTcy** [haotian-liu/LLaVA#90]
That amazing script you mention in the readme for training [LLaVA Lightning](https://github.com/haotian-liu/LLaVA#train-llava-lightning): 
`bash ./scripts/train_lightning.sh {v0,v1}`?
Well, it doesn't exist

**Comment by haotian-liu** [comment]
Sorry that was not committed and pushed successfully. Just uploaded the script. Thanks!

**Comment by StrangeTcy** [comment]
Thanks!
