### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'images'

### ISSUE THREAD

**Issue by jihan-yin** [haotian-liu/LLaVA#92]
I'm trying to set up the finetuning script locally, but am getting this error when testing the model in `train.py`. I'm manually passing in a single sample from the lazy dataset, and the error makes sense - I don't see where in the code we actually adapt the model's forward function to actually use the vision tower. Am I missing a setup step or something?

**Comment by jihan-yin** [comment]
Just ran the finetuning script fully, and am getting `TypeError: forward() got an unexpected keyword argument 'images'`

**Comment by haotian-liu** [comment]
Hi, thank you for your interest in our work.  To better understand the issue, can you share the command that you use?

**Comment by jihan-yin** [comment]
Yup - it's pretty much what you have outlined in the repo for finetuning:
```
torchrun --nnodes=1 --nproc_per_node=8 --master_port=25001 \\
        llava/train/train_mem.py \\
        --model_name_or_path {VICUNA_LOCAL_PATH} \\
        --data_path {LLAVA_DATA_LOCAL_PATH} \\
        --instruct_data_path {SELF_INSTRUCT_DATA_LOCAL_PATH} \\
        --use_pretrain_data True \\
        --instruct_data_proportion 0.25 \\
        --pretrain_data_proportion 0.25 \\
        --image_folder {COCO_2014_LOCAL_PATH} \\
        --vision_tower openai/clip-vit-large-patch14 \\
        --pretrain_mm_mlp_adapter {PRETRAIN_ADAPTER_LOCAL_PATH} \\
        --mm_vision_select_layer -2 \\
        --mm_use_im_start_end True \\
        --bf16 True \\
        --output_dir /opt/ml/checkpoints/mix_pretrain_0.25_instruct_0.25 \\
        --num_train_epochs 3 \\
        --per_device_train_batch_size 4 \\
        --per_device_eval_batch_size 4 \\
        --gradient_accumulation_steps 1 \\
        --evaluation_strategy 'no' \\
        --save_strategy 'steps' \\
        --save_steps 5000 \\
        --save_total_limit 3 \\
        --learning_rate 2e-5 \\
        --weight_decay 0. \\
        --warmup_ratio 0.03 \\
        --lr_scheduler_type 'cosine' \\
        --logging_steps 1 \\
        --tf32 True \\
        --fsdp 'full_shard auto_wrap' \\
        --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \\
        --model_max_length 1024 \\
        --gradient_checkpointing True \\
        --lazy_preprocess True \\
        --report_to wandb 
```

**Comment by jihan-yin** [comment]
But yeah, I just don't see how the model is constructed to take in 'images' in the forward call, since we're using the `LlamaForCausalLM` class which doesn't handle multimodal inputs

**Comment by haotian-liu** [comment]
Hi @jihan-yin, are you using the latest code base?  You can see from [here](https://github.com/haotian-liu/LLaVA/blob/main/llava/train/train.py#L465) that it will use `LlavaLlamaForCausalLM` when you provide `--vision_tower` in argument.

If you are using the latest code base, please share the full error log so that I can better understand the issue.  Thanks.

**Comment by jihan-yin** [comment]
Ah, I am not using the latest version. Looks like I need to update - thanks

**Comment by haotian-liu** [comment]
Yep, please try upgrading the code base, as for the older code base, you need to install our customized transformers package [here](https://github.com/haotian-liu/transformers_llava).

Upgrading to the latest code base removes that dependency, and we can make upgrades directly in this main code base.  It also supports more Vicuna models and new features :)

Please let me know if you have further questions, thanks.

**Comment by jihan-yin** [comment]
Hey @haotian-liu, now I am getting an error stating
```
File "/workspace/llava/llava/model/llava.py", line 430, in initialize_vision_tokenizer    assert input_embeddings.shape == embed_tokens_weight.shape | Traceback (most recent call last): File "llava/train/train_mem.py", line 13, in <module> train() File "/workspace/llava/llava/train/train.py", line 615, in train model.initialize_vision_tokenizer( File "/workspace/llava/llava/model/llava.py", line 430, in initialize_vision_tokenizer assert input_embeddings.shape == embed_tokens_weight.shape
```.

I am passing in `--pretrain_mm_mlp_adapter` as the pretrain checkpoint listed in the repo at https://huggingface.co/liuhaotian/LLaVA-13b-pretrain-projector-v0/blob/main/LLaVA-13b-pretrain-projector-v0-CC3M-595K-original_caption.bin. I'm still running with the same commands as above - should I be changing something?

**Comment by haotian-liu** [comment]
@jihan-yin My apologies, there is a fix that was not merged to the latest code base.  I just applied that fix, could you please pull the latest code base and try again?  Thank you.

**Comment by jihan-yin** [comment]
Ah I ended up applying the same fix locally, glad to see it's in main as well! Thanks for the fast response too, will patch and try again
