### ISSUE TITLE
[Question] 'Results do not correspond to current VQA set' when evaluating in VQAv2

### ISSUE THREAD

**Issue by SCZwangxiao** [haotian-liu/LLaVA#926]

**Comment by SCZwangxiao** [comment]
Submit results of all test set

**Comment by HireTheHero** [comment]
@SCZwangxiao So what was the problem? Do we need to download v2 test set from [official website](https://visualqa.org/download.html)?
![image](https://github.com/haotian-liu/LLaVA/assets/65780758/30070db3-08e0-45f8-9a27-7268fad5c515)
