### ISSUE TITLE
[Question] How to use my model after I finetuned it using finetune_lora_task.sh on my own dataset?

### ISSUE THREAD

**Issue by oxjohanndiep** [haotian-liu/LLaVA#937]
### Question

Hello,

I finetuned the model using the finetune_lora_task.sh script on my own custom data. After running it for 12 hours, the training finishes without error, and I got a folder with the following items:

![image](https://github.com/haotian-liu/LLaVA/assets/105214231/be6a9601-886e-463b-8279-41a300630b00)

How do I now use this model for inference? It does not contain any of those pytorch_model.bin files (https://huggingface.co/lmsys/vicuna-13b-v1.5/tree/main), so I am not sure if it saved everything.

Every help is appreciated.

**Comment by ilyesbk11** [comment]
Hello @oxjohanndiep 
can I ask you some questions ?

**Comment by oxjohanndiep** [comment]
Sure

**Comment by ilyesbk11** [comment]
What is the size of your data, and what is the computational power used to fine-tune the model ?
What's the GPU used and did you perform it locally ?
Also, can you provide the script used.
Thank you for your time.

**Comment by oxjohanndiep** [comment]
> What is the size of your data, and what is the computational power used to fine-tune the model ? What's the GPU used and did you perform it locally ? Also, can you provide the script used. Thank you for your time.

You can find everything you asked for in the README of this repo.

**Comment by ilyesbk11** [comment]
Yes I know so I just wanted to know more details since you did the fine-tuning.

**Comment by anonymous-atom** [comment]
@oxjohanndiep can you share the file/script after editing finetune_lora_task.sh ? Like how you loaded the LoRA weights ?

**Comment by anonymous-atom** [comment]
@oxjohanndiep You can merge the LoRA weights using [scripts/merge_lora_weights.py](https://github.com/haotian-liu/LLaVA/blob/main/scripts/merge_lora_weights.py). Also make sure to use correct base model.

Then you will get an output folder with weights and config file which you can further use using Gradio Web GUI or CLI as mentioned in README.md

**Comment by SoniaGrh** [comment]
Try to use the Predictor class in the file [predict.py](https://github.com/haotian-liu/LLaVA/blob/main/predict.py) and replace the setup function of the class with this:

def setup(self) -> None:
self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model("checkpoints/llava-v1.5-13b-task-lora", model_name="llava-v1.5-13b-lora-finetuned", model_base="liuhaotian/llava-v1.5-13b", load_8bit=False, load_4bit=False)

**Comment by AI-Aether** [comment]
> Try to use the Predictor class in the file [predict.py](https://github.com/haotian-liu/LLaVA/blob/main/predict.py) and replace the setup function of the class with this:
> 
> ```
> def setup(self) -> None:
>     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model("checkpoints/llava-v1.5-13b-task-lora", model_name="llava-v1.5-13b-lora-finetuned", model_base="liuhaotian/llava-v1.5-13b", load_8bit=False, load_4bit=False)
> ```

Can I run this even without merging the weights and just with the adapter_model.bin files?
