### ISSUE TITLE
about inference by batch encode

### ISSUE THREAD

**Issue by RupertLuo** [haotian-liu/LLaVA#94]
The '[PAD]' token's id is 32003, but embedding matrix's shape is [32003,5120] in given weight, which means when I do batch inference, it will come out an error , how to fix it ?

**Comment by RupertLuo** [comment]
![image](https://user-images.githubusercontent.com/36270260/236189126-6294a246-26dc-49b8-a06e-5120b0668a7d.png)

**Comment by haotian-liu** [comment]
Hi @RupertLuo, thank you for your interest in our work.

Can you provide the command you use and the full error log for me to better understand the problem and better assist?  Thanks.

**Comment by RupertLuo** [comment]
是我自己写的脚本，就是参照 /llava/eval/run_llava.py 把模型参数加载进去，然后用的我自己的数据集，每条数据的prompt不一样长，我用 pad_sequence 把它们pad到等长，pad index 用的 32003
![image](https://user-images.githubusercontent.com/36270260/236380336-469ebbc0-cc4b-47ab-83c1-7bb686c6297c.png)
然后这个 idx 在，embeding 矩阵里面是没有的，因为embedding矩阵维度是 （32003，5120），也就是最大idx是32002，所以爆这个错了, 我这里在代码中 print了input中最大的index，和embedding的shape

**Comment by RupertLuo** [comment]
![image](https://user-images.githubusercontent.com/36270260/236427959-b274e085-f8ee-46cd-a225-cf6b3dc01bb2.png)
做generation的时候是不是要用这个idx做 padding

**Comment by haotian-liu** [comment]
I see, I guess you may use any token for `PAD` but make sure that they are masked out during the inference.  There are some issues with the tokenizer config currently, but anyway the embedding of the `PAD` token will not make sense, as it has never been optimized (they are masked out during the training).

**Comment by youweiliang** [comment]
Hi @haotian-liu ,
Thanks for the nice work! Does using the unknown token `<unk>` for padding make sense?

**Comment by haotian-liu** [comment]
Yes it makes sense, and starting from v1 checkpoints, it uses `<unk>` by default.

**Comment by RupertLuo** [comment]
Thanks!
