### ISSUE TITLE
[Usage] How can I use the LoRA checkpoints for finetuning on custom data ? I tried but ran into some issues

### ISSUE THREAD

**Issue by anonymous-atom** [haotian-liu/LLaVA#947]
### Describe the issue

Issue:  I am trying to finetune LLaVA using LoRA checkpoints using the [finetune_task_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh) but running into some checkpoints loading issue.

Also should I used pretrained projectors or LLaVA LoRA pre-trained weights ? @haotian-liu 
Command:
```
#!/bin/bash

deepspeed llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path liuhaotian/llava-v1.5-13b \   **Don't we need to load LoRA checkpoints here ? Or where then ?**
    --version v1 \
    --data_path ./playground/data/llava_v1_5_mix665k.json \
    --image_folder ./playground/data \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-13b-task-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```
I chnaged it to below:
```

#!/bin/bash

deepspeed llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path liuhaotian/llava-v1.5-13b-lora \
    --version v1 \
    --data_path ./playground/data/llava_v1_5_mix665k.json \
    --image_folder ./playground/data \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-13b-task-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```
Log: 
```
no pytorch_model.bin file found
```

![image](https://github.com/haotian-liu/LLaVA/assets/74659873/2534c2a6-21c1-4048-ba3e-2a8fc22ba926)

This is what happens when I train using default [finetune_task_lora.sh](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_task_lora.sh) script.

**Comment by anonymous-atom** [comment]
@henrycjh @FHL1998 can you give it a look ? When I am tryin to load the pre-trained checkpoints from [https://huggingface.co/liuhaotian/llava-v1.5-13b-lora/tree/main](https://huggingface.co/liuhaotian/llava-v1.5-13b-lora/tree/main) they they aren't in the required format. 
Like I am tryin to load LoRA checkpoints to finetune, but can't get it quite right.

**Comment by anonymous-atom** [comment]
@oxjohanndiep can you also give a look ?

**Comment by anonymous-atom** [comment]
Ok seemse like finetuning is workin, but the model is not producing any output.

**Comment by anonymous-atom** [comment]
Like when I am using the finetuned model through gradio it timeouts and don't produce any output.

**Comment by oxjohanndiep** [comment]
Have you merged the LORA weights at the end with the pre-trained weights?

**Comment by anonymous-atom** [comment]
@oxjohanndiep yeah I used it like below simply

![image](https://github.com/haotian-liu/LLaVA/assets/74659873/0889f83f-a114-4a74-a5aa-0266e27fc927)

**Comment by oxjohanndiep** [comment]
Can you use this script: https://github.com/haotian-liu/LLaVA/blob/main/scripts/merge_lora_weights.py?

**Comment by anonymous-atom** [comment]
Yes I used this script but I am still getting below issue/warning:

```
Some weights of LlavaLlamaForCausalLM were not initialized from the model checkpoint at lmsys/vicuna-13b-v1.5 and are newly initialized: ['model.mm_projector.0.weight', 'model.mm_projector.2.weight', 'model.mm_projector.2.bias', 'model.mm_projector.0.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

**Comment by anliyuan** [comment]
did you fix this？

**Comment by anonymous-atom** [comment]
@anliyuan which issue you are facin exactly ?

**Comment by anliyuan** [comment]
> @oxjohanndiep yeah I used it like below simply
> 
> ![image](https://private-user-images.githubusercontent.com/74659873/293013587-0889f83f-a114-4a74-a5aa-0266e27fc927.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzk1MzEsIm5iZiI6MTcwNDE3OTIzMSwicGF0aCI6Ii83NDY1OTg3My8yOTMwMTM1ODctMDg4OWY4M2YtYTExNC00YTc0LWE1YWEtMDI2NmUyN2ZjOTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA3MDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMmE2OGFjY2FmMGE0ZTUyZTkzMWI5YzMyY2Q3ZjJjNjAxNzliMjdlYjk0ODlhNmJmNDAxMzAyN2MxNTE4Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dWWhsjCRXiMXLJ-4-3QQqW4W3Y5kG6KFCNOHSO3ZM_8)

this one

**Comment by anliyuan** [comment]
> Yes I used this script but I am still getting below issue/warning:
> 
> ```
> Some weights of LlavaLlamaForCausalLM were not initialized from the model checkpoint at lmsys/vicuna-13b-v1.5 and are newly initialized: ['model.mm_projector.0.weight', 'model.mm_projector.2.weight', 'model.mm_projector.2.bias', 'model.mm_projector.0.bias']
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> ```

this one.

**Comment by attnmamba** [comment]
@anonymous-atom Were you trying to start finetuning starting from `liuhaotian/llava-v1.5-13b`? 

Can you share your final version of `finetune_task_lora.sh` that is working?

**Comment by mfj9999** [comment]
> > 是的，我使用了这个脚本，但我仍然遇到以下问题/警告：
> > ```
> > Some weights of LlavaLlamaForCausalLM were not initialized from the model checkpoint at lmsys/vicuna-13b-v1.5 and are newly initialized: ['model.mm_projector.0.weight', 'model.mm_projector.2.weight', 'model.mm_projector.2.bias', 'model.mm_projector.0.bias']
> > You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> > ```
> 
> 这个。

hello, I also have this question,have you solved it?

**Comment by ShristiDasBiswas** [comment]
Hi, if you were able to solve this issue, could you please share some solutions/idea? Thanks
