### ISSUE TITLE
How to get the llava 13b v1

### ISSUE THREAD

**Issue by penghe2021** [haotian-liu/LLaVA#96]
### Question

From the https://huggingface.co/liuhaotian, I cant find the llava 13b delta v1, maybe I have some misunderstanding, can you tell me where to find the delta weight for the llava 13b v1 model, thank.

**Comment by haotian-liu** [comment]
Hi, we'll release more LLaVA checkpoints based on Vicuna-v1 weights soon, stay tuned!

**Comment by penghe2021** [comment]
Thank!
