### ISSUE TITLE
How to use the BLIP synthetic caption?

### ISSUE THREAD

**Issue by PoseidomWong** [haotian-liu/LLaVA#97]
I found that there is a content about blip caption in the introduction of pretrain data. I would like to ask how to combine the original CC3M data caption with the blip caption, and how to use it?

Thanks for your time!

**Comment by haotian-liu** [comment]
Note that we only used the original CC3M data caption in our v0 release.  If you'd like to combine them, you may directly modify the annotation file, and include the response as "GPT".

**Comment by PoseidomWong** [comment]
I see. Thank you very much
