### ISSUE TITLE
[Question] TextVQA’s OCR

### ISSUE THREAD

**Issue by bruceisme** [haotian-liu/LLaVA#976]
### Question

In ./playground/data/eval/textvqa/llava_textvqa_val_v051_ocr.jsonl, the "text" part of each piece of data contains the **Reference OCR token** content. May I ask where this part of OCR is obtained from?

**Comment by pipilurj** [comment]
Hi! I also have the same question.

**Comment by haotian-liu** [comment]
It comes from the TextVQA's dataset.

[Rosetta OCR tokens [v0.2]](https://dl.fbaipublicfiles.com/textvqa/data/TextVQA_Rosetta_OCR_v0.2_train.json)

**Comment by a-runner** [comment]
So during testing, the OCR results were already fed to the large model? Does that mean the large model doesn't need to perform the OCR task itself?
