### ISSUE TITLE
[Question] pretrain result test

### ISSUE THREAD

**Issue by scarydemon2** [haotian-liu/LLaVA#995]
### Question

In the pretrain stage, I input a language model + a CLIP ViT, with the adapter being newly initialized. However, in cli.py, a llava model needs to be input, but the pretrain result only includes the weight of the adapter, so it cannot be used for inference through cli.py. Then, is there any method to test the result of the pretraining

**Comment by zihui-debug** [comment]
> ### Question
> In the pretrain stage, I input a language model + a CLIP ViT, with the adapter being newly initialized. However, in cli.py, a llava model needs to be input, but the pretrain result only includes the weight of the adapter, so it cannot be used for inference through cli.py. Then, is there any method to test the result of the pretraining

hello, I have the same question. How did you deal with it?
